Repository aziontech/azion-console-kit, pull requests merged in 2023-12, with the labels that each got.

#496 [UXE-1406] Fix multi select theme
  src/assets/themes/scss/themes/azion-dark/_extensions.scss
  src/assets/themes/scss/themes/azion-dark/extended-components/_multiselect.scss
  src/assets/themes/scss/themes/azion-light/_extensions.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_multiselect.scss
Labels: theming

#502 [NO-ISSUE] feat: migrate block real time purge
  src/router/routes/real-time-purge/index.js
  src/services/real-time-purge/contact-sales-service.js
  src/services/real-time-purge/index.js
  src/tests/services/real-time-purge/contact-sales-service.test.js
  src/views/RealTimePurge/CreateView.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: enhancement

#512 [NO-ISSUE] feat: update production deploy workflow
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
Labels: bug, enhancement, dependencies

#506 [EDU-2960] chore: review marketplace uxw
  src/views/Marketplace/MarketplaceHomeView.vue
  src/views/Marketplace/SolutionView.vue
  src/views/Marketplace/components/PermissionsFieldset.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
Labels: writing

#513 [ENG-28766] CLI callback page
  src/assets/themes/scss/themes/azion-dark/_variables.scss
  src/assets/themes/scss/themes/azion-light/_variables.scss
  src/router/hooks/beforeEachRoute.js
  src/router/index.js
  src/router/routes/cli-callback-routes/index.js
  src/views/CliCallback/FailView.vue
  src/views/CliCallback/SuccessView.vue
Labels: enhancement

#511 [ENG-28096] feat: rules engine list and delete service
  src/helpers/get-array-changed-indices.js
  src/helpers/get-first-api-error.js
  src/helpers/index.js
  src/router/routes/edge-application-routes/index.js
  src/services/axios/errors/cannot-reorder-default-rule.js
  src/services/axios/errors/index.js
  src/services/edge-application-rules-engine-services/delete-rules-engine-service.js
  src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
  src/services/edge-application-rules-engine-services/index.js
  src/services/edge-application-rules-engine-services/list-rules-engine-service.js
  src/services/edge-application-rules-engine-services/reorder-rules-engine-service.js
  src/services/users-services/create-users-service.js
  src/services/users-services/edit-another-user-service.js
  src/services/users-services/edit-users-service.js
  src/templates/empty-results-block/index.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/list-table-block/no-header.vue
  src/tests/services/edge-application-rules-engine-services/delete-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/list-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/reorder-rules-engine-service.test.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement, unit-tests, code-refactor

#516 [EDU-2952] refactor: uxw review your settings and users management
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/Users/ListView.vue
  src/views/YourSettings/EditView.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: writing

#517 [EDU-2962] refactor: purge texts
  src/services/sidebar-menus-services/menus.js
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
  src/views/RealTimePurge/ListView.vue
Labels: writing
