Repository aziontech/azion-console-kit, pull requests merged in 2024-06, with the labels that each got.

#1216 [UXE-3244] feat: add autofilterfocus to dropdown in import github
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
Labels: enhancement

#1218 [UXE-2496] fix: remove send feedback from help-center footer link options
  src/templates/help-center-block/index.vue
Labels: bug

#1219 [UXE-3394] fix: loop when trying to load the default rule engine in edge app
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1222 [UXE-3307] fix: it is closing the drawer when an error occurs
  src/views/EdgeFirewallFunctions/Drawer/index.vue
Labels: bug

#1221 [UXE-1871] refactor: account settings infinite loading in city and region fields
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: bug

#1223 [NO-ISSUE] fix: ensure to create edge firewall with correct params with custom response rule engine
  src/services/edge-firewall-rules-engine-services/create-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/edit-edge-firewall-rules-engine-service.js
Labels: bug

#1224 [UXE-2859] fix: releasing behavior selection in the default rule
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1226 [UXE-2934] fix: domain selection is adapting incorrectly
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: bug

#1228 [UXE-3363] refactor: change edge services resources type radio group to dropdown
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
Labels: code-refactor

#1225 [UXE-3264] fix: issues with checkbox disabled, tag in radio and empty list in real time purge
  src/services/real-time-purge/list-real-time-purge-service.js
  src/templates/form-fields-inputs/fieldCheckboxBlock.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/list-table-block/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: bug, code-refactor

#1227 [UXE-3113] feat: add search filter create modal
  src/services/solutions-services/index.js
  src/services/solutions-services/list-solutions-service.js
  src/services/solutions-services/make-solutions-base-url.js
  src/templates/create-modal-block/index.vue
  src/templates/create-modal-block/make-create-modal-block.vue
  src/templates/navbar-block/create.vue
  src/tests/services/solutions-services/list-solutions-service.test.js
Labels: enhancement, unit-tests, code-refactor

#1229 [UXE-2051] refactor: adjusted empty block component ui following figma
  src/templates/empty-results-block/index.vue
  src/templates/error-page-block/index.vue
  src/views/ActivityHistory/ListView.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/EdgeNode/ListViewTabServices.vue
  src/views/EdgeServices/ListViewTabResources.vue
  src/views/PersonalTokens/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: enhancement

#1230 [UXE-3113] refactor: remove search field from import from github tab
  src/templates/create-modal-block/index.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
Labels: code-refactor

#1232 [NO-ISSUE] chore: upgrade project version from 1.15.4 to 1.15.5
  package.json
Labels: project version

#1231 [UXE-2500] fix: add font-medium in waf drawer and big number block
  src/templates/info-drawer-block/info-labels/big-number.vue
  src/views/WafRules/Drawer/index.vue
Labels: bug

#1237 [NO-ISSUE] chore: upgrade project version from 1.15.5 to 1.15.6
  package.json
Labels: project version

#1238 DEPLOY 2024.06.05
  package.json
  src/templates/create-modal-block/index.vue
  src/templates/info-drawer-block/info-labels/big-number.vue
  src/views/WafRules/Drawer/index.vue
Labels: DEPLOY

#1240 [EDU-4692] chore: review content in Personal Token modal
  src/services/personal-tokens-services/create-personal-tokens-service.js
  src/tests/services/personal-tokens-services/create-personal-tokens-service.test.js
  src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
Labels: writing, waiting-for-uxe-to-merge

#1243 [UXE-3468] fix: remove div classes in field dropdown input block
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
Labels: bug

#1242 [UXE-3355] fix: added validation to http and https inputs in edge application
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
Labels: bug

#1245 [NO-ISSUE] chore: upgrade project version from 1.15.6 to 1.15.7
  package.json
Labels: project version

#1246 DEPLOY 2024.06.06
  package.json
  src/services/personal-tokens-services/create-personal-tokens-service.js
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/tests/services/personal-tokens-services/create-personal-tokens-service.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
  src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
Labels: DEPLOY

#1235 [UXE-2398] fix: change sizes of filter area in real time metrics
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/advanced-filter/index.vue
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
Labels: bug

#1244 [UXE-2265] fix: add class to prevent line break in breadcrumb
  src/templates/page-heading-block-tabs/index.vue
  src/templates/page-heading-block/index.vue
Labels: bug, do-not-merge

#1249 [NO-ISSUE] fix: phase options showing in rules engine create
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1241 [UXE-3391] feat: add auto focus to dropdowns with filter
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/WafRules/ListWafRulesTuning.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: enhancement

#1251 [NO-ISSUE] chore: upgrade project version from 1.15.7 to 1.15.8
  package.json
Labels: project version

#1252 DEPLOY 2024-06-06
  package.json
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/advanced-filter/index.vue
  src/templates/page-heading-block-tabs/index.vue
  src/templates/page-heading-block/index.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/WafRules/ListWafRulesTuning.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: DEPLOY

#1254 [UXE-2396] fix: add scroll when tabs are bigger than screen
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
Labels: bug

#1255 [UXE-3311] fix: add width in input filter for dropdown
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: bug

#1248 [UXE-3328] bug: profile menu position
  src/templates/profile-block/index.vue
Labels: bug

#1256 [UXE-3314] fix: update validation in users form
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: bug, enhancement

#1257 [UXE-2397] fix: remove space between buttons when screend is medium
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Labels: bug

#1259 [UXE-2751] fix: ensure to display Azion SAN certificate for domains without certificate on domain list
  src/services/domains-services/list-domains-service.js
  src/tests/services/domains-services/list-domains-service.test.js
Labels: bug

#1260 [UXE-1673] fix: apply read only behavior edge pulse editors
  src/views/EdgePulse/FormFields/FormFieldsDefault.vue
  src/views/EdgePulse/FormFields/FormFieldsTag.vue
Labels: bug

#1261 [UXE-2647] fix: add button behavior disabled value based on latest behavior
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1262 [UXE-3324] fix: fixed early validation in the PhoneNumber fields in Your Settings and Users
  src/services/users-services/load-another-user-service.js
  src/services/users-services/load-user-service.js
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: bug, code-refactor

#1263 [UXE-3326] add validation to field full name and change o name do field to full name"
  src/views/Home/FormFields/FormFieldsHome.vue
  src/views/Home/HomeView.vue
Labels: bug

#1266 [UXE-3460] fix: update label of import a Trusted CA certificate field
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
Labels: writing

#1265 [UXE-3459] fix: typo in subtitle of an create digital certificates field
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
Labels: writing

#1268 [UXE-3589] fix: adjust extractApiError method to handle any key
  src/services/data-stream-services/create-data-stream-service.js
  src/services/data-stream-services/edit-data-stream-service.js
Labels: bug

#1272 [NO-ISSUE] fix: workflow e2e test running step
  .github/workflows/assign-pr.yml
  .github/workflows/e2e-tests.yml
Labels: bug, e2e tests

#1264 [UXE-3351] fix: handle toast in submit method in your settings
  src/services/users-services/edit-users-service.js
  src/views/YourSettings/EditView.vue
Labels: bug

#1270 [UXE-3580] feat: edge firewall change to new selectors
  src/services/edge-firewall-services/load-edge-firewall-service.js
  src/tests/services/edge-firewall-services/load-edge-firewall-service.test.js
  src/views/EdgeFirewall/CreateView.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: enhancement

#1271 [UXE-3581] chore: edge functions change to use switch field block
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: enhancement, code-refactor

#1275 [UXE-3463] fix: add sortField property to status column
  src/views/DigitalCertificates/ListView.vue
Labels: bug

#1274 [UXE-3582] feat: add FieldSwitchBlock in edge dns
  src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
Labels: enhancement

#1269 [UXE-3329] fix: change billing redirect url
  src/helpers/get-static-urls-by-environment.js
  src/tests/helpers/get-static-urls-by-environment.test.js
Labels: bug

#1278 [UXE-3470] fix: changed sufix in events request and response data section
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
Labels: bug

#1276 [UXE-3585] refactor: replace on variables product switch to use field switch block
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: enhancement, code-refactor

#1280 [UXE-3476] feat: adding modal to copy the created domain
  src/views/Domains/CreateView.vue
  src/views/Domains/Dialog/CopyDomainDialog.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Home/HomeView.vue
Labels: console-measurements

#1282 [UXE-3591] fix: change fields help text order
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1277 [NO-ISSUE] refactor: new props and names to computed props in main settings modules
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: code-refactor

#1281 [UXE-3609] fix: remove logged user from users management list
  src/services/users-services/list-users-service.js
  src/tests/services/users-services/list-users-service.test.js
  src/views/Users/ListView.vue
Labels: bug, unit-tests, code-refactor

#1283 [UXE-3593] fix: add binding to useTls option in datastreaming
  src/helpers/get-static-urls-by-environment.js
  src/services/data-stream-services/create-data-stream-service.js
  src/services/data-stream-services/edit-data-stream-service.js
  src/services/data-stream-services/load-data-stream-service.js
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/tests/services/data-stream-services/create-data-stream-service.test.js
  src/tests/services/data-stream-services/edit-data-stream-service.test.js
  src/views/DataStream/CreateView.vue
  src/views/DataStream/EditView.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1284 [UXE-3616] fix: Hide sampling section from datastreaming form
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1286 fix: dataset does not load in data stream
  src/services/data-stream-services/load-data-stream-service.js
  src/tests/services/data-stream-services/create-data-stream-service.test.js
  src/tests/services/data-stream-services/edit-data-stream-service.test.js
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/Users/ListView.vue
Labels: bug

#1287 [UXE-3614] fix: add button in rules engine list open the drawer by the current phase
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: bug

#1290 [UXE-3462] fix: lets encrypt certificate editing validation
  src/helpers/azion-documentation-catalog.js
  src/router/routes/digital-certificates-routes/index.js
  src/tests/helpers/azion-documentation-catalog-product-guide.test.js
  src/views/DigitalCertificates/EditView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: bug

#1285 [UXE-3588] fix: added readonly for non-custom templates in the data set field
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1291 [UXE-3590] fix: dataset does not load custom a template in data stream
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1292 [UXE-3462] fix: hide action bar for lets encrypt certificate on Edit Digital Certificate view
  src/views/DigitalCertificates/EditView.vue
Labels: bug

#1293 [EDU-4734] chore: review toast - Change email in Your Settings
  src/views/YourSettings/EditView.vue
Labels: writing

#1297 [NO-ISSUE] fix: loop when trying to load the default rule engine in edge app
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1296 [UXE-3633] fix: adjusted wrong timer in deploy project view
  src/views/CreateNew/DeployView.vue
Labels: bug

#1295 [UXE-3586] refactor: replace on waf product switch to use field switch and radio
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/form-fields-inputs/fieldGroupSwitch.vue
  src/templates/form-fields-inputs/fieldRadioBlock.vue
  src/templates/form-fields-inputs/fieldSwitchBlock.vue
  src/templates/selector-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
Labels: enhancement

#1299 [UXE-3587] refactor: replace on your setting page switch to use field switch
  src/templates/form-fields-inputs/fieldSwitchBlock.vue
  src/views/YourSettings/EditView.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: enhancement

#1303 [UXE-1816] feat: implemented the focus error feature in the view your settings
  src/views/YourSettings/EditView.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: enhancement, code-refactor

#1305 [UXE-1816] feat: implemented the focus error feature in the view variables
  src/views/Variables/CreateView.vue
  src/views/Variables/EditView.vue
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: enhancement, code-refactor

#1298 [UXE-1816] feat: implemented the focus error feature in the view user management
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: enhancement, code-refactor

#1300 [UXE-1816] feat: implemented the focus error feature in the view credentials
  src/views/Credentials/CreateView.vue
  src/views/Credentials/EditView.vue
  src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
  src/views/Credentials/FormFields/FormFieldsEditCredentials.vue
Labels: enhancement, code-refactor

#1304 [UXE-1816] feat: implemented the focus error feature in the view personal tokens
  src/views/PersonalTokens/CreateView.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
Labels: enhancement, code-refactor

#1308 [UXE-3476] feat: open dialog to copy domain created after save
  src/views/Domains/CreateView.vue
  src/views/Domains/Dialog/CopyDomainDialog.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: console-measurements

#1309 [UXE-3579] refactor: changed switch input to new selector in team permissions
  src/services/team-permission/list-team-permission-service.js
  src/tests/services/team-permission-services/list-team-permission-service.test.js
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
Labels: code-refactor

#1312 [NO-ISSUE] fix: clean broken cypress e2e tests
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/login.cy.js
  cypress/e2e/real-time-metrics.cy.js
  cypress/fixtures/digital-certificates.json
Labels: bug, e2e tests

#1311 [UXE-3584] refactor: replace on users page switch to use field switch block
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: enhancement, code-refactor

#1313 [UXE-3667] feat: implemented the focus error feature in the view network lists
  src/templates/form-fields-inputs/fieldTextArea.vue
  src/views/NetworkLists/CreateView.vue
  src/views/NetworkLists/EditView.vue
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
Labels: enhancement

#1314 [UXE-3308] fix: add divider to improve user experience in rules engine
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1315 [UXE-3308] chore: revert divider addition in rules engine/criteria
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: invalid

#1316 [UXE-3667] feat: implemented the focus error feature in the edge services and resources tab
  src/templates/create-drawer-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/views/EdgeServices/CreateView.vue
  src/views/EdgeServices/EditView.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
  src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
Labels: enhancement

#1318 [UXE-3594] fix: default values not load in edit data stream
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1319 [UXE-1816] feat: implemented the focus error feature in the view domains
  src/templates/create-form-block/index.vue
  src/templates/edit-form-block/index.vue
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: enhancement, code-refactor

#1320 [UXE-1816] feat: improvement in the focus error method
  src/templates/create-drawer-block/index.vue
  src/templates/create-form-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/edit-form-block/index.vue
Labels: enhancement, code-refactor

#1323 [NO-ISSUE] feat: add toast to playground to check the toast lifespan
  src/views/Playground/PlaygroundView.vue
Labels: enhancement

#1325 [UXE-3667] feat: implemented the focus error feature in the create edge firewall
  src/views/EdgeFirewall/CreateView.vue
Labels: console-measurements

#1322 [UXE-3667] feat: implemented the focus error feature in the digital certificates
  src/templates/form-fields-inputs/fieldText.vue
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/EditView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: enhancement

#1324 [UXE-3722] refactor: implemented the focus error feature on the waf product
  src/views/WafRules/CreateView.vue
  src/views/WafRules/EditView.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: code-refactor

#1321 [UXE-3476] fix: adjust close icon toast sucess and add anchor to edit form
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
Labels: bug

#1327 [UXE-1816] feat: centralization of the scroll focus error method in a composoble
  src/composables/useScrollToError.js
  src/templates/create-drawer-block/index.vue
  src/templates/create-form-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/edit-form-block/index.vue
Labels: enhancement, code-refactor

#1326 [UXE-3586] refactor: replace the description from FormHorizontal to FieldSwitchBlock
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
Labels: code-refactor

#1328 [NO-ISSUE] chore: upgrade project version from 1.15.8 to 1.15.9
  package.json
Labels: project version

#1329 [NO-ISSUE] fix: adjust is enable appication accelerator
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: bug

#1331 chore: upgrade project version from 1.15.9 to 1.16.0
  package.json
Labels: project version

#1334 [UXE-3735] refactor: replace inputSwitch to FieldGroupSwitch
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: code-refactor

#1317 [UXE-3477] fix: change max date timerange limit to updated time
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Labels: bug

#1336 [UXE-3729] refactor: automatic focus on required fields edge nodes
  src/views/EdgeNode/Drawer/index.vue
  src/views/EdgeNode/EditView.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
  src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
  src/views/EdgeNode/TabsView.vue
Labels: code-refactor

#1339 [UXE-3145] refactor: review toasts rules and styles
  src/assets/themes/scss/themes/azion-dark/variables/_message.scss
  src/assets/themes/scss/themes/azion-light/variables/_message.scss
  src/templates/create-drawer-block/index.vue
  src/templates/create-form-block/index.vue
  src/templates/create-modal-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/edit-form-block/index.vue
  src/templates/edit-form-block/no-header.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/templates/sign-in-block/forgot-password.vue
  src/templates/signup-block/account-activation.vue
  src/templates/signup-block/login-with-email-block.vue
  src/templates/toast-block/index.vue
  src/tests/utils/constants.test.js
  src/utils/constants.js
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/Domains/CreateView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeNode/Dialog/Authorize.vue
  src/views/EdgePulse/ListView.vue
  src/views/Marketplace/SolutionView.vue
  src/views/Playground/PlaygroundView.vue
  src/views/RealTimeEventsTieredCache/Drawer/index.vue
  src/views/RealTimePurge/ListView.vue
  src/views/WafRules/Drawer/index.vue
  src/views/YourSettings/EditView.vue
Labels: theming, code-refactor

#1341 [UXE-3736] refactor: automatic focus on required fields real time purge
  src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
  src/views/RealTimePurge/CreateView.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: code-refactor

#1343 [UXE-3745] fix: loop when trying to load the default rule engine in edge app
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1330 [NO-ISSUE] test: add variables E2E
  cypress/e2e/variables.cy.js
  cypress/support/commands.js
  src/templates/action-bar-block/index.vue
  src/templates/empty-results-block/index.vue
  src/templates/list-table-block/index.vue
Labels: e2e tests

#1347 DEPLOY 2024.06.25
  cypress/e2e/variables.cy.js
  cypress/support/commands.js
  package.json
  src/assets/themes/scss/themes/azion-dark/variables/_message.scss
  src/assets/themes/scss/themes/azion-light/variables/_message.scss
  src/templates/action-bar-block/index.vue
  src/templates/create-drawer-block/index.vue
  src/templates/create-form-block/index.vue
  src/templates/create-modal-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/edit-form-block/index.vue
  src/templates/edit-form-block/no-header.vue
  src/templates/empty-results-block/index.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/templates/sign-in-block/forgot-password.vue
  src/templates/signup-block/account-activation.vue
  src/templates/signup-block/login-with-email-block.vue
  src/templates/toast-block/index.vue
  src/tests/utils/constants.test.js
  src/utils/constants.js
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/Domains/CreateView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeNode/Dialog/Authorize.vue
  src/views/EdgePulse/ListView.vue
  src/views/Marketplace/SolutionView.vue
  src/views/Playground/PlaygroundView.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeEventsTieredCache/Drawer/index.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
  src/views/RealTimePurge/ListView.vue
  src/views/WafRules/Drawer/index.vue
  src/views/YourSettings/EditView.vue
Labels: DEPLOY

#1350 refactor: add erro focus on the data stream page
  src/templates/form-fields-inputs/fieldNumber.vue
  src/views/DataStream/CreateView.vue
  src/views/DataStream/EditView.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: code-refactor

#1352 [UXE-1816] feat: improvement in the focus error edge application
  src/services/edge-application-error-responses-services/list-error-responses-service.js
  src/templates/create-drawer-block/index.vue
  src/templates/create-form-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/edit-form-block/index.vue
  src/templates/form-fields-inputs/fieldAutoComplete.vue
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/form-fields-inputs/fieldGroupCheckbox.vue
  src/templates/form-fields-inputs/fieldGroupSwitch.vue
  src/templates/form-fields-inputs/fieldInputGroup.vue
  src/templates/form-fields-inputs/fieldNumber.vue
  src/templates/form-fields-inputs/fieldText.vue
  src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: enhancement, code-refactor

#1351 [QA-1992] test: edge app testing migration to azion-console-kit
  .gitignore
  cypress.config.js
  cypress/e2e/edge_application.cy.js
  cypress/support/commands.js
  src/templates/action-bar-block/index.vue
  src/templates/activity-history-block/index.vue
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/advanced-filter/index.vue
  src/templates/create-modal-block/index.vue
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Labels: e2e tests

#1360 feature/focus error in edge firewall
  src/templates/form-fields-inputs/fieldDropdownIcon.vue
  src/views/EdgeFirewall/EditView.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: console-measurements

#1345 [No-issue] chore: adjust DNS button
  src/views/EdgeDNS/CreateView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/ListView.vue
Labels: writing

#1361 [UXE-3823] fix: toggle menu with filtered table
  cypress/e2e/edge_application.cy.js
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
Labels: bug

#1357 [UXE-3762] fix: load originId field in error responses edition
  src/services/edge-application-error-responses-services/list-error-responses-service.js
  src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
Labels: bug

#1358 [UXE-3792] test: e2mock your settings view
  .eslintrc.cjs
  cypress.config.js
  cypress/e2e/your-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/fixtures/your-settings.json
  src/templates/profile-block/index.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: e2e tests

#1363 [UXE-3793] test: e2e digital certificate crud
  cypress/e2e/digital-certificates.cy.js
  cypress/support/commands.js
  src/templates/page-heading-block/index.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
Labels: e2e tests

#1365 [UXE-3791] test: create e2e test for team permissions
  cypress/e2e/teams-permissions.cy.js
  src/views/TeamsPermissions/CreateView.vue
  src/views/TeamsPermissions/EditView.vue
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
  src/views/TeamsPermissions/ListView.vue
Labels: e2e tests

#1364 [QA-2018] test: dynamically define names of entities to be created by E2E
  cypress/e2e/edge_application.cy.js
  cypress/support/e2e.js
  cypress/support/utils.js
Labels: e2e tests

#1369 [NO-ISSUE] test: refactor e2e digital certificates to use selectors
  cypress/e2e/digital-certificates.cy.js
  cypress/support/commands.js
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
Labels: code-refactor, e2e tests

#1370 [NO-ISSUE] fix: test if origin id is not null or undefined before using toString
  src/services/edge-application-error-responses-services/list-error-responses-service.js
Labels: bug

#1367 [UXE-3692] chore: change segment token
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/factories/analytics-tracking-factory.js
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
Labels: console-measurements

#1371 [QA-2030] test: add README defined e2e test development
  cypress/README.md
Labels: e2e tests

#1375 fix: data stream focus error in submit
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: code-refactor

#1376 chore: upgrade project version from 1.16.1 to 1.16.2
  package.json
Labels: project version

#1377 DEPLOY 2024.06.27
  .eslintrc.cjs
  .github/workflows/pre-merge.yml
  .gitignore
  cypress.config.js
  cypress/README.md
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/example.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/variables.cy.js
  cypress/e2e/your-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/fixtures/your-settings.json
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/support/utils.js
  package.json
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/factories/analytics-tracking-factory.js
  src/services/edge-application-error-responses-services/list-error-responses-service.js
  src/templates/action-bar-block/index.vue
  src/templates/activity-history-block/index.vue
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/advanced-filter/index.vue
  src/templates/create-modal-block/index.vue
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/templates/page-heading-block/index.vue
  src/templates/profile-block/index.vue
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeDNS/CreateView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/ListView.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
  src/views/TeamsPermissions/CreateView.vue
  src/views/TeamsPermissions/EditView.vue
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
  src/views/TeamsPermissions/ListView.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: DEPLOY

#1381 [NO-ISSUE] chore: update segment token
  src/plugins/factories/analytics-tracking-factory.js
Labels: console-measurements

#1384 [NO-ISSUE] chore: upgrade project version from 1.16.2 to 1.16.3
  package.json
Labels: project version

#1386 DEPLOY 2024.06.28
  package.json
  src/plugins/factories/analytics-tracking-factory.js
Labels: DEPLOY

#1388 [UXE-3860] feat: add credit card component to cell table
  src/assets/svg/credit-card-logos/amex-card.vue
  src/assets/svg/credit-card-logos/diners-card.vue
  src/assets/svg/credit-card-logos/discover-card.vue
  src/assets/svg/credit-card-logos/jcb-card.vue
  src/assets/svg/credit-card-logos/mastercard-card.vue
  src/assets/svg/credit-card-logos/visa-card.vue
  src/templates/list-table-block/columns/column-builder.js
  src/templates/list-table-block/columns/credit-card-column.vue
Labels: console-measurements

#1373 [UXE-3789] test: create e2e test for credentials
  cypress/README.md
  cypress/e2e/credentials.cy.js
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/your-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/support/commands.js
  src/templates/form-fields-inputs/fieldText.vue
  src/templates/form-fields-inputs/fieldTextArea.vue
  src/templates/toast-block/index.vue
  src/views/Credentials/CreateView.vue
  src/views/Credentials/EditView.vue
  src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
  src/views/Credentials/FormFields/FormFieldsEditCredentials.vue
  src/views/Credentials/ListView.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: documentation, code-refactor, e2e tests

#1380 [UXE-3859] chore: add new icons
  src/assets/icons/azionicons.scss
  src/assets/icons/azionicons.woff2
Labels: icons

#1390 [QA-2031] refactory: unify selector and refactory e2e tests
  cypress/e2e/credentials.cy.js
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/your-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  src/templates/list-table-block/columns/column-builder.js
Labels: e2e tests

#1337 [QA-2032] test: add network lists E2E test
  cypress/e2e/network-lists.cy.js
  cypress/support/selectors.js
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
Labels: e2e tests

#1382 [QA-2033] test: add variables E2E test
  cypress/e2e/variables.cy.js
  cypress/support/selectors.js
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: e2e tests

#1338 [QA-2034] test: add waf rules E2E test
  cypress/e2e/waf.cy.js
  cypress/support/selectors.js
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
Labels: e2e tests
