Repository aziontech/azion-console-kit, pull requests merged in 2024-10, with the labels that each got.

#1764 [UXE-4954] test: add coverage for redirectToManager guard and update router guards
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/router/hooks/guards/logoutGuard.js
  src/router/hooks/guards/themeGuard.js
  src/router/hooks/redirectToManager.js
  src/router/index.js
  src/tests/router/hooks/redirectToManager.test.js
Labels: enhancement, unit-tests

#1773 [UXE-5134] feat: implements tracking events in edge services
  src/views/EdgeServices/CreateView.vue
  src/views/EdgeServices/EditView.vue
  src/views/EdgeServices/ListView.vue
Labels: console-measurements

#1775 [NO-ISSUE] fix: adjustment to the route guards to standardize execution and dependency injection as parameters.
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/router/hooks/guards/index.js
  src/router/hooks/guards/loadingGuard.js
  src/router/hooks/guards/logoutGuard.js
  src/router/hooks/guards/redirectGuard.js
  src/router/hooks/guards/redirectToManagerGuard.js
  src/router/hooks/guards/themeGuard.js
  src/router/index.js
  src/tests/router/hooks/guards/redirectToManagerGuard.test.js
Labels: bug, unit-tests

#1776 [UXE-5136] feat: implements tracking events in digital certificate
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/EditView.vue
  src/views/DigitalCertificates/ListView.vue
Labels: console-measurements

#1779 [UXE-5132] feat: implements events in records
  src/templates/create-drawer-block/index.vue
  src/views/EdgeDNS/EditView.vue
Labels: console-measurements

#1771 [UXE-5039] feat: fix error message parser in waf tuning load
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
Labels: bug

#1772 [UXE-5149] fix: service keeps loading when there is no service registered
  src/services/edge-node-service-services/create-service-edge-node-service.js
  src/services/edge-node-service-services/load-service-edge-node-service.js
  src/tests/services/edge-node-service-services/create-service-edge-node-service.test.js
  src/tests/services/edge-node-service-services/load-service-edge-node-service.test.js
  src/views/EdgeNode/Drawer/index.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
Labels: bug

#1762 [UXE-4871] feat: change events name and parse error message correctly in the ser…
  src/services/network-lists-services/create-network-list-service.js
  src/services/network-lists-services/edit-network-list-service.js
  src/tests/services/network-lists-services/create-network-list-service.test.js
  src/tests/services/network-lists-services/edit-network-list-service.test.js
  src/views/NetworkLists/CreateView.vue
  src/views/NetworkLists/EditView.vue
  src/views/NetworkLists/ListView.vue
Labels: bug, console-measurements

#1783 [UXE-4942] feat: add Azion Copilot with deepchat to AI Chat component
  azion.config.cjs
  src/modules/azion-ai-chat/azion-ai-chat-block.vue
  src/modules/azion-ai-chat/azion-ai-get-help.vue
  src/modules/azion-ai-chat/contextual-prompts/domains/index.js
  src/modules/azion-ai-chat/contextual-prompts/generic/index.js
  src/modules/azion-ai-chat/contextual-prompts/index.js
  src/modules/azion-ai-chat/index.vue
  src/modules/azion-ai-chat/services/interceptor-service.js
  src/modules/azion-ai-chat/services/make-request-config.js
  src/modules/azion-ai-chat/services/request-interceptor-service.js
  src/modules/azion-ai-chat/tests/make-request-config.test.js
  src/modules/azion-ai-chat/tests/requestInterceptorService.test.js
  src/templates/navbar-block/index.vue
  vite.config.js
Labels: enhancement

#1789 [UXE-5213] refactor: reduce stripe calls
  src/main.js
  src/plugins/StripeIntegrationPlugin.js
  src/plugins/factories/stripe-integration-factory.js
  src/router/routes/billing-routes/index.js
  src/services/billing-services/get-stripe-client-service.js
  src/services/billing-services/index.js
  src/templates/add-payment-method-block/index.vue
  src/tests/plugins/factories/stripe-integration-factory.test.js
  src/tests/services/billing-services/get-stripe-client-service.test.js
  src/views/Billing/Drawer/DrawerPaymentMethod.vue
  src/views/Billing/TabsView.vue
Labels: unit-tests, code-refactor

#1786 [UXE-5007] fix: incorrect ordering in real time events in the ts field
  src/views/RealTimeEvents/Blocks/constants/tabs-events.js
Labels: bug

#1777 [EDU-5476] refactor: Adjust DDoS card description
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: writing

#1787 [UXE-5180] feat: enhance AnalyticsTrackerAdapter refine identify method and introduce reset method
  src/App.vue
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/logoutGuard.js
  src/router/index.js
  src/templates/profile-block/index.vue
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests

#1782 [QA-2249] feat: updated e2e tests to run against prod env
  .github/workflows/cleanup_e2e_tests.yml
  .github/workflows/pre-merge.yml
  .github/workflows/prod-e2e-tests.yml
  cypress.config.prod.js
  cypress.env.example.json
  cypress/README.md
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/e2e/edge-dns/create-edge-dns-zone.cy.js
  cypress/e2e/edge-dns/create-record-type-a.cy.js
  cypress/e2e/edge-dns/create-record-type-aaaa.cy.js
  cypress/e2e/edge-dns/create-record-type-aname.cy.js
  cypress/e2e/edge-dns/create-record-type-caa.cy.js
  cypress/e2e/edge-dns/create-record-type-cname.cy.js
  cypress/e2e/edge-dns/create-record-type-ds.cy.js
  cypress/e2e/edge-dns/create-record-type-mx.cy.js
  cypress/e2e/edge-dns/create-record-type-ns.cy.js
  cypress/e2e/edge-dns/create-record-type-ptr.cy.js
  cypress/e2e/edge-dns/create-record-type-srv.cy.js
  cypress/e2e/edge-dns/create-record-type-txt.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
  cypress/e2e/network-lists/create-network-list-asn.cy.js
  cypress/e2e/network-lists/create-network-list-countries.cy.js
  cypress/e2e/variables/create-secret.cy.js
  cypress/e2e/waf/create-allowed-rule-conditional-query-string.cy.js
  cypress/e2e/waf/create-allowed-rule-conditional-request-body.cy.js
  cypress/e2e/waf/create-allowed-rule-conditional-request-header.cy.js
  cypress/e2e/waf/create-allowed-rule-file-name.cy.js
  cypress/e2e/waf/create-allowed-rule-path-zone.cy.js
  cypress/e2e/waf/create-allowed-rule-raw-body.cy.js
  cypress/e2e/waf/create-waf-rule.cy.js
  cypress/e2e/waf/edit-waf-rule.cy.js
  package.json
  scripts/cleanup.js
Labels: e2e tests

#1781 [UXE-4538] feat: add edge application creation drawer to domains form
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeApplications/Drawer/index.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement

#1795 [NO-ISSUE] fix: adjust to pass group data props and change dataset
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/reports.js
  src/services/billing-services/index.js
  src/templates/graphs-card-block/big-numbers-card.vue
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
Labels: bug

#1800 [UXE-4538] fix: select created app when drawer close
  cypress/e2e/domains/create-domain-edge-application.cy.js
  src/services/edge-application-services/create-edge-application-service.js
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeApplications/Drawer/index.vue
Labels: bug

#1793 [UXE-5191] feat: add digital certificate drawer to domains page
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/services/digital-certificates-services/create-digital-certificates-csr-service.js
  src/services/digital-certificates-services/create-digital-certificates-service.js
  src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js
  src/views/DigitalCertificates/Drawer/index.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  vite.config.js
Labels: enhancement

#1802 [UXE-4942] feat: add Azion Copilot with deepchat to AI Chat component
  azion.config.cjs
  src/modules/azion-ai-chat/azion-ai-chat-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-full-size-block.vue
  src/modules/azion-ai-chat/azion-ai-get-help.vue
  src/modules/azion-ai-chat/contextual-prompts/domains/index.js
  src/modules/azion-ai-chat/contextual-prompts/generic/index.js
  src/modules/azion-ai-chat/contextual-prompts/index.js
  src/modules/azion-ai-chat/index.vue
  src/modules/azion-ai-chat/services/interceptor-service.js
  src/modules/azion-ai-chat/services/make-request-config.js
  src/modules/azion-ai-chat/services/request-interceptor-service.js
  src/modules/azion-ai-chat/tests/make-request-config.test.js
  src/modules/azion-ai-chat/tests/requestInterceptorService.test.js
  src/templates/navbar-block/index.vue
  src/templates/shell-block/index.vue
  src/views/Copilot/CopilotView.vue
  vite.config.js
Labels: enhancement, unit-tests

#1801 [NO-ISSUE] refactoring: grepTags in local-prod-e2e-tests workflow
  .github/workflows/local-prod-e2e-tests.yml
Labels: e2e tests

#1803 [UXE-5193] feat: add functions drawer to edge firewall functions instace form
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: enhancement

#1806 [UXE-5244] feat: update url waf allowed rules
  src/services/waf-rules-services/create-waf-rules-allowed-service.js
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/services/waf-rules-services/delete-waf-rules-allowed-service.js
  src/services/waf-rules-services/edit-waf-rules-allowed-service.js
  src/services/waf-rules-services/list-waf-rules-allowed-service.js
  src/services/waf-rules-services/load-waf-rules-allowed-service.js
  src/services/waf-rules-services/make-waf-rules-allowed-base-url.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
  src/tests/services/waf-rules-services/delete-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/edit-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/load-waf-rules-allowed-sevice.test.js
  src/tests/services/waf-rules-services/make-waf-rules-allowed.test.js
Labels: enhancement, unit-tests

#1810 [UXE-5194] feat: add origin and function instance drawers to rules engine page
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement

#1815 [NO-ISSUE] chore: remove unused origin and rule from azion json for ai
  azion/stage/azion.json
Labels: IAC

#1814 [UXE-4942] feat: add Azion Copilot with deepchat to AI Chat component
  src/modules/azion-ai-chat/azion-ai-chat-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-desktop.vue
  src/modules/azion-ai-chat/azion-ai-chat-full-size-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-mobile.vue
  src/modules/azion-ai-chat/azion-ai-get-help.vue
  src/modules/azion-ai-chat/contextual-prompts/domains/index.js
  src/modules/azion-ai-chat/contextual-prompts/generic/index.js
  src/modules/azion-ai-chat/contextual-prompts/index.js
  src/modules/azion-ai-chat/index.vue
  src/modules/azion-ai-chat/services/interceptor-service.js
  src/modules/azion-ai-chat/services/make-request-config.js
  src/modules/azion-ai-chat/services/request-interceptor-service.js
  src/modules/azion-ai-chat/tests/interceptor-service.test.js
  src/modules/azion-ai-chat/tests/make-request-config.test.js
  src/modules/azion-ai-chat/tests/requestInterceptorService.test.js
  src/templates/navbar-block/index.vue
  src/templates/shell-block/index.vue
  src/views/Copilot/CopilotView.vue
Labels: enhancement

#1817 [UXE-4942] feat: update Copilot tooltip message in AI Chat components
  src/modules/azion-ai-chat/azion-ai-chat-header-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-mobile.vue
Labels: enhancement

#1820 DEPLOY 2024-10-17
  .github/workflows/pre-merge.yml
  azion/stage/azion.json
  src/modules/azion-ai-chat/azion-ai-chat-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-desktop.vue
  src/modules/azion-ai-chat/azion-ai-chat-full-size-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-header-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-mobile.vue
  src/modules/azion-ai-chat/azion-ai-get-help.vue
  src/modules/azion-ai-chat/contextual-prompts/domains/index.js
  src/modules/azion-ai-chat/contextual-prompts/generic/index.js
  src/modules/azion-ai-chat/contextual-prompts/index.js
  src/modules/azion-ai-chat/index.vue
  src/modules/azion-ai-chat/services/interceptor-service.js
  src/modules/azion-ai-chat/services/make-request-config.js
  src/modules/azion-ai-chat/services/request-interceptor-service.js
  src/modules/azion-ai-chat/tests/interceptor-service.test.js
  src/modules/azion-ai-chat/tests/make-request-config.test.js
  src/modules/azion-ai-chat/tests/requestInterceptorService.test.js
  src/templates/navbar-block/index.vue
  src/templates/shell-block/index.vue
  src/views/Copilot/CopilotView.vue
Labels: DEPLOY

#1821 [UXE-5271] feat: add filter challenge solved in breakdown dashboards
  src/helpers/real-time-filters-rules.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/constants/services-operator-in.js
  src/modules/real-time-metrics/filters/extract-filters-and-variables.js
  src/services/real-time-metrics-services/index.js
  src/services/real-time-metrics-services/search-classified-service.js
  src/templates/advanced-filter/component/display/chips-default-display.vue
  src/templates/advanced-filter/component/fields/select-filter.vue
  src/templates/advanced-filter/component/index.js
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/advanced-filter/index.vue
  src/tests/helpers/realt-time-filter-rules.test.js
  src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
Labels: console-measurements

#1813 [UXE-5197] feat: add edge services drawer to edge nodes services form
  src/services/edge-service-services/create-edge-service-services.js
  src/templates/create-drawer-block/index.vue
  src/views/EdgeNode/Drawer/index.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
  src/views/EdgeServices/CreateEdgeServiceDrawer/index.vue
  src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
Labels: enhancement

#1816 [UXE-5299] fix: send header criterias operator as matches instead of is in list
  cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#1824 [UXE-5194] feat: add create cache settings, create origin and create function drawers to rules engine page
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement

#1825 [UXE-4771] feat: implement a feature to display the 5 most used fields
  src/helpers/real-time-filters-rules.js
  src/modules/real-time-events/filters/index.js
  src/modules/real-time-events/filters/relevant-fields.js
  src/tests/helpers/realt-time-filter-rules.test.js
  src/views/RealTimeEvents/TabsView.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
Labels: enhancement

#1835 [UXE-5298] feat: add filters in list format
  src/helpers/real-time-filters-rules.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/services-operator-in.js
  src/services/real-time-metrics-services/index.js
  src/services/real-time-metrics-services/search-action-service.js
  src/services/real-time-metrics-services/search-challenge-solved-service.js
  src/services/real-time-metrics-services/search-classified-service.js
  src/templates/advanced-filter/component/display/chips-default-display.vue
  src/templates/advanced-filter/component/index.js
  src/templates/advanced-filter/dialog-filter.vue
  src/tests/helpers/realt-time-filter-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
Labels: unit-tests, console-measurements

#1833 [UXE-5269] feat: add preview input on the domain page
  .gitignore
  src/services/domains-services/create-domain-service.js
  src/services/domains-services/load-domain-service.js
  src/templates/edit-form-block/index.vue
  src/tests/services/domains-services/create-domain-service.test.js
  src/tests/services/domains-services/load-domain-service.test.js
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: enhancement, do-not-merge

#1836 [UXE-5233] fix: adjust units big numbers in real time events
  src/helpers/real-time-filters-rules.js
  src/services/real-time-metrics-services/search-action-service.js
  src/services/real-time-metrics-services/search-classified-service.js
  src/templates/info-drawer-block/info-labels/big-number.vue
  src/tests/helpers/realt-time-filter-rules.test.js
  src/views/RealTimeEvents/Drawer/httpRequests.vue
  src/views/RealTimeEvents/Drawer/tieredCache.vue
Labels: bug

#1839 [UXE-5427] fix: error when rendering tuning tab
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
Labels: bug, unit-tests

#1841 [UXE-5392] feat: add identity providers list view
  azion.config.cjs
  src/router/index.js
  src/router/routes/identity-providers-routes/index.js
  src/services/identity-providers-services/delete-oidc-identity-provider-service.js
  src/services/identity-providers-services/delete-saml-identity-provider-service.js
  src/services/identity-providers-services/index.js
  src/services/identity-providers-services/list-identity-providers-service.js
  src/services/identity-providers-services/make-identity-providers-base-url.js
  src/services/identity-providers-services/set-identity-provider-status-service.js
  src/templates/list-table-block/index.vue
  src/tests/services/identity-providers-services/delete-oidc-identity-provider-service.test.js
  src/tests/services/identity-providers-services/delete-saml-identity-provider.test.js
  src/tests/services/identity-providers-services/list-identity-providers-service.test.js
  src/tests/services/identity-providers-services/make-identity-providers-base-url.test.js
  src/tests/services/identity-providers-services/set-identity-provider-status-service.test.js
  src/views/IdentityProviders/ListView.vue
  vite.config.js
Labels: good first issue

#1844 [UXE-5417] feat: add SSO Management menu option and route guard to users that don't have federated_auth flag
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/SSOManagementGuard.js
  src/router/hooks/guards/index.js
  src/stores/account.js
  src/templates/profile-block/index.vue
  src/views/IdentityProviders/ListView.vue
Labels: good first issue

#1847 [UXE-5179] chore: adjust text in Social Login field
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: writing

#1846 [UXE-5235] feat: disable viewing sensitive data
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: enhancement

#1852 [NO-ISSUE] fix: reorder guards in beforeEachRoute.js and simplify ssoManagementGuard
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/SSOManagementGuard.js
Labels: bug

#1856 [UXE-5390] fix: create saml redirect url
  src/services/identity-providers-services/create-saml-identity-provider-service.js
  src/tests/services/identity-providers-services/create-saml-identity-provider-service.test.js
Labels: bug

#1855 [UXE-5512] fix: adjust loop requests waf filter
  src/templates/empty-results-block/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#1857 [UXE-5411] fix: more details render empty in real time events
  src/router/hooks/guards/SSOManagementGuard.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/views/RealTimeEvents/Drawer/edgeFunctionsConsole.vue
Labels: bug

#1860 [UXE-5525] feat: added new custom ports to edge application form
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement

#1862 [UXE-4355] fix: invoice details section not load values service and product charges
  src/services/billing-services/list-service-and-products-changes.js
Labels: bug

#1865 [UXE-5515] feat: enable identify event on each page change for appcues flow
  src/router/hooks/afterEachRoute.js
Labels: console-measurements

#1863 [UXE-5283] feat: migrate cache setting v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-cache-settings-services/v4/list-cache-settings-service.js
  src/tests/services/edge-application-cache-settings-services/v4/list-cache-settings-service.test.js
  src/views/EdgeApplicationsCacheSettings/ListView.vue
Labels: enhancement

#1861 [UXE-5284] feat: migrate functions instance to v4
  src/services/edge-application-functions-services/list-edge-application-functions-service.js
  src/services/edge-application-functions-services/v4/index.js
  src/services/edge-application-functions-services/v4/list-edge-functions-service.js
  src/services/edge-application-functions-services/v4/make-edge-function-base-url.js
  src/tests/services/edge-application-functions-services/v4/list-edge-functions-service.test.js
  src/tests/services/edge-application-functions-services/v4/make-edge-application-v4-base-url.test.js
  src/views/EdgeApplicationsFunctions/ListView.vue
Labels: enhancement

#1866 [UXE-5289] feat: migrate functions to v4
  src/router/routes/edge-functions-routes/index.js
  src/services/edge-functions-services/v4/index.js
  src/services/edge-functions-services/v4/list-edge-functions-service.js
  src/services/edge-functions-services/v4/make-edge-functions-base-url.js
  src/tests/services/edge-functions-services/v4/list-edge-functions-service.test.js
  src/tests/services/edge-functions-services/v4/make-edge-functions-base-url.test.js
  src/views/EdgeFunctions/ListView.vue
Labels: enhancement

#1858 [UXE-5296] feat: migrate rules engine to v4 version
  .gitignore
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-rules-engine-services/v4/list-rules-engine-service.js
  src/services/edge-application-services/v4/list-edge-applications-service.js
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/tests/services/edge-application-rules-engine-services/v4/list-rules-engine-service.test.js
  src/tests/services/edge-application-services/v4/list-edge-applications-service.test.js
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement

#1859 [UXE-5470] feat: remove domains from edge firewall and add edge firewall selector in domains form
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/services/domains-services/create-domain-service.js
  src/services/domains-services/edit-domain-service.js
  src/services/domains-services/list-domains-service.js
  src/services/domains-services/load-domain-service.js
  src/services/edge-firewall-services/create-edge-firewall-service.js
  src/services/edge-firewall-services/edit-edge-firewall-service.js
  src/tests/services/domains-services/list-domains-service.test.js
  src/tests/services/edge-firewall-services/create-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/edit-edge-firewall-service.test.js
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeFirewall/CreateView.vue
  src/views/EdgeFirewall/Drawer/index.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: enhancement

#1867 [UXE-5554] feat: added no cache browser option to cache settings
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: enhancement

#1864 [UXE-5544] feat: added marketplace products to sidebar menu with flag
  src/services/sidebar-menus-services/list-sidebar-menus-service.js
  src/services/sidebar-menus-services/menus.js
  src/stores/account.js
  src/templates/sidebar-block/index.vue
  src/tests/services/sidebar-menus-services/list-sidebar-menus-service.test.js
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement, unit-tests
