Repository aziontech/azion-console-kit, pull requests merged in 2024-09, with the labels that each got.

#1666 [NO-ISSUE] fix: remove aicomponent fro navbar and gethelp
  src/templates/navbar-block/index.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
Labels: bug

#1661 feat: add gauge chart
  src/modules/real-time-metrics/MOCK_METRICS_DATA.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: enhancement

#1659 Stacked bar chart
  src/modules/real-time-metrics/MOCK_METRICS_DATA.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/templates/graphs-card-block/components/chart/stacked-bar-chart.vue
  src/templates/graphs-card-block/index.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/views/Playground/PlaygroundView.vue
Labels: enhancement

#1667 DEPLOY 2024.09.02 #2
  azion/production/azion.json
  src/templates/navbar-block/index.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
Labels: DEPLOY

#1662 [UXE-4690] feat: integrate new stacked area chart to metrics
  src/modules/real-time-metrics/MOCK_METRICS_DATA.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/templates/graphs-card-block/components/chart/stacked-area-chart.vue
  src/templates/graphs-card-block/index.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/views/Playground/PlaygroundView.vue
Labels: enhancement

#1672 [UXE-4772] test: change tests to wait for api response instead of arbitrary time
  cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-waf.cy.js
Labels: e2e tests

#1664 [UXE-3308] feat: add accordions to fit rules engine criterias
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: enhancement

#1683 [NO-ISSUE] chore: fix coverage files upload
  .github/workflows/dev-e2e-tests.yml
Labels: e2e tests

#1678 [UXE-1908] feat: added create and edit track events in edge applications device groups
  src/helpers/metrics-playground-opener.js
  src/services/edge-application-device-groups-services/create-device-group-service.js
  src/services/edge-application-device-groups-services/edit-device-group-service.js
  src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
Labels: console-measurements

#1682 [UXE-4708] feat: allow accounts access from a list to console
  azion.config.cjs
  src/router/hooks/redirectToManager.js
  src/services/account-services/index.js
  src/services/account-services/list-client-ids-released-for-console-service.js
  src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
  vite.config.js
Labels: console-measurements

#1685 [UXE-2057] feat: added edit track events in edge applications error responses
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
Labels: console-measurements

#1674 [UXE-1907] [UXE-1910] feat: added clicked to create and edit track events in device groups
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
Labels: console-measurements

#1689 [UXE-2061] feat: added create and edit track events in edge applications cache settings
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
Labels: console-measurements

#1688 [UXE-2060][UXE-2063] feat: added clicked to create and edit track events in edge applications cache settings
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
Labels: console-measurements

#1690 [UXE-4857] fix: update styles for big-number and tab-panel-block components
  src/templates/info-drawer-block/info-labels/big-number.vue
  src/views/RealTimeEvents/Blocks/tab-panel-block.vue
  src/views/RealTimeEvents/Drawer/httpRequests.vue
Labels: bug, theming

#1692 [NO-ISSUE] fix: adjust rules azion config
  azion.config.cjs
Labels: bug

#1695 [UXE-4857] style: update text-sm class in dialog filter
  src/templates/advanced-filter/dialog-filter.vue
  src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
Labels: theming

#1694 [UXE-4768] fix: resolve toast message content in list-table-block
  src/templates/list-table-block/index.vue
Labels: bug

#1696 DEPLOY 2024.09.10
  .github/workflows/deploy-stage.yml
  .github/workflows/dev-e2e-tests.yml
  azion.config.cjs
  azion/stage/azion.json
  cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-waf.cy.js
  src/helpers/metrics-playground-opener.js
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/chart/format-graph.js
  src/modules/real-time-metrics/chart/index.js
  src/modules/real-time-metrics/helpers/countries-code.json
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/plugins/factories/stripe-integration-factory.js
  src/router/hooks/redirectToManager.js
  src/services/account-services/index.js
  src/services/account-services/list-client-ids-released-for-console-service.js
  src/services/edge-application-device-groups-services/create-device-group-service.js
  src/services/edge-application-device-groups-services/edit-device-group-service.js
  src/templates/add-payment-method-block/index.vue
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/graphs-card-block/components/aggregation-info.vue
  src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
  src/templates/graphs-card-block/components/chart/donut-chart.vue
  src/templates/graphs-card-block/components/chart/gauge-chart.vue
  src/templates/graphs-card-block/components/chart/list-chart.vue
  src/templates/graphs-card-block/components/chart/pie-chart.vue
  src/templates/graphs-card-block/components/chart/stacked-area-chart.vue
  src/templates/graphs-card-block/components/chart/stacked-bar-chart.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-legend-block.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/heatmap-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/templates/graphs-card-block/index.vue
  src/templates/info-drawer-block/info-labels/big-number.vue
  src/templates/list-table-block/columns/column-builder.js
  src/templates/list-table-block/index.vue
  src/tests/modules/real-time-metrics/chart/format-c3-graph-props.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/Playground/PlaygroundView.vue
  src/views/Playground/charts/ListChart.vue
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
  src/views/RealTimeEvents/Blocks/tab-panel-block.vue
  src/views/RealTimeEvents/Drawer/httpRequests.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
  vite.config.js
Labels: DEPLOY

#1693 [UXE-2072] feat: add tracker clicked to create and clicked to edit events in rules engine
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: console-measurements

#1705 [NO-ISSUE] fix: remove https origin azion config
  azion.config.cjs
Labels: bug

#1700 [UXE-4888] feat: add WAF Rules edited and failed to edit events to tracker
  src/views/WafRules/EditView.vue
Labels: console-measurements

#1698 [UXE-4884] feat: add clicked to create and clicked to edit event to waf rules
  src/views/WafRules/ListView.vue
Labels: console-measurements

#1699 [UXE-4885] feat: add WAF Rules created and failed to create events to tracker
  src/views/WafRules/CreateView.vue
Labels: console-measurements

#1697 [UXE-2073] feat: add failed to edit and failed to create rules engine events to tracker
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
Labels: console-measurements

#1714 feat: remove icon github e add new icon send to feedback
  src/templates/navbar-block/feedback.vue
Labels: enhancement

#1713 [UXE-4901] fix: reorder rules engine list table block
  src/templates/list-table-block/index.vue
Labels: bug

#1707 [UXE-4869] feat: add clicked to create and clicked to edit network lists events
  src/views/NetworkLists/ListView.vue
Labels: console-measurements

#1709 [UXE-1908] feat: added create and edit track events in edge applications functions instance
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
Labels: console-measurements

#1716 [UXE-4926] feat: add new tracker event to click to create user and edit
  src/views/Users/ListView.vue
Labels: enhancement, console-measurements

#1710 [UXE-4907] feat: support for new charts in metrics
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/chart/format-graph.js
  src/modules/real-time-metrics/constants/chart-rules.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/filters/extract-filters-and-variables.js
  src/modules/real-time-metrics/filters/filter-to-graphql-string.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/convert-report-meta-to-gql.js
  src/modules/real-time-metrics/reports/fill-result-query.js
  src/modules/real-time-metrics/reports/load-report-with-meta.js
  src/templates/graphs-card-block/big-numbers-card.vue
  src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
  src/templates/graphs-card-block/components/chart/gauge-chart.vue
  src/templates/graphs-card-block/components/map/json/countries.json
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/bubbles-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/heatmap-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/templates/graphs-card-block/components/map/utils/features-handler.js
  src/templates/graphs-card-block/index.vue
  src/tests/helpers/events-playground-opener.test.js
  src/tests/modules/real-time-metrics/chart/format-c3-graph-props.test.js
  src/tests/modules/real-time-metrics/constants/chart-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/convert-report-meta-to-gql.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
Labels: enhancement, unit-tests

#1711 [UXE-4873] feat: add network lists edited and failed to edit events to tracker
  src/views/NetworkLists/EditView.vue
Labels: console-measurements

#1718 [NO-ISSUE] chore: update project version to 1.22.0
  package.json
Labels: project version

#1670 [NO-ISSUE] chore: remove unused dependencie
  package.json
  yarn.lock
Labels: dependencies, theming

#1717 feat: add tracker events when it is created and edited user
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
Labels: enhancement, console-measurements

#1715 [NO-ISSUE] fix: reorder rules engine edge firewall and change api contract
  src/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-reorder-base-url.js
  src/services/edge-firewall-rules-engine-services/reorder-edge-firewall-rules-engine-service.js
  src/templates/list-table-block/index.vue
  src/tests/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-base-url.test.js
Labels: bug

#1721 [UXE-4954] feat: update redirectToManager hook to handle console access restrictions
  src/router/hooks/redirectToManager.js
  src/services/account-services/list-client-ids-released-for-console-service.js
  src/stores/account.js
  src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
Labels: enhancement, unit-tests

#1720 [UXE-4928] feat: add failed create user and edit tracker event
  src/services/edge-application-error-responses-services/make-edge-application-error-responses-base-url.js
  src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
  src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
Labels: enhancement, console-measurements

#1728 [UXE-5059] fix: resolve general validation issues in bot manager dashboard
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/chart/format-graph.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/filters/extract-filters-and-variables.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/fill-result-query.js
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/heatmap-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: bug, unit-tests, code-refactor

#1733 [UXE-5056] fix: resolve limit in gql
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: bug

#1725 DEPLOY 2024-09-18
  azion/production/azion.json
  cypress/e2e/edge-application/add-error-response.cy.js
  package.json
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/chart/format-graph.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/filters/extract-filters-and-variables.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/fill-result-query.js
  src/router/hooks/redirectToManager.js
  src/router/index.js
  src/router/routes/compare-with-azion/index.js
  src/services/account-services/list-client-ids-released-for-console-service.js
  src/services/axios/makeCompareWithAzionApi.js
  src/services/axios/makeWebpagetestApi.js
  src/services/compare-with-azion/get-test-from-webpagetest.js
  src/services/compare-with-azion/get-test.js
  src/services/compare-with-azion/index.js
  src/services/compare-with-azion/make-base-url.js
  src/services/compare-with-azion/make-base-webpagetest-url.js
  src/services/compare-with-azion/test-consolidation.js
  src/services/edge-application-error-responses-services/make-edge-application-error-responses-base-url.js
  src/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-reorder-base-url.js
  src/services/edge-firewall-rules-engine-services/reorder-edge-firewall-rules-engine-service.js
  src/stores/account.js
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/heatmap-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/templates/list-table-block/index.vue
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
  src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
  src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-base-url.test.js
  src/views/CompareWithAzion/CompareView.vue
  src/views/CompareWithAzion/blocks/grade-block.vue
  src/views/CompareWithAzion/blocks/journey-block.vue
  src/views/CompareWithAzion/blocks/resume-block.vue
  src/views/CompareWithAzion/blocks/security-block.vue
  src/views/CompareWithAzion/utils/convert-ms-sec.js
  src/views/CompareWithAzion/utils/format-bytes-to-kb.js
  src/views/CompareWithAzion/utils/format-bytes.js
  src/views/CompareWithAzion/utils/result-data-parse.js
  src/views/CompareWithAzion/utils/result-extract.js
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/NetworkLists/CreateView.vue
  src/views/PersonalTokens/CreateView.vue
  src/views/PersonalTokens/ListView.vue
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
  vite.config.js
  yarn.lock
Labels: DEPLOY

#1730 [UXE-4912] feat: add WAF Allowed rules events to tracker
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: console-measurements

#1735 [UXE-4767] fix: console re purge toast shown without confirm click
  src/views/RealTimePurge/Dialog/index.vue
  src/views/RealTimePurge/ListView.vue
Labels: bug

#1736 [NO-ISSUE] refactor: general changes in bot manager reports
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/load-report-variation.js
  src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: unit-tests, code-refactor

#1740 chore: update project version to 1.22.2
  package.json
Labels: project version

#1743 DEPLOY 2024.09.24
  package.json
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/load-report-variation.js
  src/services/real-time-purge/make-real-time-purge-service.js
  src/templates/graphs-card-block/components/chart/big-numbers-chart.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/tests/services/real-time-purge/make-real-time-purge.test.js
  src/views/AccountSettings/AccountSettingsView.vue
  src/views/RealTimePurge/Dialog/index.vue
  src/views/RealTimePurge/ListView.vue
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: DEPLOY

#1727 [UXE-4967] feat: added allow rules track events in waf tuning
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/analytics/trackers/ProductTracker.js
  src/plugins/analytics/trackers/WafRulesTracker.js
  src/plugins/analytics/trackers/index.js
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/views/WafRules/Dialog/index.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: console-measurements

#1741 [EDU-5386] chore: adjusting description bot graph
  src/modules/real-time-metrics/constants/reports-texts.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: writing

#1747 [EDU-5386] chore: adjust Bot graphs names
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: writing

#1748 [UXE-5021] feat: add edited and failed to edit your settings events to tracker
  src/views/YourSettings/EditView.vue
Labels: console-measurements

#1746 [UXE-2072] feat: add rules engine created and failed to created events and fixed event name
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
Labels: console-measurements

#1739 [UXE-5025] feat: add tracking events to teams permissions
  src/templates/edit-form-block/index.vue
  src/views/TeamsPermissions/CreateView.vue
  src/views/TeamsPermissions/EditView.vue
  src/views/TeamsPermissions/ListView.vue
Labels: enhancement, console-measurements

#1738 [UXE-4804] fix: error when using advanced filters
  src/helpers/convert-gql.js
  src/tests/helpers/convert-gql.test.js
Labels: bug

#1752 [UXE-5123] fix: remove unused API endpoint for allowed accounts
  vite.config.js
Labels: bug

#1750 [UXE-4813] feat: persist number of records per page on list screens
  src/stores/table-definitions.js
  src/templates/list-table-block/index.vue
Labels: console-measurements

#1754 chore: update project version to 1.22.3
  package.json
Labels: project version

#1755 DEPLOY 2024.09.25
  azion.config.cjs
  azion/production/azion.json
  azion/stage/azion.json
  package.json
  src/helpers/convert-gql.js
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/analytics/trackers/ProductTracker.js
  src/plugins/analytics/trackers/WafRulesTracker.js
  src/plugins/analytics/trackers/index.js
  src/router/hooks/redirectToManager.js
  src/services/account-services/index.js
  src/services/account-services/list-client-ids-released-for-console-service.js
  src/stores/account.js
  src/stores/table-definitions.js
  src/templates/edit-form-block/index.vue
  src/templates/list-table-block/index.vue
  src/tests/helpers/convert-gql.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/tests/services/account-services/list-client-ids-released-for-console-service.test.js
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/TeamsPermissions/CreateView.vue
  src/views/TeamsPermissions/EditView.vue
  src/views/TeamsPermissions/ListView.vue
  src/views/WafRules/Dialog/index.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/ListWafRulesTuning.vue
  src/views/YourSettings/EditView.vue
  vite.config.js
Labels: DEPLOY

#1757 [UXE-5079] feat: retry counter and button to Compare With Azion
  src/services/compare-with-azion/get-test-from-webpagetest.js
  src/services/compare-with-azion/get-test.js
  src/views/CompareWithAzion/CompareView.vue
  src/views/CompareWithAzion/blocks/data-block.vue
  src/views/CompareWithAzion/blocks/grade-block.vue
  src/views/CompareWithAzion/blocks/retry-message.vue
  src/views/CompareWithAzion/blocks/security-block.vue
  src/views/CompareWithAzion/utils/convert-ms-sec.js
  src/views/CompareWithAzion/utils/result-data-parse.js
Labels: enhancement, code-refactor

#1758 [UXE-5064] feat: implements events in real time metrics
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/analytics/trackers/RealTimeMetricsTracker.js
  src/plugins/analytics/trackers/index.js
  src/templates/graphs-card-block/components/more-options-menu.vue
  src/templates/graphs-card-block/index.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Labels: enhancement, console-measurements

#1761 chore: update project version from 1.22.3 to 1.22.4
  package.json
Labels: project version

#1749 [UXE-5100] feat: add breakdown dashboard in bot manager advanced page
  src/assets/c3.scss
  src/helpers/real-time-filters-rules.js
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/constants/services-operator-in.js
  src/modules/real-time-metrics/index.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/convert-report-meta-to-gql.js
  src/services/real-time-metrics-services/index.js
  src/services/real-time-metrics-services/search-bot-category-service.js
  src/templates/advanced-filter/component/fields/multiselect-filter.vue
  src/templates/advanced-filter/component/index.js
  src/templates/graphs-card-block/components/map/constants/color-scheme.js
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-legend-block.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-block.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/templates/graphs-card-block/components/map/utils/features-handler.js
  src/templates/graphs-card-block/index.vue
  src/tests/helpers/realt-time-filter-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/tests/services/real-time-metrics-services/search-bot-category-service.test.js
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
  tailwind.config.js
Labels: enhancement, unit-tests, code-refactor

#1759 [NO-ISSUE] feat: added clicked to create and edit track events in functions instances
  src/views/EdgeApplicationsFunctions/ListView.vue
Labels: console-measurements

#1766 [NO-ISSUE] fix: improvement parse contract for service billing
  src/services/billing-services/list-payment-history-service.js
  src/tests/services/billing-services/list-payment-history-service.test.js
Labels: bug

#1760 DEPLOY 2024.09.27
  package.json
  src/assets/c3.scss
  src/helpers/real-time-filters-rules.js
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/constants/services-operator-in.js
  src/modules/real-time-metrics/index.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/convert-report-meta-to-gql.js
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/analytics/trackers/RealTimeMetricsTracker.js
  src/plugins/analytics/trackers/index.js
  src/services/billing-services/list-payment-history-service.js
  src/services/compare-with-azion/get-test-from-webpagetest.js
  src/services/compare-with-azion/get-test.js
  src/services/real-time-metrics-services/index.js
  src/services/real-time-metrics-services/search-bot-category-service.js
  src/templates/advanced-filter/component/fields/multiselect-filter.vue
  src/templates/advanced-filter/component/index.js
  src/templates/graphs-card-block/components/map/constants/color-scheme.js
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-legend-block.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-block.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/templates/graphs-card-block/components/map/utils/features-handler.js
  src/templates/graphs-card-block/components/more-options-menu.vue
  src/templates/graphs-card-block/index.vue
  src/tests/helpers/realt-time-filter-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/tests/services/billing-services/list-payment-history-service.test.js
  src/tests/services/real-time-metrics-services/search-bot-category-service.test.js
  src/views/CompareWithAzion/CompareView.vue
  src/views/CompareWithAzion/blocks/data-block.vue
  src/views/CompareWithAzion/blocks/grade-block.vue
  src/views/CompareWithAzion/blocks/retry-message.vue
  src/views/CompareWithAzion/blocks/security-block.vue
  src/views/CompareWithAzion/utils/convert-ms-sec.js
  src/views/CompareWithAzion/utils/result-data-parse.js
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
  tailwind.config.js
Labels: DEPLOY

#1767 [UXE-5130] feat: add variable tracker event
  src/plugins/analytics/trackers/RealTimeMetricsTracker.js
  src/plugins/analytics/trackers/index.js
  src/services/real-time-metrics-services/index.js
  src/views/CompareWithAzion/blocks/retry-message.vue
  src/views/Variables/CreateView.vue
  src/views/Variables/EditView.vue
  src/views/Variables/ListView.vue
Labels: enhancement, console-measurements

#1765 [NO-ISSUE] refactor: adjustments in code readability in rtmetrics
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/templates/graphs-card-block/components/map/constants/color-scheme.js
  src/templates/graphs-card-block/components/map/utils/features-handler.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: code-refactor

#1769 DEPLOY 2024.09.30
  package.json
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/plugins/analytics/trackers/RealTimeMetricsTracker.js
  src/plugins/analytics/trackers/index.js
  src/services/edge-node-services/edit-edge-node-service.js
  src/services/edge-node-services/load-edge-node-service.js
  src/services/real-time-metrics-services/index.js
  src/templates/form-fields-inputs/fieldSwitchBlock.vue
  src/templates/graphs-card-block/components/map/constants/color-scheme.js
  src/templates/graphs-card-block/components/map/utils/features-handler.js
  src/templates/selector-block/index.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  src/tests/services/edge-node-services/edit-edge-node-services.test.js
  src/tests/services/edge-node-services/load-edge-node-service.test.js
  src/views/CompareWithAzion/blocks/retry-message.vue
  src/views/EdgeNode/EditView.vue
  src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
  src/views/Variables/CreateView.vue
  src/views/Variables/EditView.vue
  src/views/Variables/ListView.vue
Labels: DEPLOY
