Repository aziontech/azion-console-kit, pull requests merged in 2024-02, with the labels that each got.

#653 [NO-ISSUE] refactor: readding data streaming and edge pulse texts
  src/views/DataStreaming/CreateView.vue
  src/views/DataStreaming/Dialog/SamplingDialog.vue
  src/views/DataStreaming/EditView.vue
  src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
  src/views/DataStreaming/ListView.vue
  src/views/EdgePulse/FormFields/FormFieldsTag.vue
Labels: writing

#654 [UX-1711] feat: implement more options menu for report
  src/stores/help-center.js
  src/templates/graphs-card-block/index.vue
  src/views/Metrics/blocks/dashboard-panel-block.vue
Labels: enhancement, WIP, code-refactor

#662 [NO-ISSUE] fix: remove item to edit in edit drawer block and refactor rules engine
  src/templates/edit-drawer-block/index.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: code-refactor

#664 [NO-ISSUE] style: include pt for remove shadow and padding
  src/templates/list-table-block/no-header.vue
  src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
  src/templates/switch-account-block/index.vue
Labels: theming

#687 [EDU-2964] chore: review waf rules views
  src/router/routes/waf-rules-routes/index.js
  src/views/WafRules/CreateView.vue
  src/views/WafRules/Drawer/index.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
  src/views/WafRules/ListView.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: writing

#661 [UXE-1711] feat: implement more options menu for report
  src/helpers/metrics-playground-opener.js
  src/router/routes/metrics-routes/index.js
  src/services/metrics-services/constants/reports.js
  src/stores/metrics-store/constants/date-time-interval.js
  src/stores/metrics.js
  src/templates/graphs-card-block/components/chart-owner.vue
  src/templates/graphs-card-block/components/chart/bar-chart/bar-chart.vue
  src/templates/graphs-card-block/components/chart/line-chart/line-chart.vue
  src/templates/graphs-card-block/components/chart/spline-chart/spline-chart.vue
  src/templates/graphs-card-block/components/more-options-menu.vue
  src/templates/graphs-card-block/constants/chart-data.js
  src/templates/graphs-card-block/constants/color-patterns.js
  src/templates/graphs-card-block/helpers/c3-charts.js
  src/templates/graphs-card-block/index.vue
  src/tests/helpers/metrics-playground-opener.test.js
  src/views/Metrics/MetricsView.vue
  src/views/Metrics/blocks/dashboard-panel-block.vue
Labels: enhancement, unit-tests, code-refactor

#692 [EDU-2963] chore: review edge firewall uxw
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeFirewall/CreateView.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: writing

#696 [UXE-1697] fix: added criteria and conditional limit
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#701 [UXE-1759] fix: remove unnecessary email reset before submit
  src/views/YourSettings/EditView.vue
Labels: bug

#698 [UXE-27512] fix: L2 cache module at edge application
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-application-services/index.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: bug

#697 [UXE-1619] fix: clicking the logo with the same router should reload the page
  src/templates/navbar-block/index.vue
Labels: bug

#695 [UXE-1721] fix: disable csr field in digital certificate edit page
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: bug

#702 [NO-ISSUE ] fix: fix input name it is not working
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
Labels: bug

#705 DEPLOY 2024.02.08
  package.json
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-application-services/index.js
  src/templates/list-table-block/columns/expand-text-column.vue
  src/templates/navbar-block/index.vue
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeFirewall/CreateView.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/YourSettings/EditView.vue
Labels: DEPLOY

#707 [ENG-29254] feat: integrate feedback tags
  src/services/metrics-services/constants/dashboards.js
  src/services/metrics-services/constants/reports.js
  src/stores/metrics-store/actions/index.js
  src/stores/metrics-store/actions/load-report-variation.js
  src/stores/metrics-store/actions/load-report-with-meta.js
  src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
  src/stores/metrics.js
  src/templates/graphs-card-block/components/aggregation-info.vue
  src/templates/graphs-card-block/index.vue
Labels: enhancement, code-refactor

#713 [NO-ISSUE] refactor: [metrics] change card columns from 4 to 6
  src/services/metrics-services/constants/reports.js
Labels: code-refactor

#712 [UXE-1592] fix: dynamically delete entered codes
  src/templates/mfa-authenticate-block/index.vue
Labels: bug

#715 [UXE-1679] fix: multi select in edge application https and http ports
  src/services/edge-application-services/create-edge-application-service.js
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-application-services/load-edge-application-service.js
  src/tests/services/edge-application-services/create-edge-application-service.test.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: bug

#716 [UXE-1790] feat: change copyright text
  src/templates/footer-block/index.vue
  src/templates/mfa-authenticate-block/index.vue
  src/tests/services/edge-application-services/create-edge-application-service.test.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement

#718 [UXE-1791] feat: Open Billing & Subscriptions in RTM
  src/templates/profile-block/index.vue
Labels: bug

#720 [NO-ISSUE] fix: MFA code in setup page
  src/templates/mfa-setup-block/index.vue
Labels: bug

#725 DEPLOY 2024.02.12
  package.json
  src/services/edge-application-services/create-edge-application-service.js
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-application-services/load-edge-application-service.js
  src/services/metrics-services/constants/reports.js
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
  src/templates/footer-block/index.vue
  src/templates/mfa-authenticate-block/index.vue
  src/templates/mfa-setup-block/index.vue
  src/templates/profile-block/index.vue
  src/tests/services/edge-application-services/create-edge-application-service.test.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/Home/HomeView.vue
  src/views/WafRules/CreateView.vue
Labels: DEPLOY

#714 [ENG-29050] feat: handle password reset
  src/router/routes/password-routes/index.js
  src/services/auth-services/index.js
  src/services/auth-services/make-password-setting-service-base-url.js
  src/services/auth-services/password-setting-service.js
  src/templates/sign-in-block/reset-password.vue
  src/tests/services/auth-services/password-setting-service.test.js
  src/views/NewPassword/NewPasswordView.vue
Labels: enhancement, unit-tests

#730 [UXE-1807] fix: remove action delete to list tables that dont have delete service
  src/templates/list-table-block/no-header.vue
Labels: bug

#721 [UXE-1800] feat: add feedback fish to menu
  package.json
  src/templates/navbar-block/feedback-fish.vue
  src/templates/navbar-block/index.vue
  yarn.lock
Labels: experimental-changes

#734 [UXE-1799] fix: [edge firewall] update criteria list validation and values in drawer dropdown
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/Home/HomeView.vue
Labels: bug

#736 DEPLOY 2024.02.16
  package.json
  src/router/routes/password-routes/index.js
  src/services/auth-services/index.js
  src/services/auth-services/make-password-setting-service-base-url.js
  src/services/auth-services/password-setting-service.js
  src/templates/dialog-unsaved-block/index.vue
  src/templates/edit-form-block/index.vue
  src/templates/form-fields-inputs/fieldSwitch.vue
  src/templates/list-table-block/no-header.vue
  src/templates/navbar-block/feedback-fish.vue
  src/templates/navbar-block/index.vue
  src/templates/profile-block/index.vue
  src/templates/sign-in-block/reset-password.vue
  src/tests/services/auth-services/password-setting-service.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeFirewall/TabsView.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeNode/TabsView.vue
  src/views/EdgeServices/TabsView.vue
  src/views/Home/HomeView.vue
  src/views/NewPassword/NewPasswordView.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
  src/views/WafRules/TabsView.vue
  yarn.lock
Labels: DEPLOY

#739 [NO-ISSUE] refactor: remove whitespace before period in disclaimer text
  src/views/Home/HomeView.vue
Labels: code-refactor

#741 [UXE-1798] fix: [global] apply overscroll-behavior-contain to all elements
  src/assets/main.css
Labels: bug

#743 [UXE-1806] fix: inappropriate checkbox behavior
  src/templates/list-table-block/no-header.vue
Labels: bug

#745 [UXE-1801] chore: functions instances firewall description
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: writing

#746 [UXE-1903] feat: redirect users from console to manager
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/redirectToManager.js
  src/router/index.js
  src/services/contract-services/index.js
  src/services/contract-services/load-contract-service-plan.js
  src/services/contract-services/make-contract-base-url.js
  src/stores/account.js
  src/templates/dialog-unsaved-block/index.vue
  src/templates/edit-form-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/tests/services/contract-services/load-contract-service-plan.test.js
  src/tests/services/contract-services/make-contract-base-url.test.js
  src/views/EdgeNode/TabsView.vue
  vite.config.js
Labels: enhancement

#748 [UXE-1903] fix: remove redirect guard with invalid service plan calculation
  src/router/index.js
  src/templates/list-table-block/no-header.vue
  vite.config.js
Labels: bug

#749 [UXE-1798] fix: [dropdowns] add appendTo=self to fix list being scrolled with page
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/footer-block/index.vue
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/profile-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/templates/switch-account-block/index.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
  src/views/Home/FormFields/FormFieldsHome.vue
  src/views/IntelligentDNS/FormFields/FormFieldsRecords.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
  src/views/Metrics/blocks/interval-filter-block.vue
  src/views/Metrics/blocks/tabs-page-block.vue
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
  src/views/WafRules/ListWafRulesTuning.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: bug

#751 [UXE-1979] fix: [profile-menu] update theme value in menu on change
  src/templates/profile-block/index.vue
Labels: bug

#753 [UXE-1903] feat: redirect users from console to manager by kind or support plan
  src/router/hooks/redirectToManager.js
  src/router/index.js
  src/services/contract-services/make-contract-base-url.js
  src/tests/services/contract-services/load-contract-service-plan.test.js
  src/tests/services/contract-services/make-contract-base-url.test.js
  vite.config.js
Labels: enhancement

#752 [UXE-1895] fix: add page_size 2000 in domains
  src/services/data-streaming-services/list-data-streaming-domains-service.js
  src/services/data-streaming-services/load-data-streaming-service.js
Labels: bug

#754 [NO-ISSUE] refactor: adjust get env helper method
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  src/helpers/get-environment-from-url.js
  src/helpers/get-environment.js
  src/helpers/get-static-urls-by-environment.js
  src/helpers/index.js
  src/helpers/metrics-playground-opener.js
  src/router/hooks/redirectToManager.js
  src/services/help-center-services/get-help-center-documentation-service.js
  src/services/help-center-services/make-documentation-base-url.js
  src/templates/help-center-block/index.vue
  src/templates/profile-block/index.vue
  src/tests/helpers/get-environment-from-url.test.js
  src/tests/helpers/get-environment.test.js
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/tests/services/help-center-services/make-documentation-base-url.test.js
  src/views/Home/HomeView.vue
Labels: github-actions, code-refactor

#755 [NO-ISSUE] feat: open menu sidebar in new tab with keyboard key
  src/templates/sidebar-block/index.vue
Labels: bug

#747 [UXE-1696] fix: add modal unsaved to drawer
  src/templates/create-drawer-block/index.vue
  src/templates/dialog-unsaved-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/views/EdgeApplications/TabsView.vue
Labels: bug

#762 [NO-ISSUE] fix: avoid redirects to azion access
  src/router/hooks/redirectToManager.js
Labels: bug

#763 [ENG-27927] refactor: add field in drawer httprequest in events
  src/services/real-time-events-service/http-request/load-http-request.js
Labels: code-refactor

#761 [UXE-1842] fix: adjusted the IDNS tab to support the unsaved modal
  src/helpers/generate-timestamp.js
  src/templates/edit-form-block/index.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeFirewall/TabsView.vue
  src/views/EdgeNode/TabsView.vue
  src/views/EdgeServices/TabsView.vue
  src/views/IntelligentDNS/EditView.vue
  src/views/WafRules/TabsView.vue
Labels: bug

#765 [UXE-1919] fix: template selector with start state empty
  src/helpers/generate-timestamp.js
  src/services/network-lists-services/list-network-list-service.js
  src/templates/create-drawer-block/index.vue
  src/templates/create-modal-block/index.vue
  src/templates/dialog-unsaved-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/tests/services/marketplace-services/list-solutions-service.test.js
  src/tests/services/network-lists-services/list-network-list-service.test.js
  src/views/IntelligentDNS/EditView.vue
Labels: bug

#750 [EDU-4162] chore: bug hunting build uxw adjustments
  src/services/edge-application-origins-services/create-origin-service.js
  src/templates/dialog-unsaved-block/index.vue
  src/tests/services/edge-application-origins-services/create-origin-service.test.js
  src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
  src/views/Credentials/FormFields/FormFieldsEditCredentials.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
Labels: writing

#771 [UXE-1817] fix: add expand-column in cnames
  src/services/domains-services/list-domains-service.js
  src/tests/services/domains-services/list-domains-service.test.js
  src/views/Domains/ListView.vue
Labels: bug

#770 [UXE-1697] fix: adjusting maximum criteria and behaviors for rules engine
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#774 [UXE-2033] fix: filter date remains with the same value when switching tabs
  src/views/RealTimeEvents/TabsView.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStreaming/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsIntelligentDNS/ListView.vue
  src/views/RealTimeEventsL2Cache/ListView.vue
Labels: bug

#767 [UXE-2015] feat: implement helpcenter in metrics
  src/router/hooks/beforeEachRoute.js
  src/services/help-center-services/get-help-center-documentation-service.js
  src/services/metrics-services/constants/dashboards-texts.js
  src/services/metrics-services/constants/help-center-urls.js
  src/services/metrics-services/constants/reports.js
  src/stores/help-center.js
  src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
  src/templates/graphs-card-block/components/more-options-menu.vue
  src/templates/graphs-card-block/helpers/c3-charts.js
  src/templates/graphs-card-block/index.vue
  src/templates/help-center-block/index.vue
  src/templates/profile-block/index.vue
  src/tests/services/help-center-services/get-help-center-documentation-service.test.js
Labels: bug, enhancement, code-refactor

#783 [NO-ISSUE] fix: [slide-in] adjust content height
  src/templates/help-center-block/index.vue
Labels: bug

#780 [UXE-2150] fix: capitalize activity history type first letter
  src/services/real-time-events-service/activity-history/load-activity-history.js
Labels: bug

#784 [UXE-2148] fix: add expand-text component to title header
  src/views/RealTimeEventsActivityHistory/ListView.vue
Labels: bug, code-refactor

#785 [UXE-2035] fix: adjusting component sizes and alignments
  src/services/real-time-events-service/intelligent-dns/list-intelligent-dns.js
  src/templates/info-drawer-block/info-labels/big-number.vue
  src/views/RealTimeEventsActivityHistory/Drawer/index.vue
  src/views/RealTimeEventsDataStreaming/Drawer/index.vue
  src/views/RealTimeEventsEdgeFunctions/Drawer/index.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/Drawer/index.vue
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
  src/views/RealTimeEventsIntelligentDNS/Drawer/index.vue
  src/views/RealTimeEventsL2Cache/Drawer/index.vue
Labels: bug

#788 [UXE-1880] feat: add tracking client to project
  package.json
  src/App.vue
  src/helpers/get-environment.js
  src/main.js
  src/plugins/AnalyticsTrackerAdapterPlugin.js
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/plugins/factories/analytics-tracking-factory.js
  src/router/hooks/afterEachRoute.js
  src/router/index.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/tests/plugins/factories/analytics-tracking-factory.test.js
  vitest.config.js
  yarn.lock
Labels: enhancement, unit-tests

#791 [EDU-3643] refactor: update metrics reports texts
  src/services/metrics-services/constants/dashboards-texts.js
Labels: writing

#795 [UXE-1882] feat: add track event Click To Create
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/templates/info-drawer-block/info-section/index.vue
  src/templates/list-table-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplications/ListView.vue
Labels: enhancement, unit-tests, console-measurements

#793 [UXE-2158] refactor: replace RTE datetime filter options
  src/views/Metrics/blocks/interval-filter-block.vue
  src/views/RealTimeEvents/blocks/constants/date-time-interval.js
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
Labels: code-refactor

#797 [NO-ISSUE] chore: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#800 [UXE-2102] feat: user signed in
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/sign-in-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests, console-measurements

#801 [UXE-2103] feat: add User Failed to Sign In
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/sign-in-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests, console-measurements

#802 [UXE-1883] feat: create event edge application created
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement, unit-tests, console-measurements

#786 [UXE-2040] fix: changed big number weight
  src/templates/info-drawer-block/info-labels/big-number.vue
Labels: bug
