Repository aziontech/azion-console-kit, pull requests merged in 2024-05, with the labels that each got.

#1094 [UXE-2904] fix: change import from github page breadcumb hyperlink
  src/router/routes/import-github-routes/index.js
Labels: bug

#1098 [NO-ISSUE] fix: remove wrong text in form fields records
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
Labels: bug

#1097 [UXE-2925] refactor: github connection popup changed to fullscreen
  src/templates/template-engine-block/oauth-github.vue
Labels: code-refactor

#1104 [UXE-1600] chore: add helper for origin type
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: writing

#1093 [UXE-1874] fix: change more details box header in template page to fit content correctly
  src/assets/themes/scss/themes/azion-dark/extended-components/_dialog.scss
  src/assets/themes/scss/themes/azion-dark/extended-components/_sidebar.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_dialog.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_sidebar.scss
Labels: bug

#1096 [UXE-2818] fix: match zone is path does not work
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#1106 [UXE-2498] feat: add message purge is execution queue
  src/services/real-time-purge/create-real-time-purge-service.js
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/views/RealTimePurge/ListView.vue
Labels: enhancement, categorized

#1108 [UXE-3096] fix: adding ordering of templates by name
  src/services/marketplace-services/list-solutions-service.js
  src/tests/services/marketplace-services/list-solutions-service.test.js
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: bug

#1109 [UXE-3122] fix: remove unnecessary toast from import from Github to deploy view and add variable key validation
  src/templates/create-form-block/index.vue
  src/templates/form-fields-inputs/fieldText.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: bug

#1113 [UXE-3131] feat: added default ordering by name in list vcs repositories service
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/tests/services/version-control-system-integration-services/list-repositories-service.test.js
Labels: enhancement, unit-tests

#1114 [UXE-3133] Theming: Improve text style, spacing and responsive behavior for inline messages
  src/assets/themes/scss/themes/azion-dark/extended-components/_inlinemessage.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_inlinemessage.scss
  src/views/Playground/PlaygroundView.vue
Labels: theming

#1115 [UXE-3112] feat: updating name and label of the edge application name
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: enhancement

#1116 [ENG-2765] fix: return to list on EdgeApplicationErrorResponses cancel
  src/views/EdgeApplicationsErrorResponses/EditView.vue
Labels: bug

#1119 [UXE-2937] fix: allow more than 30 scopes
  src/services/version-control-system-integration-services/list-integrations-service.js
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
Labels: bug

#1112 [UXE-2930] refactor: change timer to show time in minutes and seconds
  src/views/CreateNew/DeployView.vue
Labels: code-refactor

#1121 [NO-ISSUE] chore: upgrade project version from 1.15.0 to 1.15.1
  package.json
Labels: DEPLOY

#1123 test: remove test not used
  src/tests/helpers/generate-formatted-timestamp.test.js
  src/views/CreateNew/DeployView.vue
Labels: unit-tests

#1122 DEPLOY 2024.05.07
  package.json
  src/assets/themes/scss/themes/azion-dark/extended-components/_dialog.scss
  src/assets/themes/scss/themes/azion-dark/extended-components/_inlinemessage.scss
  src/assets/themes/scss/themes/azion-dark/extended-components/_sidebar.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_dialog.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_inlinemessage.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_sidebar.scss
  src/helpers/generate-formatted-timestamp.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/marketplace-services/list-solutions-service.js
  src/services/network-lists-services/list-network-list-service.js
  src/services/real-time-purge/create-real-time-purge-service.js
  src/services/version-control-system-integration-services/list-integrations-service.js
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/templates/create-form-block/index.vue
  src/templates/form-fields-inputs/fieldText.vue
  src/templates/template-engine-block/oauth-github.vue
  src/tests/helpers/generate-formatted-timestamp.test.js
  src/tests/services/marketplace-services/list-solutions-service.test.js
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
  src/tests/services/version-control-system-integration-services/list-repositories-service.test.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
  src/views/CreateNew/DeployView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
  src/views/EdgeFirewall/TabsView.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
  src/views/Playground/PlaygroundView.vue
  src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/RealTimePurge/ListView.vue
  src/views/Variables/FormFields/FormFieldsVariables.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: DEPLOY

#1125 [UXE-2935] refactor: added a check to ensure polling is performed one at a time
  src/templates/script-runner-block/index.vue
  src/tests/services/script-runner-services/get-script-runner-logs-service.test.js
  src/views/CreateNew/DeployView.vue
Labels: enhancement, code-refactor

#1124 [UXE-3114] fix: remove unnecessary variables of import from github instantiate
  src/views/ImportGitHub/ImportGithubView.vue
Labels: bug

#1128 [UXE-3135] fix: ensure to only catch once the fail creation of an variable
  src/views/ImportGitHub/ImportGithubView.vue
Labels: bug

#1132 chore: upgrade project version from 1.15.1 to 1.15.2
  package.json
Labels: project version

#1133 DEPLOY 2024.05.08
  package.json
  src/services/script-runner-service/get-script-runner-logs-service.js
  src/templates/script-runner-block/index.vue
  src/tests/services/script-runner-services/get-script-runner-logs-service.test.js
  src/views/CreateNew/DeployView.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: DEPLOY

#1137 [UXE-3139] feat: add project name to deploy
  src/stores/deploy.js
  src/templates/template-engine-block/index.vue
  src/views/CreateNew/DeployView.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: enhancement

#1111 [UXE-2081] feat: add event tracker click to edit edge firewall
  src/views/EdgeFirewall/ListView.vue
Labels: console-measurements

#1136 [UXE-2931] fix: update resend email endpoint
  src/services/signup-services/make-resend-email-base-url.js
  src/tests/services/signup-services/resend-email-service.test.js
Labels: bug, unit-tests

#1139 [UXE-2081] feat: add event tracker in edit edge firewall
  src/views/EdgeFirewall/EditView.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
Labels: console-measurements

#1135 [UXE-2881] fix: escape validation in template engine empty not requied fields
  src/templates/template-engine-block/index.vue
Labels: bug

#1138 [NO-ISSUE] chore: change fail message text for deploy at DeployView
  src/views/CreateNew/DeployView.vue
Labels: enhancement

#1126 [UXE-2877] refactor: replace old selectors with new ones in additional data
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/form-fields-inputs/fieldRadioBlock.vue
  src/templates/form-fields-inputs/fieldSwitchBlock.vue
  src/templates/selector-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
Labels: code-refactor

#1140 [UXE-2083] feat: add event tracker failed edit edge firewall
  src/templates/template-engine-block/index.vue
  src/views/EdgeFirewall/EditView.vue
Labels: console-measurements

#1141 [UXE-3179] refactor: change deploy timer to persist when the page is reloaded
  src/stores/deploy.js
  src/templates/template-engine-block/index.vue
  src/views/CreateNew/DeployView.vue
Labels: code-refactor

#1142 [UXE-2291] feat: update name save button for deploy in the template and import j…
  src/templates/action-bar-block/action-bar-with-teleport.vue
  src/templates/template-engine-block/index.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: enhancement

#1144 [UXE-2891] fix: request time filter with between operator breaks the query
  src/modules/real-time-metrics/filters/extract-filters-and-variables.js
Labels: bug

#1145 [UXE-2009] refactore: Adjust the columns of the realtime events view tables
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
  src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
Labels: do-not-merge, code-refactor

#1150 [UXE-2891] fix: request time filter with between operator breaks the query
  src/modules/real-time-metrics/filters/extract-filters-and-variables.js
  src/views/CreateNew/DeployView.vue
Labels: bug

#1151 chore: updated version package json from 1.15.2 to 1.15.3
  package.json
Labels: project version

#1148 [UXE-3234] refactor: data stream selectors switch and radio changed to new blocks
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: code-refactor

#1147 [UXE-2084] feat: add clicked to create and clicked to edit functions event
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/views/EdgeFunctions/ListView.vue
Labels: do-not-merge, console-measurements

#1153 [UXE-3251] refactor: domains selectors radio and switch changed to new blocks
  src/services/domains-services/load-domain-service.js
  src/tests/services/domains-services/load-domain-service.test.js
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: bug, code-refactor

#1149 [UXE-3250] refactor: digital certificate selectors radio changed to new blocks
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
Labels: code-refactor

#1155 [UXE-2342] feat: pending action reappears
  src/services/real-time-purge/create-real-time-purge-service.js
  src/services/real-time-purge/list-real-time-purge-service.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
  src/views/EdgeFunctions/ListView.vue
  src/views/RealTimePurge/Dialog/index.vue
Labels: enhancement

#1146 [UXE-1744] refactor: remove real time metrics dependency from store
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/helpers/getters.js
  src/modules/real-time-metrics/index.js
  src/modules/real-time-metrics/reports/index.js
  src/modules/real-time-metrics/reports/load-report-variation.js
  src/modules/real-time-metrics/reports/load-report-with-meta.js
  src/modules/real-time-metrics/reports/load-reports-data-by-selected-dashboard.js
  src/modules/real-time-metrics/reports/resolve-reports.js
  src/stores/metrics.js
  src/templates/advanced-filter/component/fields/multiselect-filter.vue
  src/templates/advanced-filter/index.vue
  src/templates/graphs-card-block/index.vue
  src/tests/modules/real-time-metrics/chart/chart-fixtures.js
  src/tests/modules/real-time-metrics/chart/format-c3-graph-props.test.js
  src/tests/modules/real-time-metrics/constants/chart-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/filter-rules.test.js
  src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/constants/time-interval.test.js
  src/tests/modules/real-time-metrics/helpers/getters-filter.test.js
  src/tests/modules/real-time-metrics/helpers/getters-group.test.js
  src/tests/modules/real-time-metrics/helpers/getters-report.test.js
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
  src/views/RealTimeMetrics/blocks/dashboard-panel-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
  src/views/RealTimeMetrics/blocks/tabs-page-block.vue
  tailwind.config.js
Labels: bug, unit-tests, code-refactor

#1129 [UXE-3188] refactor: change description for settings and add tip to name field
  src/helpers/azion-documentation-catalog.js
  src/tests/helpers/azion-documentation-catalog-product-guide.test.js
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
Labels: unit-tests, code-refactor

#1156 [UXE-2130] feat: add created function tracker
  src/templates/create-modal-block/index.vue
  src/views/EdgeFunctions/CreateView.vue
  src/views/EdgeFunctions/ListView.vue
Labels: console-measurements

#1157 [UXE-1946] feat: adding ordering to the edge firewall rules engine table
  src/helpers/get-array-changed-indexes.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-rules-engine-services/index.js
  src/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-reorder-base-url.js
  src/services/edge-firewall-rules-engine-services/reorder-edge-firewall-rules-engine-service.js
  src/templates/list-table-block/no-header.vue
  src/tests/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-base-url.test.js
  src/tests/services/edge-firewall-rules-engine-services/reorder-edge-firewall-rules-engine-service.test.js
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: console-measurements

#1161 [UXE-2888] fix: reset filters before update
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
Labels: bug

#1163 [NO-ISSUE] refactor: update text in settings description in edgeDns
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
Labels: code-refactor

#1162 [UXE-3301] refactor: edge app rules engine page selectors radio and switch changed to new blocks
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: bug, code-refactor

#1164 [UXE-2890] fix: resolve zero value causing bad request
  src/templates/advanced-filter/component/display/chips-default-display.vue
  src/templates/advanced-filter/component/fields/text-filter.vue
  src/templates/advanced-filter/dialog-filter.vue
Labels: bug

#1159 [UXE-2129] feat: add tracker event in rules and functions in edge firewall
  src/views/EdgeFirewall/EditView.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
Labels: console-measurements

#1165 [UXE-2342] refactor: change text color and the spaces in Realtime Purge Dialog
  src/views/RealTimePurge/Dialog/index.vue
Labels: enhancement

#1167 [UXE-2934] fix: adjustment max size component pick list
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: bug

#1168 [UXE-3297] refactor: edge app origins drawer selectors radio and switch changed to new blocks
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: code-refactor

#1172 [UXE-3321] doc: create pr templates
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bug.md
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/deploy.md
Labels: documentation

#1173 [QA-1924] feat: implement cypress tests in azion console kit ci/cd workflow
  .github/workflows/e2e-tests.yml
  .gitignore
  DEVELOPER.md
  cypress.config.js
  package.json
  yarn.lock
Labels: e2e tests

#1175 [UXE-2342] refactor: rename the tittle of repurge dialog to Confirm Repurge
  src/views/RealTimePurge/Dialog/index.vue
Labels: code-refactor

#1177 [UXE-3330] fix: refactor feedbackfish component styling
  src/templates/navbar-block/feedback-fish.vue
  src/templates/navbar-block/index.vue
Labels: bug, code-refactor

#1178 [UXE-1784] feat: increased lines in monaco on dataStream view
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: enhancement

#1179 [UXE-3360] fix: adjusted resize monaco editor in data stream
  src/templates/create-form-block/form-horizontal.vue
Labels: bug

#1171 [UXE-2088] feat: add edited edge functions event tracker
  src/services/edge-functions-services/edit-edge-functions-service.js
  src/views/EdgeFunctions/EditView.vue
Labels: console-measurements

#1170 [UXE-2131] feat: add failed to create function event to tracker
  src/services/edge-functions-services/create-edge-functions-service.js
  src/views/EdgeFunctions/CreateView.vue
Labels: console-measurements

#1183 [UXE-3315] refactor: add life in toast in reorder request
  src/services/edge-functions-services/edit-edge-functions-service.js
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/views/EdgeFunctions/EditView.vue
Labels: code-refactor

#1174 [QA-1939] feat: add cypress login test
  .github/workflows/e2e-tests.yml
  .gitignore
  DEVELOPER.md
  cypress.config.js
  cypress.env.example.json
  cypress/e2e/login.cy.js
Labels: e2e tests

#1188 [UXE-2093] feat: domains create clicked event to edit domain
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/ListView.vue
Labels: console-measurements

#1186 [UXE-2927] fix: adding custom template option for data stream
  src/services/data-stream-services/create-data-stream-service.js
  src/services/data-stream-services/edit-data-stream-service.js
  src/services/data-stream-services/list-data-stream-service.js
  src/services/data-stream-services/list-data-stream-template-service.js
  src/services/data-stream-services/load-data-stream-service.js
  src/tests/services/data-stream-services/create-data-stream-service.test.js
  src/tests/services/data-stream-services/edit-data-stream-service.test.js
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1189 [UXE-3299] refactor: real time purge radios selectors changed to new blocks
  src/templates/create-form-block/form-horizontal.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: code-refactor

#1190 [UXE-2134] feat: add event track failed to create domain
  src/services/domains-services/create-domain-service.js
  src/tests/services/domains-services/create-domain-service.test.js
  src/views/Domains/CreateView.vue
Labels: enhancement, unit-tests, console-measurements

#1191 [NO-ISSUE] fix: invite your team home page
  src/templates/form-fields-inputs/fieldSwitchBlock.vue
  src/tests/services/data-stream-services/create-data-stream-service.test.js
  src/tests/services/data-stream-services/edit-data-stream-service.test.js
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
  src/views/Home/HomeView.vue
Labels: bug

#1187 [UXE-1709] fix: change domain name validation to only ascii caracteres
  src/views/Domains/CreateView.vue
Labels: bug

#1192 [NO-ISSUE] fix: add fixed white background to improve qr code camera readability
  src/templates/mfa-setup-block/index.vue
Labels: bug, theming

#1193 refactor: rename Domains to Domain in tracker event
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/ListView.vue
Labels: console-measurements

#1202 [NO-ISSUE] chore: improve project version from 1.15.3 to 1.15.4
  package.json
  src/views/Domains/CreateView.vue
Labels: project version

#1205 [UXE-1709] fix: change regex from name field validation and add the same validat…
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
Labels: bug

#1206 [UXE-1876] fix: remove then from divider and change match zone field label to si…
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
Labels: bug

#1208 [UXE-1981] fix: change rules engine behaviors, criterias and conditionals delete…
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1209 [NO-ISSUE] refactor: remove text opacity from card text when selector is present
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/selector-block/index.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: code-refactor

#1207 [UXE-3246] fix: add regex validation to key field in variables form
  src/views/Variables/CreateView.vue
  src/views/Variables/EditView.vue
Labels: bug

#1215 [UXE-3296] fix: ensure image optimization option is passed to rules engine edit
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1210 [UXE-2391] fix: adjusted the colors of the today color calendar
  src/assets/themes/scss/themes/azion-dark/variables/_form.scss
  src/assets/themes/scss/themes/azion-light/variables/_form.scss
Labels: bug, theming

#1213 [UXE-2579] fix: adjustment in opacity of disabled elements
  src/assets/themes/scss/themes/azion-dark/variables/_general.scss
  src/assets/themes/scss/themes/azion-light/variables/_general.scss
Labels: theming

#1212 [UXE-2869] fix: edit records in second page
  src/services/edge-dns-records-services/load-records-service.js
  src/tests/services/edge-dns-records-services/load-records-service.test.js
Labels: bug

#1214 [UXE-1951] fix: home card section title to mach correct Azion product naming
  src/helpers/index.js
  src/helpers/remove-html-tag-from-text.js
  src/tests/helpers/remove-html-tags-from-text.test.js
  src/views/Home/HomeView.vue
Labels: bug
