Repository aziontech/azion-console-kit, pull requests merged in 2024-03, with the labels that each got.

#798 [UXE-2097] feat: add track event User Signed Up
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/signup-block/account-activation.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/templates/signup-block/form-signup-block.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests, console-measurements

#799 [UXE-2042] fix: update edge functions and image processor
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/data-streaming/list-data-streaming.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/intelligent-dns/list-intelligent-dns.js
  src/services/real-time-events-service/l2-cache/list-l2-cache.js
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStreaming/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/Drawer/index.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsIntelligentDNS/ListView.vue
  src/views/RealTimeEventsL2Cache/ListView.vue
Labels: bug

#810 [UXE-2100] feat: added track event submitted additional data
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/signup-block/additional-data-form-block.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests, console-measurements

#811 [UXE-2046] fix: update element tag in info-section component
  src/templates/info-drawer-block/info-section/index.vue
Labels: bug

#772 [EDU-4173] Bug Hunting - UXW adjustments
  src/router/routes/team-permission/index.js
  src/router/routes/users-routes/index.js
  src/templates/action-bar-block/index.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/CreateNew/DeployView.vue
  src/views/Marketplace/SolutionView.vue
  src/views/TeamsPermissions/CreateView.vue
  src/views/TeamsPermissions/EditView.vue
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
  src/views/TeamsPermissions/ListView.vue
Labels: writing, waiting-for-uxe-to-merge

#805 [UXE-2182] refactor: update uxw digital certificate
  src/services/metrics-services/constants/dashboards-texts.js
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: writing, waiting-for-uxe-to-merge

#804 [UXE-2104] feat: added a tracker when clicking on create in header and home
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/navbar-block/create.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/Home/HomeView.vue
Labels: enhancement, unit-tests, console-measurements

#787 [UXE-2050] fix: added cache key value in l2 cache drawer
  src/views/RealTimeEventsL2Cache/Drawer/index.vue
Labels: bug

#806 [UXE-2098] feat: added track event User Failed to Sign Up
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/signup-block/form-signup-block.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests, console-measurements

#813 [UXE-2101] feat: added track event failed submit additional data
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/signup-block/additional-data-form-block.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement, unit-tests, console-measurements

#814 [NO-ISSUE] fix: sufix big number font size
  src/templates/info-drawer-block/info-labels/big-number.vue
Labels: bug

#808 [UXE-2219] fix: show digital certificate status
  src/services/digital-certificates-services/list-digital-certificates-service.js
  src/tests/services/digital-certificates-services/list-digital-certificates-service.test.js
Labels: bug

#807 [UXE-2038] fix: change the icon and ts size in real time events time stamp
  src/templates/info-drawer-block/info-section/index.vue
Labels: bug

#815 [UXE-1959] refactor: adjust metrics theme config
  src/assets/c3.scss
  src/templates/graphs-card-block/constants/color-patterns.js
Labels: bug, code-refactor

#816 [NO-ISSUE] fix: temporarily commented code
  src/services/real-time-events-service/http-request/load-http-request.js
Labels: experimental-changes

#817 [UXE-2041] refactor: update view events documentation links
  src/helpers/azion-documentation-catalog.js
  src/router/routes/real-time-events-routes/index.js
Labels: code-refactor

#821 [UXE-2105] feat: added tracker event when clicking on a template
  src/assets/c3.scss
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/create-modal-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/Home/HomeView.vue
Labels: enhancement, unit-tests, console-measurements

#824 [UXE-2286] fix: add new properties to adaptResponse function
  src/services/real-time-events-service/http-request/load-http-request.js
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
Labels: bug, code-refactor

#823 [UXE-2106] feat: add tracker when clicked to view more details on template
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/CreateView.vue
Labels: enhancement, unit-tests, console-measurements

#825 [UXE-2099] feat: added track event activated account
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/Login/LoginView.vue
Labels: enhancement, unit-tests, code-refactor, console-measurements

#826 [UXE-2107] feat: add deployed tracker
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/template-engine-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, unit-tests, console-measurements

#829 [UXE-2108] feat: failed to deploy
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/template-engine-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/DeployView.vue
Labels: enhancement, unit-tests, console-measurements

#828 [NO-ISSUE] feat: add production key for segment in analytics factory to ensure production integration
  src/plugins/factories/analytics-tracking-factory.js
Labels: enhancement, console-measurements

#832 chore: upgrade project version from 1.8.8 to 1.9.0
  package.json
Labels: project version

#830 [UXE-2037] fix: adjust style big numbers
  src/views/RealTimeEventsDataStreaming/Drawer/index.vue
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
  src/views/RealTimeEventsImageProcessor/Drawer/index.vue
  src/views/RealTimeEventsL2Cache/Drawer/index.vue
Labels: bug, do-not-merge

#836 [UXE-2163] feat: update l2 caching to tiered cache
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: categorized, console-measurements

#838 [UXE-1888] feat: add clicked to create origin event
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
Labels: enhancement, unit-tests, console-measurements

#840 [UXE-1889] feat: add created origin event tracker
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/CreateView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
Labels: enhancement, unit-tests, console-measurements

#843 feat: added props to user failed signin track event
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/services/signup-services/signup-service.js
  src/templates/signup-block/form-signup-block.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: enhancement, console-measurements

#841 [NO-ISSUE] fix: using the right match zones for WAF allowed rules
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
Labels: bug

#845 [UXE-2163] fix: tiered cache typo in form fields of real time purge
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: bug

#846 [NO-ISSUE] chore: upgrade project version from version 1.9.0 to 1.9.1
  package.json
Labels: project version

#847 DEPLOY 2024.03.06
  package.json
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/services/signup-services/signup-service.js
  src/templates/signup-block/form-signup-block.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/CreateView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/RealTimeEventsDataStreaming/Drawer/index.vue
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
  src/views/RealTimeEventsImageProcessor/Drawer/index.vue
  src/views/RealTimeEventsL2Cache/Drawer/index.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
Labels: DEPLOY

#850 [NO-ISSUE] fix: typo in realtime purge create view initial values
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
  src/views/RealTimePurge/CreateView.vue
Labels: bug

#851 DEPLOY 2024.03.06
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
  src/views/RealTimePurge/CreateView.vue
Labels: DEPLOY

#849 [UXE-1890] feat: failed to create origin
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
Labels: enhancement, unit-tests, console-measurements

#842 [UXE-2185] [UXE-2186] refactor: uxw data streaming
  src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
  src/views/DataStreaming/ListView.vue
Labels: writing, waiting-for-uxe-to-merge

#839 [UXE-2183] refactor: update network list placeholder
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
Labels: writing, waiting-for-uxe-to-merge

#852 [UXE-1891] feat: add event tracker clicked to edit origin
  src/views/EdgeApplicationsOrigins/ListView.vue
Labels: enhancement, console-measurements

#853 [UXE-1904] feat: add event tracker edited origin
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
Labels: enhancement, console-measurements

#855 [EDU-4249] feat: product naming
  src/router/routes/data-streaming-routes/index.js
  src/router/routes/intelligent-dns-routes/index.js
  src/services/metrics-services/constants/dashboards-texts.js
  src/services/metrics-services/constants/dashboards.js
  src/services/metrics-services/constants/reports.js
  src/services/sidebar-menus-services/menus.js
  src/templates/create-modal-block/index.vue
  src/views/DataStreaming/CreateView.vue
  src/views/DataStreaming/EditView.vue
  src/views/DataStreaming/FormFields/FormFieldsDataStreaming.vue
  src/views/DataStreaming/ListView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/IntelligentDNS/CreateView.vue
  src/views/IntelligentDNS/EditView.vue
  src/views/IntelligentDNS/FormFields/FormFieldsRecords.vue
  src/views/IntelligentDNS/ListView.vue
  src/views/RealTimeEvents/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/RealTimeEvents/TabsView.vue
  src/views/RealTimeEventsDataStreaming/ListView.vue
  src/views/RealTimeEventsIntelligentDNS/ListView.vue
Labels: writing

#856 [UXE-1906] feat: event tracker failed to edit origin
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
Labels: enhancement, unit-tests, console-measurements

#858 [UXE-2053] feat: add to tracking traits account full name
  src/App.vue
  src/views/RealTimeEventsIntelligentDNS/ListView.vue
Labels: enhancement, console-measurements

#857 [UXE-2050] fix: cache key info alignment
  src/views/RealTimeEventsL2Cache/Drawer/index.vue
Labels: bug

#859 [UXE-2404] refactor: rename intelligent dns to edge dns in store
  src/stores/edge-dns.js
  src/views/IntelligentDNS/FormFields/FormFieldsIntelligentDns.vue
  src/views/IntelligentDNS/FormFields/FormFieldsRecords.vue
Labels: code-refactor

#860 [UXE-2406] refactor: change edge dns routes
  src/router/index.js
  src/router/routes/edge-dns-routes/index.js
  src/services/intelligent-dns-records-services/create-records-service.js
  src/services/intelligent-dns-services/create-intelligent-dns-service.js
  src/services/sidebar-menus-services/menus.js
  src/stores/solution-create.js
  src/views/IntelligentDNS/EditView.vue
  src/views/IntelligentDNS/ListView.vue
  src/views/RealTimeEventsIntelligentDNS/ListView.vue
Labels: code-refactor

#863 [ENG-2436] fix: [metrics] remove resample param from gql query
  src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
  src/stores/metrics-store/helpers/convert-report-meta-to-gql.js
  src/tests/store/metrics-store/helpers/fixtures/convert-report-fixtures.js
Labels: bug, unit-tests

#862 [UXE-2422] refactor: l2 cache to tiered cache labels, variables and functions names
  src/helpers/azion-documentation-catalog.js
  src/router/routes/real-time-events-routes/index.js
  src/services/metrics-services/constants/dashboards-texts.js
  src/services/metrics-services/constants/dashboards.js
  src/services/metrics-services/constants/reports.js
  src/services/real-time-events-service/index.js
  src/services/real-time-events-service/l2-cache/index.js
  src/services/real-time-events-service/tiered-cache/index.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/views/RealTimeEvents/TabsView.vue
  src/views/RealTimeEventsTieredCache/Drawer/index.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
Labels: code-refactor

#867 [UXE-2436] fix: [metrics] adjust aggregationType for some reports
  src/services/metrics-services/constants/reports.js
Labels: bug

#874 [UXE-2340] feat implements new type origins
  src/services/edge-application-origins-services/create-origin-service.js
  src/services/edge-application-origins-services/edit-origin-service.js
  src/services/edge-application-origins-services/list-origins-service.js
  src/services/edge-application-origins-services/load-origin-service.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: enhancement, categorized

#877 [UXE-2144] feat: add params to deploy failure and success events measurement
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/stores/solution-create.js
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/CreateView.vue
  src/views/CreateNew/DeployView.vue
Labels: console-measurements

#880 [NO-ISSUE] chore: upgrade project version from version 1.9.1 to 1.10.0
  package.json
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: project version

#882 [NO-ISSUE] fix: checking the value of the prefix
  src/services/edge-application-origins-services/create-origin-service.js
  src/services/edge-application-origins-services/edit-origin-service.js
Labels: bug

#890 [NO-ISSUE] chore: merge main with dev
  src/services/signup-services/signup-service.js
  src/templates/signup-block/form-signup-block.vue
  src/views/CreateNew/CreateView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/RealTimeEventsDataStream/Drawer/index.vue
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
  src/views/RealTimeEventsImageProcessor/Drawer/index.vue
  src/views/RealTimeEventsTieredCache/Drawer/index.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: bug, code-refactor

#887 [UXE-2494] fix: error when i try to change the minimum TLS version
  src/services/edge-application-services/edit-edge-application-service.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: bug, categorized

#891 [NO-ISSUE] fix: validation fields in origin
  src/services/edge-application-origins-services/create-origin-service.js
  src/services/edge-application-origins-services/edit-origin-service.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
Labels: bug

#888 [NO-ISSUE] fix: edge node list was not listing the data
  src/views/EdgeNode/ListView.vue
Labels: bug

#868 [UXE-2053] feat: Insert properties in the event create edge application
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/create-modal-block/index.vue
  src/views/CreateNew/CreateView.vue
  src/views/CreateNew/DeployView.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
Labels: enhancement, unit-tests, console-measurements

#878 [UXE-2037] fix: adjusting display of big numbers
  src/views/RealTimeEventsDataStream/Drawer/index.vue
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
  src/views/RealTimeEventsImageProcessor/Drawer/index.vue
  src/views/RealTimeEventsTieredCache/Drawer/index.vue
Labels: bug, theming, categorized

#883 [UXE-2218] feat: add clicked to deploy event
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/templates/template-engine-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/CreateView.vue
Labels: console-measurements

#864 [EDU-4297] fix: banner from experimental to preview and remove button
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
Labels: writing, waiting-for-uxe-to-merge

#782 [UXE-2024] test: added tests to all events services and helpers
  src/helpers/capitalize-first-letter.js
  src/helpers/convert-gql.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/tests/helpers/convert-gql.test.js
  src/tests/services/activity-history-service/list-activity-history-service.test.js
  src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
  src/tests/services/real-time-events-service/activity-history/load-activity-history.test.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/data-stream/load-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-dns/load-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions-console/load-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/edge-functions/load-edge-functions.test.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
  src/tests/services/real-time-events-service/http-request/load-http-request.test.js
  src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
  src/tests/services/real-time-events-service/image-processor/load-image-processor.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
  src/tests/services/real-time-events-service/tiered-cache/load-tiered-cache.test.js
Labels: unit-tests

#892 [UXE-2097] feat: added sso methods to signup tracking
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/router/routes/signup-routes/index.js
  src/stores/account.js
  src/templates/signup-block/form-signup-block.vue
  src/templates/signup-block/social-signup-block.vue
  src/templates/social-idps-block/index.vue
  src/tests/plugins/adapters/AnalyticsTrackerAdapter.test.js
Labels: unit-tests, code-refactor, console-measurements

#897 [UXE-1949] fix: when an account has the enforce MFA enabled, all the …
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: bug, categorized

#904 [EDU-4301] refactor: update metrics urls
  src/services/metrics-services/constants/dashboards-texts.js
  src/services/metrics-services/constants/help-center-urls.js
  src/services/metrics-services/constants/reports.js
Labels: code-refactor

#905 [EDU-4301] refactor: update helpcenter urls on metrics
  src/services/metrics-services/constants/help-center-urls.js
  src/services/metrics-services/constants/reports.js
Labels: code-refactor

#906 [EDU-4301] refactor: update edge-dns and data-stream helpcenter urls on metrics
  src/services/metrics-services/constants/help-center-urls.js
Labels: code-refactor

#902 [UXE-2562] fix: phase button hidden in edit rules engine
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#907 [NO-ISSUE] chore: update project version to 1.11.0
  package.json
Labels: project version

#831 [UXE-2477] refactor: tracker adapter structure
  src/App.vue
  src/plugins/AnalyticsTrackerAdapterPlugin.js
  src/plugins/adapters/AnalyticsTrackerAdapter.js
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/analytics/trackers/CreateTracker.js
  src/plugins/analytics/trackers/ProductTracker.js
  src/plugins/analytics/trackers/SignInTracker.js
  src/plugins/analytics/trackers/SignUpTracker.js
  src/plugins/analytics/trackers/index.js
  src/router/hooks/afterEachRoute.js
  src/router/routes/signup-routes/index.js
  src/stores/account.js
  src/templates/create-modal-block/index.vue
  src/templates/navbar-block/create.vue
  src/templates/sign-in-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/templates/signup-block/form-signup-block.vue
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/views/CreateNew/CreateView.vue
  src/views/CreateNew/DeployView.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/Home/HomeView.vue
  src/views/Login/LoginView.vue
Labels: code-refactor, console-measurements

#912 [UXE-1950] fix: rules engine not loading behavior
  src/services/edge-firewall-functions-services/list-functions-service.js
  src/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.js
Labels: bug

#913 [UXE-2561] update session data
  src/App.vue
  src/helpers/store-handler.js
Labels: bug, categorized

#919 fix: unsaved alert even after clicking save button
  src/views/WafRules/TabsView.vue
Labels: bug, categorized

#917 [UXE-1811] alinhamento dos itens do footer
  src/templates/footer-block/index.vue
  src/templates/system-status-bar-block/index.vue
Labels: theming, code-refactor

#920 [UXE-2433] fix: not validating account expiration
  src/helpers/account-expired.js
  src/router/hooks/beforeEachRoute.js
  src/tests/helpers/account-expired.test.js
Labels: bug

#921 [UXE-2050] fix: spacing and alignment of copy cache key button
  src/templates/info-drawer-block/info-labels/text-info.vue
  src/views/RealTimeEventsTieredCache/Drawer/index.vue
Labels: bug

#923 [UXE-2633] fix: listings without deletion action
  src/templates/list-table-block/no-header.vue
Labels: bug, categorized

#918 [UXE-2513] fix: overwrite z-index
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#925 [UXE-1948] fix: different looking column
  src/templates/list-table-block/no-header.vue
Labels: bug

#924 feat: custom theme values for password
  src/assets/themes/scss/themes/azion-dark/variables/_form.scss
  src/assets/themes/scss/themes/azion-light/variables/_form.scss
  src/views/Playground/PlaygroundView.vue
Labels: theming

#927 [UXE-1945] fix: Origin not loading in error response
  src/services/edge-application-origins-services/list-origins-service.js
Labels: bug

#928 [UXE-1966] behaviors loading incorrectly
  src/assets/themes/scss/themes/azion-dark/variables/_form.scss
  src/assets/themes/scss/themes/azion-light/variables/_form.scss
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug, categorized

#932 [UXE-2301] refactor: remove store use from card components
  src/stores/metrics.js
  src/templates/graphs-card-block/components/aggregation-info.vue
  src/templates/graphs-card-block/components/more-options-menu.vue
  src/templates/graphs-card-block/index.vue
Labels: code-refactor

#930 [UXE-2534] fix: make service catch when there is a error in the results of a script
  src/services/script-runner-service/get-script-runner-results-service.js
  src/tests/services/script-runner-services/get-script-runner-results-serice.test.js
Labels: bug

#936 [UXE-2560] fix: Entity name is missing on edition
  src/views/EdgeServices/EditView.vue
  src/views/EdgeServices/TabsView.vue
Labels: bug

#931 [UXE-2399] feat: added responsive layout to advanced filter in metrics layout
  src/templates/advanced-filter/component/fields/float-filter.vue
  src/templates/advanced-filter/component/fields/float-range-filter.vue
  src/templates/advanced-filter/component/fields/multiselect-filter.vue
  src/templates/advanced-filter/component/fields/number-filter.vue
  src/templates/advanced-filter/component/fields/number-range-filter.vue
  src/templates/advanced-filter/component/fields/text-filter.vue
  src/templates/advanced-filter/dialog-filter.vue
Labels: enhancement

#934 [UXE-2254] fix: stacktrace field case fix
  src/views/RealTimeEventsHTTPRequests/Drawer/index.vue
Labels: bug

#937 [NO-ISSUE] fix: events field name
  src/views/RealTimeEventsHTTPRequests/ListView.vue
Labels: writing, waiting-for-uxe-to-merge

#938 [NO-ISSUE] fix: incorrect tracking event chaining in sign up methods
  src/router/routes/signup-routes/index.js
Labels: bug

#939 [UXE-2002] fix: map of undefined in team permissions load
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
Labels: bug

#935 [UXE-2304] refactor: isolate beholder date proto
  src/App.vue
  src/helpers/convert-date.js
  src/helpers/index.js
  src/modules/real-time-metrics/constants/time-intervals.js
  src/modules/real-time-metrics/helpers/convert-date.js
  src/router/routes/personal-tokens-routes/index.js
  src/tests/helpers/convert-date.test.js
  src/tests/modules/real-time-metrics/helpers/convert-date.test.js
  src/tests/services/real-time-metrics-services/make-domains-base-url.test.js
  src/tests/services/real-time-metrics-services/make-edge-dns-base-url.test.js
  src/tests/services/real-time-metrics-services/make-edge-functions-base-url.test.js
  src/tests/services/real-time-metrics-services/search-domains-service.test.js
  src/tests/services/real-time-metrics-services/search-edge-dns-service.test.js
  src/tests/services/real-time-metrics-services/search-edge-functions-service.test.js
  src/views/PersonalTokens/CreateView.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Labels: code-refactor

#940 [UXE-2488] fix: captcha off-screen
  src/assets/main.css
Labels: bug

#946 chore: update project version
  package.json
Labels: project version

#944 [UXE-2514] fix: scroll disables when the mouse is on the table
  src/assets/themes/scss/themes/azion-dark/extended-components/_datatable.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_datatable.scss
Labels: bug
