Repository aziontech/azion-console-kit, pull requests merged in 2024-11, with the labels that each got.

#1873 [UXE-5553] feat: add sampling behavior to datastream form
  src/services/data-stream-services/load-data-stream-service.js
  src/stores/account.js
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: enhancement, end-of-life-rtm

#1875 [NO-ISSUE] fix: fix search on the table
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
Labels: enhancement

#1870 [UXE-5550] feat: Block users with more than 2999 domains to acess data-stream creation
  src/helpers/convert-array-objects-to-camel-case.js
  src/helpers/make-list-service-query-params.js
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/domainsLimitGuard.js
  src/router/hooks/guards/index.js
  src/services/team-permission/list-team-permission-service.js
  src/services/workloads-services/index.js
  src/services/workloads-services/list-workloads-service.js
  src/services/workloads-services/make-workloads-base-url.js
  src/templates/empty-results-block/index.vue
  src/templates/list-table-block/index.vue
  src/tests/helpers/convert-array-objects-to-camel-case.test.js
  src/tests/services/team-permission-services/list-team-permission-service.test.js
  src/tests/services/workloads-services/list-workloads.test.js
  src/tests/services/workloads-services/make-workloads-base-url.test.js
  src/views/DataStream/ListView.vue
Labels: good first issue

#1872 [UXE-5558] feat: migrate digital certificate to v4
  src/router/routes/digital-certificates-routes/index.js
  src/services/digital-certificates-services/v4/index.js
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/services/digital-certificates-services/v4/make-digital-certificates-base-url.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
  src/tests/services/digital-certificates-services/v4/make-digital-certificates-base-url.test.js
  src/views/DigitalCertificates/ListView.vue
Labels: enhancement

#1874 [UXE-5291] feat: migrate edge firewall to v4
  src/helpers/convert-date.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-functions-services/list-edge-firewall-functions-service.js
  src/services/edge-firewall-functions-services/v4/index.js
  src/services/edge-firewall-functions-services/v4/list-functions-service.js
  src/services/edge-firewall-rules-engine-services/v4/index.js
  src/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-services/v4/index.js
  src/services/edge-firewall-services/v4/list-edge-firewall-service.js
  src/services/edge-firewall-services/v4/make-edge-firewall-base-url.js
  src/tests/helpers/convert-date.test.js
  src/tests/services/edge-firewall-functions-services/v4/list-functions-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.test.js
  src/tests/services/edge-firewall-services/v4/list-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/v4/make-edge-firewall-base-url.test.js
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: enhancement

#1871 [UXE-5555] feat: migrate network list to v4
  src/router/routes/network-lists-routes/index.js
  src/services/network-lists-services/v4/index.js
  src/services/network-lists-services/v4/list-network-list-service.js
  src/services/network-lists-services/v4/make-network-list-service.js
  src/tests/services/network-lists-services/v4/list-network-list-service.test.js
  src/tests/services/network-lists-services/v4/make-network-list-base-url.test.js
  src/views/NetworkLists/ListView.vue
Labels: enhancement

#1877 [UXE-5541] feat: migrate domains to workloads in real time metrics
  src/modules/real-time-metrics/constants/services-operator-in.js
  src/services/real-time-metrics-services/index.js
  src/services/real-time-metrics-services/make-workloads-base-url.js
  src/services/real-time-metrics-services/search-workloads-service.js
  src/services/workloads-services/makeWorkloadsBaseUrl.js
  src/tests/modules/real-time-metrics/constants/map-services-operator-in.test.js
  src/tests/services/real-time-metrics-services/search-workloads-service.test.js
Labels: enhancement, unit-tests

#1876 [UXE-5297] feat: migrate allowed rules to v4
  src/services/waf-rules-services/list-waf-rules-allowed-service.js
  src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: enhancement

#1881 [NO-ISSUE] fix: request workloads just when target route is data stream
  src/router/hooks/guards/domainsLimitGuard.js
Labels: bug

#1879 [UXE-5576] feat: add menu option to manage accounts depending on the account type
  src/templates/profile-block/index.vue
Labels: good first issue

#1887 [UXE-5580] feat: add reseller, group and client management list views
  src/helpers/make-list-service-query-params.js
  src/router/index.js
  src/router/routes/client-management-routes/index.js
  src/router/routes/group-management-routes/index.js
  src/router/routes/reseller-management-routes/index.js
  src/services/accounts-management-services/index.js
  src/services/accounts-management-services/list-accounts-service.js
  src/services/accounts-management-services/make-accounts-management-base-url.js
  src/services/axios/AxiosHttpClientAdapter.js
  src/services/real-time-metrics-services/search-workloads-service.js
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/templates/profile-block/index.vue
  src/tests/services/accounts-management-services/list-accounts-service.test.js
  src/tests/services/accounts-management-services/make-accounts-management-base-url.test.js
  src/views/ClientManagement/ListView.vue
  src/views/GroupManagement/ListView.vue
  src/views/ResellerManagement/ListView.vue
Labels: good first issue

#1880 [UXE-5585] feat: migrate domains to v4
  src/router/routes/domains-routes/index.js
  src/services/domains-services/v4/index.js
  src/services/domains-services/v4/list-domain-service.js
  src/services/domains-services/v4/make-domains-service.js
  src/tests/services/domains-services/v4/list-domain-service.test.js
  src/tests/services/domains-services/v4/make-domains-base-url.test.js
  src/views/Domains/ListView.vue
Labels: enhancement

#1883 [UXE-5583] feat: add behavior to clone edge app
  src/services/edge-application-services/v4/clone-edge-application-service.js
  src/services/edge-application-services/v4/index.js
  src/services/edge-application-services/v4/list-edge-applications-service.js
  src/tests/services/edge-application-services/v4/clone-edge-applications-service.test.js
  src/tests/services/edge-application-services/v4/list-edge-applications-service.test.js
  src/views/EdgeApplications/Dialog/Clone.vue
  src/views/EdgeApplications/ListView.vue
Labels: enhancement

#1885 [UXE-5286] feat: migrate wafs to v4
  src/router/routes/waf-rules-routes/index.js
  src/services/waf-rules-services/v4/index.js
  src/services/waf-rules-services/v4/list-waf-rules-service.js
  src/services/waf-rules-services/v4/make-waf-rules-base-url.js
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/tests/services/waf-rules-services/v4/list-waf-rules-service.test.js
  src/tests/services/waf-rules-services/v4/make-waf-rules-make-base-url.test.js
  src/views/DigitalCertificates/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/WafRules/ListView.vue
Labels: enhancement

#1896 [UXE-5525] fix: Some custom ports not selecting when editing Edge App
  src/services/edge-application-services/load-edge-application-service.js
  src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
  src/tests/services/edge-application-services/load-edge-application-service.test.js
  src/tests/services/network-lists-services/edit-network-list-service.test.js
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: enhancement

#1894 [UXE-5584] feat: add clone waf rules behavior
  src/services/waf-rules-services/v4/clone-waf-rules-service.js
  src/services/waf-rules-services/v4/index.js
  src/tests/services/waf-rules-services/v4/clone-waf-rules-service.test.js
  src/views/WafRules/Dialog/Clone.vue
  src/views/WafRules/ListView.vue
Labels: enhancement

#1890 [UXE-5587] feat: clone behavior edge firewall
  src/services/edge-firewall-services/v4/clone-edge-firewall-service.js
  src/services/edge-firewall-services/v4/index.js
  src/services/edge-firewall-services/v4/list-edge-firewall-service.js
  src/tests/services/edge-firewall-services/v4/clone-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/v4/list-edge-firewall-service.test.js
  src/views/EdgeFirewall/Dialog/Clone.vue
  src/views/EdgeFirewall/ListView.vue
Labels: enhancement

#1902 [NO-ISSUE] fix: clone edge app
  src/services/edge-application-services/v4/clone-edge-application-service.js
  src/services/edge-application-services/v4/list-edge-applications-service.js
  src/tests/services/edge-application-services/v4/clone-edge-applications-service.test.js
  src/tests/services/edge-application-services/v4/list-edge-applications-service.test.js
  src/views/EdgeApplications/Dialog/Clone.vue
Labels: bug, code-refactor

#1899 [UXE-5621] fix: Origin not loading in Edge App Rules Engine set origin behavior
  src/services/edge-application-rules-engine-services/helper-behavior.js
  src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js
Labels: bug

#1886 [UXE-5616] feat: remove route guards / redirect to rtm
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/index.js
  src/router/hooks/guards/redirectToManagerGuard.js
  src/tests/router/hooks/guards/redirectToManagerGuard.test.js
Labels: console-measurements

#1907 [UXE-5669] test: add ENTER hit in all v4 tables tests
  cypress/e2e/data-stream/create-data-stream-awskinesis.cy.js
  cypress/e2e/data-stream/create-data-stream-azureblobstorage.cy.js
  cypress/e2e/data-stream/create-data-stream-azuremonitor.cy.js
  cypress/e2e/data-stream/create-data-stream-bigquery.cy.js
  cypress/e2e/data-stream/create-data-stream-datadog.cy.js
  cypress/e2e/data-stream/create-data-stream-elasticsearch.cy.js
  cypress/e2e/data-stream/create-data-stream-ibmqradar.cy.js
  cypress/e2e/data-stream/create-data-stream-kafka.cy.js
  cypress/e2e/data-stream/create-data-stream-s3.cy.js
  cypress/e2e/data-stream/create-data-stream-splunk.cy.js
  cypress/e2e/data-stream/create-data-stream-standard.cy.js
  cypress/e2e/digital-certificates/create-digital-certificate.cy.js
  cypress/e2e/edge-application/add-origin.cy.js
  cypress/e2e/edge-application/create-function-instance.cy.js
  cypress/e2e/edge-application/edit-cache-setting.cy.js
  cypress/e2e/edge-application/edit-function-instance.cy.js
  cypress/e2e/edge-application/edit-origin.cy.js
  cypress/e2e/edge-application/instantiate-function-rules-engine.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-cache-policy.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine.cy.js
  cypress/e2e/edge-application/rules-engine/edit-rule-engine.cy.js
  cypress/e2e/edge-dns/create-record-type-a.cy.js
  cypress/e2e/edge-dns/create-record-type-aaaa.cy.js
  cypress/e2e/edge-dns/create-record-type-aname.cy.js
  cypress/e2e/edge-dns/create-record-type-caa.cy.js
  cypress/e2e/edge-dns/create-record-type-cname.cy.js
  cypress/e2e/edge-dns/create-record-type-ds.cy.js
  cypress/e2e/edge-dns/create-record-type-mx.cy.js
  cypress/e2e/edge-dns/create-record-type-ns.cy.js
  cypress/e2e/edge-dns/create-record-type-ptr.cy.js
  cypress/e2e/edge-dns/create-record-type-srv.cy.js
  cypress/e2e/edge-dns/create-record-type-txt.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-waf.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall.cy.js
  cypress/e2e/edge-services/create-edge-service.cy.js
  cypress/e2e/edge-services/edit-edge-service-resource.cy.js
  cypress/e2e/users-management/create-user-owner.cy.js
  cypress/e2e/users-management/create-user-with-team.cy.js
  cypress/e2e/variables/create-secret.cy.js
  cypress/e2e/variables/create-variable.cy.js
  cypress/e2e/variables/edit-variable.cy.js
  cypress/e2e/waf/create-allowed-rule-conditional-query-string.cy.js
  cypress/e2e/waf/create-allowed-rule-conditional-request-body.cy.js
  cypress/e2e/waf/create-allowed-rule-conditional-request-header.cy.js
  cypress/e2e/waf/create-allowed-rule-file-name.cy.js
  cypress/e2e/waf/create-allowed-rule-path-zone.cy.js
  cypress/e2e/waf/create-allowed-rule-raw-body.cy.js
  cypress/e2e/waf/create-waf-rule.cy.js
  cypress/e2e/waf/edit-waf-rule.cy.js
Labels: e2e tests

#1910 [UXE-5525] fix: select saved ports on edit page
  src/services/edge-application-services/load-edge-application-service.js
Labels: bug

#1908 [UXE-5672] fix: parsed correctly the list functions instance response
  src/router/routes/client-management-routes/index.js
  src/router/routes/group-management-routes/index.js
  src/views/ClientManagement/ListView.vue
  src/views/ClientsManagement/EditView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/GroupManagement/ListView.vue
  src/views/GroupsManagement/ListView.vue
  src/views/ResellerManagement/ListView.vue
  src/views/ResellersManagement/EditView.vue
  src/views/ResellersManagement/ListView.vue
Labels: bug

#1901 [UXE-5580] fix: change column name to company name and remove deleted accounts
  src/services/accounts-management-services/list-accounts-service.js
  src/tests/services/accounts-management-services/list-accounts-service.test.js
  src/views/ClientsManagement/ListView.vue
  src/views/GroupsManagement/ListView.vue
  src/views/ResellersManagement/ListView.vue
Labels: bug

#1916 [UXE-5555] fix: last modified sort field on Network Lists screen
  src/views/NetworkLists/ListView.vue
Labels: bug, code-refactor

#1917 [UXE-5292] fix: Edge Firewall Function Instances ordering
  src/views/EdgeFirewallFunctions/ListView.vue
Labels: bug, code-refactor

#1918 [UXE-5585] fix: Domain/Workloads sort columns issues
  src/views/Domains/ListView.vue
Labels: bug, code-refactor

#1920 [UXE-5291] fix: Edge Firewall List sort
  src/views/EdgeFirewall/ListView.vue
Labels: bug, code-refactor

#1914 [NO-ISSUE] test: added xfail in some edge application tests
  cypress/e2e/edge-application/add-error-response.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/edit-rule-engine.cy.js
Labels: e2e tests

#1919 [UXE-5558] fix: fields to order in the digital certificate
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
  src/views/DigitalCertificates/ListView.vue
Labels: bug, code-refactor

#1915 [UXE-5554] fix: added no cache parse in api v4 for cache settings edge app
  src/services/edge-application-cache-settings-services/v4/list-cache-settings-service.js
Labels: bug

#1922 [UXE-5286] refactor: fix sort field waf
  src/views/WafRules/ListView.vue
Labels: bug, code-refactor

#1923 [UXE-5297] fix: WAF Allowed rules - sort field and change field from description to name
  src/services/waf-rules-services/create-waf-rules-allowed-service.js
  src/services/waf-rules-services/edit-waf-rules-allowed-service.js
  src/services/waf-rules-services/list-waf-rules-allowed-service.js
  src/services/waf-rules-services/load-waf-rules-allowed-service.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/edit-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/list-waf-rules-allowed-service.test.js
  src/tests/services/waf-rules-services/load-waf-rules-allowed-sevice.test.js
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: bug, code-refactor

#1924 [NO-ISSUE] fix: sort field function in edge app function instances
  src/views/EdgeApplicationsFunctions/ListView.vue
Labels: bug, code-refactor

#1925 [NO-ISSUE] test: added hit enter in search inputs v4
  cypress/e2e/domains/edit-domain.cy.js
  cypress/e2e/edge-dns/create-edge-dns-zone.cy.js
  cypress/e2e/edge-dns/create-record-type-a.cy.js
  cypress/e2e/edge-dns/create-record-type-aaaa.cy.js
  cypress/e2e/edge-dns/create-record-type-aname.cy.js
  cypress/e2e/edge-dns/create-record-type-caa.cy.js
  cypress/e2e/edge-dns/create-record-type-cname.cy.js
  cypress/e2e/edge-dns/create-record-type-ds.cy.js
  cypress/e2e/edge-dns/create-record-type-mx.cy.js
  cypress/e2e/edge-dns/create-record-type-ns.cy.js
  cypress/e2e/edge-dns/create-record-type-ptr.cy.js
  cypress/e2e/edge-dns/create-record-type-srv.cy.js
  cypress/e2e/edge-dns/create-record-type-txt.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-network-list.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js
  cypress/e2e/personal-token/create-personal-token.cy.js
Labels: unit-tests

#1926 [NO-ISSUE] chore: update project version to 1.29.0
  package.json
Labels: project version

#1911 [UXE-5541] feat: creating domains component to have lazy loader
  src/helpers/real-time-filters-rules.js
  src/templates/advanced-filter/component/fields/multiselect-lazy-loader-filter.vue
  src/templates/advanced-filter/component/index.js
  src/tests/helpers/realt-time-filter-rules.test.js
Labels: console-measurements

#1931 [NO-ISSUE] fix: removed default name sorting from rules engine in edge application
  src/services/edge-application-rules-engine-services/v4/list-rules-engine-service.js
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/tests/services/edge-application-rules-engine-services/v4/list-rules-engine-service.test.js
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: bug

#1932 [UXE-5718] test: removed wrong spaccing in page title element
  src/templates/page-heading-block/index.vue
Labels: e2e tests

#1944 [UXE-5715] feat: migrate edge application cache settings creation form to use api v4
  cypress/e2e/edge-application/edit-cache-setting.cy.js
  src/helpers/extract-api-error.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-cache-settings-services/v4/create-cache-settings-service.js
  src/services/edge-application-cache-settings-services/v4/index.js
  src/tests/helpers/extract-api-error.test.js
  src/tests/services/edge-application-cache-settings-services/v4/create-cache-settings-service.test.js
Labels: api-v4-migration

#1895 [NO-ISSUE] chore: remove sass warning during compilation, 1.77.6 the last version withou warning
  package.json
  yarn.lock
Labels: enhancement, dependencies, theming

#1948 test: add e2e test cases to lazy loading table pagination
  cypress/e2mock/edge-application/list-edge-applications.cy.js
  cypress/fixtures/edge-application/edge-applications-paginated.json
  cypress/support/selectors/block-selectors/list-table-block.js
Labels: e2e tests

#1947 [NO-ISSUE] fix: correction in pagination in tables with api v4
  cypress/e2mock/edge-application/list-edge-applications.cy.js
  cypress/fixtures/edge-application/edge-applications-paginated.json
  cypress/support/selectors/block-selectors/list-table-block.js
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: bug, do-not-merge

#1937 [UXE-5742] feat: migrate create edge firewall post method to v4
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-services/v4/create-edge-firewall-service.js
  src/services/edge-firewall-services/v4/index.js
  src/tests/services/edge-firewall-services/v4/create-edge-firewall-service.test.js
  src/views/EdgeFirewall/Drawer/index.vue
Labels: enhancement

#1952 [UXE-5721] feat: migrate digital certificates delete to v4
  src/router/routes/digital-certificates-routes/index.js
  src/services/digital-certificates-services/v4/delete-digital-certificates-service.js
  src/services/digital-certificates-services/v4/index.js
  src/services/edge-firewall-services/v4/create-edge-firewall-service.js
  src/tests/services/digital-certificates-services/v4/delete-digital-certificates-service.test.js
Labels: enhancement

#1935 [UXE-5723] feat: migrate load service to v4 digital certificates
  src/router/routes/digital-certificates-routes/index.js
  src/services/digital-certificates-services/v4/index.js
  src/services/digital-certificates-services/v4/load-digital-certificates-service.js
  src/tests/helpers/convert-date.test.js
  src/tests/helpers/generate-timestamp.test.js
  src/tests/helpers/open-graphql-playground.test.js
  src/tests/services/auth-services/reset-password-service.test.js
  src/tests/services/axios/makeGoogleStorageApi.test.js
  src/tests/services/digital-certificates-services/v4/load-digital-certificates-service.test.js
  src/views/DigitalCertificates/EditView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: enhancement

#1946 [UXE-5720] feat: migrate patch digital certificate
  cypress/e2e/digital-certificates/edit-digital-certificate.cy.js
  src/router/routes/digital-certificates-routes/index.js
  src/services/digital-certificates-services/v4/edit-digital-certificates-service.js
  src/services/digital-certificates-services/v4/index.js
  src/tests/services/digital-certificates-services/v4/edit-digital-certificates-service.test.js
  src/tests/services/real-time-metrics-services/search-action-service.test.js
  src/tests/services/real-time-metrics-services/search-challenge-solved-service.test.js
  src/tests/services/real-time-metrics-services/search-classified-service.test.js
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: enhancement

#1950 [UXE-5719] feat: migrate create digital certificates
  src/router/routes/digital-certificates-routes/index.js
  src/services/digital-certificates-services/v4/create-digital-certificates-csr-service.js
  src/services/digital-certificates-services/v4/create-digital-certificates-services.js
  src/services/digital-certificates-services/v4/index.js
  src/services/digital-certificates-services/v4/make-digital-certificates-csr-base-url.js
  src/tests/services/digital-certificates-services/v4/create-digital-certificates-csr-services.test.js
  src/tests/services/digital-certificates-services/v4/create-digital-certificates-services.test.js
  src/tests/services/digital-certificates-services/v4/make-digital-certificates-csr-base-url.test.js
Labels: enhancement

#1951 [UXE-5716] feat: migrate edge application cache settings edit page to api v4
  cypress/e2e/edge-application/edit-cache-setting.cy.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-cache-settings-services/v4/edit-cache-settings-service.js
  src/services/edge-application-cache-settings-services/v4/index.js
  src/services/edge-application-cache-settings-services/v4/load-cache-settings-service.js
  src/tests/services/edge-application-cache-settings-services/v4/edit-cache-settings-service.test.js
  src/tests/services/edge-application-cache-settings-services/v4/load-cache-settings-service.test.js
Labels: api-v4-migration

#1913 [UXE-5600] feat: allow redirect when user is logged and enter public routes
  src/router/hooks/guards/accountGuard.js
Labels: enhancement

#1955 [UXE-5717] feat: migrate edge application cache settings deletion to api v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-cache-settings-services/v4/delete-cache-settings-service.js
  src/services/edge-application-cache-settings-services/v4/index.js
  src/tests/services/edge-application-cache-settings-services/v4/delete-cache-settings-service.test.js
Labels: api-v4-migration

#1959 [NO-ISSUE] fix: show error message when deleting Digital Certificates
  src/services/digital-certificates-services/v4/delete-digital-certificates-service.js
  src/services/edge-application-cache-settings-services/v4/index.js
  src/tests/services/digital-certificates-services/v4/delete-digital-certificates-service.test.js
Labels: bug

#1962 [UXE-5711] feat: migrate edge application device groups creation to api v4
  cypress/e2e/edge-application/create-device-groups.cy.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-device-groups-services/v4/create-device-groups-service.js
  src/services/edge-application-device-groups-services/v4/index.js
  src/tests/services/edge-application-device-groups-services/v4/create-device-groups-service.test.js
Labels: api-v4-migration

#1961 [UXE-5716] fix: send payload correctly when large file optimization is not enabled
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: bug

#1963 [UXE-5742] feat: migrated edge firewall edit page to api v4
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-services/v4/edit-edge-firewall-service.js
  src/services/edge-firewall-services/v4/index.js
  src/tests/services/edge-firewall-services/v4/edit-edge-firewall-service.test.js
Labels: unit-tests, api-v4-migration

#1967 [UXE-5712] feat: migrate edge application device groups edit page to api v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-device-groups-services/v4/edit-device-groups-service.js
  src/services/edge-application-device-groups-services/v4/index.js
  src/services/edge-application-device-groups-services/v4/load-device-group-service.js
  src/tests/services/edge-application-device-groups-services/v4/edit-device-groups-service.test.js
  src/tests/services/edge-application-device-groups-services/v4/load-device-group-service.test.js
Labels: api-v4-migration

#1970 [UXE-5742] feat: migrated edge firewall load to api v4
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-services/v4/index.js
  src/services/edge-firewall-services/v4/load-edge-firewall-service.js
  src/tests/services/edge-firewall-services/v4/load-edge-firewall-service.test.js
Labels: unit-tests, api-v4-migration

#1972 [UXE-5755] feat: migrated edge firewall create function to api v4
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-functions-services/v4/create-function-service.js
  src/services/edge-firewall-functions-services/v4/index.js
  src/tests/services/edge-firewall-functions-services/v4/create-edge-firewall-functions-service.test.js
Labels: api-v4-migration

#1965 [UXE-5743] feat: migrated edge firewall delete to api v4
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-services/v4/delete-edge-firewall-service.js
  src/services/edge-firewall-services/v4/index.js
  src/tests/services/edge-firewall-services/v4/clone-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/v4/create-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/v4/delete-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/v4/list-edge-firewall-service.test.js
  src/tests/services/edge-firewall-services/v4/make-edge-firewall-base-url.test.js
Labels: unit-tests, api-v4-migration

#1936 [UXE-5724] feat: lazy load Edge App/Edge Firewall on Add/Edit Domain screen
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/e2e/domains/create-domain-lets-encrypt.cy.js
  cypress/e2e/domains/create-domain-mtls.cy.js
  cypress/e2e/domains/edit-domain.cy.js
  cypress/e2e/purge/create-purge-domain.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/router/routes/domains-routes/index.js
  src/services/edge-application-services/v4/index.js
  src/services/edge-application-services/v4/load-edge-application-service.js
  src/services/edge-firewall-services/v4/index.js
  src/services/edge-firewall-services/v4/load-edge-firewall-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/tests/services/edge-application-services/v4/load-edge-application-service.test.js
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: do-not-merge, console-measurements

#1976 [UXE-5747] fix: layout clone modal for Edge App/Edge Firewall/WAF
  src/views/EdgeApplications/Dialog/Clone.vue
  src/views/EdgeFirewall/Dialog/Clone.vue
  src/views/WafRules/Dialog/Clone.vue
Labels: bug

#1971 [NO-ISSUE] fix: resolve pagination issue when sorting columns
  cypress/e2mock/edge-application/list-edge-applications.cy.js
  cypress/fixtures/edge-application/edge-applications-ordering-name.json
  cypress/fixtures/edge-application/edge-applications.json
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
Labels: bug, e2e tests

#1973 [UXE-5705] feat: migrate edge application delete to api v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-services/v4/delete-edge-application-service.js
  src/services/edge-application-services/v4/index.js
  src/tests/services/edge-application-services/v4/delete-edge-application-service.test.js
  src/tests/services/edge-firewall-services/v4/load-edge-firewall-service.test.js
Labels: api-v4-migration

#1945 [NO-ISSUE] chore: update project version to 1.30.0
  package.json
Labels: project version

#1977 [UXE-5810] feat: lazy load digital certificate in Add/Edit Domain screen
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/e2e/domains/create-domain-lets-encrypt.cy.js
  cypress/e2e/domains/create-domain-mtls.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/router/routes/domains-routes/index.js
  src/services/digital-certificates-services/list-digital-certificates-service.js
  src/services/digital-certificates-services/v4/index.js
  src/services/digital-certificates-services/v4/list-digital-certificates-dropdown-service.js
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/services/digital-certificates-services/v4/load-digital-certificates-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-dropdown-service.test.js
  src/tests/services/digital-certificates-services/v4/load-digital-certificates-service.test.js
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: console-measurements

#1966 [UXE-5745] fix: Edge DNS List View v3 to v4 migration
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-services/index.js
  src/services/edge-dns-services/make-edge-dns-base-url.js
  src/services/edge-dns-services/v4/list-edge-dns-service.js
  src/services/edge-dns-services/v4/make-edge-dns-base-url.js
  src/views/EdgeDNS/ListView.vue
Labels: api-v4-migration

#1943 fix: update signup layout for better alignment
  src/views/Signup/SignupView.vue
Labels: bug
