Repository aziontech/azion-console-kit, pull requests merged in 2024-08, with the labels that each got.

#1547 [UXE-4204] fix: waf tunning does not display attack logs
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/templates/list-table-block/index.vue
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
  src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#1559 [UXE-1872] feat: added middle mouse click in sidebar products
  src/templates/sidebar-block/index.vue
Labels: enhancement

#1568 [NO-ISSUE] docs: upgrade readme instructions to enable easy deploy for different environments
  README.md
  src/templates/empty-results-block/empty-edge-node.vue
  src/views/EdgeNode/ListView.vue
  src/views/Signup/SignupView.vue
Labels: documentation, code-refactor

#1552 [QA-2093] feat: activate sonarcloud on workflow
  .github/workflows/pre-merge.yml
  sonar-project.properties
Labels: enhancement

#1572 [UXE-4334] fix: renaming the recaptcha key for the stage environment and adding dynamic date in the test
  .github/workflows/deploy-stage.yml
  src/tests/services/billing-services/load-your-service-plan-service.test.js
Labels: bug, unit-tests, github-actions

#1577 [UXE-4348] feat: refined the query to handle billID and invoiceNumber with correct typing
  src/services/billing-services/list-service-and-products-changes.js
  src/services/billing-services/load-invoice-data-service.js
Labels: enhancement

#1574 [UXE-4335] fix: update rules engine list response phase after success creation
  src/tests/services/billing-services/load-your-service-plan-service.test.js
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: bug, unit-tests

#1580 [UXE-4014] feat: optimize guards with centralized folder and billing improvements
  src/helpers/get-static-urls-by-environment.js
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/router/hooks/guards/index.js
  src/router/hooks/guards/loadingGuard.js
  src/router/hooks/guards/logoutGuard.js
  src/router/hooks/guards/themeGuard.js
  src/router/routes/billing-routes/index.js
  src/stores/account.js
  src/templates/navbar-block/switch-account.vue
  src/templates/profile-block/index.vue
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/views/Home/HomeView.vue
Labels: enhancement, unit-tests, code-refactor

#1575 [UXE-4333] refactor: loading to edge application selector in domains
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: bug

#1579 [UXE-3366] fix: status code 400 when creating allowed rule by tuning
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
Labels: bug

#1578 [UXE-4039] fix: Unable edit to secret variables
  src/views/Variables/FormFields/FormFieldsVariables.vue
  src/views/Variables/ListView.vue
Labels: bug

#1581 [UXE-4369] feat: add formart currency and unit value in bill details
  src/helpers/convert-number.js
  src/helpers/index.js
  src/services/billing-services/list-payment-methods-service.js
  src/services/billing-services/list-service-and-products-changes.js
  src/services/billing-services/load-current-invoice-service.js
  src/services/billing-services/load-invoice-data-service.js
  src/services/billing-services/load-your-service-plan-service.js
  src/tests/helpers/convert-number.test.js
  src/tests/services/billing-services/list-service-and-products-changes.test.js
  src/tests/services/billing-services/load-your-service-plan-service.test.js
  src/views/Billing/InvoiceDetailsView.vue
  src/views/Billing/TabsView.vue
Labels: enhancement, code-refactor, e2e tests

#1576 [UXE-4002] refactor: organize edge application/rules engine drawer
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: code-refactor

#1585 [UXE-4427] feat: remove warning message about preview stage console
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
  src/templates/content-block/project-stage-message-block.vue
Labels: enhancement

#1586 [NO-ISSUE] chore: upgrade project version from 1.19.1 to 1.20.0
  package.json
Labels: project version

#1587 [NO-ISSUE] fix: redirect user to list when a secret is created
  src/services/variables-services/create-variables-service.js
Labels: bug

#1596 [UXE-4357] fix: added auth verification to page loaded track event
  src/router/hooks/afterEachRoute.js
Labels: bug

#1583 [UXE-4165] fix: double / from prefix field in Edge App Edge Storage Origins
  src/services/edge-application-origins-services/create-origin-service.js
  src/services/edge-application-origins-services/edit-origin-service.js
  src/tests/services/edge-application-origins-services/create-origin-service.test.js
  src/tests/services/edge-application-origins-services/edit-origin-service.test.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
Labels: bug

#1593 [UXE-3625] refactor: add h-[2.323rem] in px(37) in the advanced filter component
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/advanced-filter/index.vue
  src/views/RealTimeMetrics/blocks/interval-filter-block.vue
Labels: bug, code-refactor

#1594 [UXE-4208] feat: added autofocus on password and email input in login screen
  cypress/support/commands.js
  src/templates/sign-in-block/index.vue
Labels: enhancement

#1600 [UXE-4208] refactor: autofocus on password and email input in login screen
  src/templates/sign-in-block/index.vue
Labels: code-refactor

#1597 [UXE-4356] feat: add secrets segment variables in the workflows
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  src/plugins/AnalyticsTrackerAdapterPlugin.js
  src/plugins/analytics/AnalyticsTrackerAdapter.js
  src/plugins/factories/analytics-tracking-factory.js
  src/plugins/factories/segment-handler-token-factory.js
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/tests/plugins/factories/analytics-tracking-factory.test.js
  src/tests/plugins/factories/segment-handler-token-factory.test.js
Labels: enhancement

#1602 [NO-ISSUE] chore: updated version package json from 1.20.0 to 1.20.1
  package.json
Labels: project version

#1606 [UXE-4375] feat: add export to CSV support in list table block
  src/helpers/get-csv-cell-content-from-row-data.js
  src/helpers/index.js
  src/templates/list-table-block/index.vue
  src/tests/helpers/get-csv-cell-content-from-row-data.test.js
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
Labels: enhancement, unit-tests

#1608 [UXE-3366] fix: set cookie value to zone_input when the attack is a cookie
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
Labels: bug

#1603 [UXE-4473] fix: block users without permission of acessing team permissions edit page
  cypress/e2mock/teams-permissions.cy.js
  src/services/team-permission/load-team-permission-service.js
  src/templates/edit-form-block/index.vue
  src/tests/services/team-permission-services/load-team-permission-service.test.js
  src/views/TeamsPermissions/EditView.vue
Labels: bug, unit-tests, e2e tests

#1607 [UXE-4506] fix: change variables form inline message text
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: bug

#1590 [UXE-4291] fix: adjust load data in dropdown network list
  src/services/network-lists-services/list-network-list-service.js
  src/tests/services/network-lists-services/list-network-list-service.test.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug, do-not-merge

#1614 [NO-ISSUE] chore: updated version package json from 1.20.1 to 1.20.2
  package.json
Labels: project version

#1612 DEPLOY 2024.08.14
  cypress/e2mock/teams-permissions.cy.js
  package.json
  src/App.vue
  src/helpers/get-csv-cell-content-from-row-data.js
  src/helpers/index.js
  src/helpers/theme-select.js
  src/services/network-lists-services/list-network-list-service.js
  src/services/team-permission/load-team-permission-service.js
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/templates/edit-form-block/index.vue
  src/templates/list-table-block/index.vue
  src/tests/helpers/get-csv-cell-content-from-row-data.test.js
  src/tests/helpers/themeSelect.test.js
  src/tests/services/network-lists-services/list-network-list-service.test.js
  src/tests/services/team-permission-services/load-team-permission-service.test.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
  src/views/RealTimeMetrics/RealTimeMetricsView.vue
  src/views/TeamsPermissions/EditView.vue
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: DEPLOY

#1609 [UXE-4503] fix: remove digital certificate column from domains list view
  src/views/Domains/ListView.vue
Labels: bug

#1611 [UXE-4484] fix: list items that do not have hover behavior
  src/templates/list-table-block/index.vue
Labels: bug, do-not-merge

#1610 [UXE-4371] feat: add filter advanced in view realTime Events
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/list-table-block/index.vue
  src/views/RealTimeEvents/TabsView.vue
  src/views/RealTimeEvents/blocks/content-filter-block.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
Labels: enhancement, code-refactor

#1619 [UXE-4291] fix: convert the argument type from criteria to string on the edge firewall rules engine
  src/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.js
  src/tests/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.test.js
Labels: bug

#1620 [UXE-4484] feat: upgrade azion theme to 1.5.6 version
  package.json
  yarn.lock
Labels: enhancement

#1618 [UXE-4471] fix: block page loaded event tracker when change route is blocked
  src/router/hooks/afterEachRoute.js
Labels: bug

#1617 [NO-ISSUE] test: add dev2 tag to team permissions e2mock spec
  cypress/e2mock/teams-permissions.cy.js
Labels: e2e tests

#1622 [UXE-4473] fix: change error message parser to dont get error key
  src/services/team-permission/load-team-permission-service.js
  src/tests/services/team-permission-services/load-team-permission-service.test.js
Labels: bug, unit-tests

#1621 [UXE-4543] fix: show response when deleting a digital certificate thats being used
  src/services/digital-certificates-services/delete-digital-certificates-service.js
  src/tests/services/digital-certificates-services/delete-digital-certificates-service.test.js
Labels: code-refactor

#1624 [NO-ISSUE] feat: use AzionConfig types
  .eslintrc.cjs
  azion.config.ts
  jsconfig.json
  package.json
  yarn.lock
Labels: documentation, enhancement

#1623 [UXE-4372] feat: applied advanced filter query to view realtime events
  src/helpers/convert-gql.js
  src/helpers/hash-route.js
  src/helpers/index.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/load-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/templates/advanced-filter/advanced-filter-no-hash.vue
  src/templates/list-table-block/index.vue
  src/tests/helpers/convert-gql.test.js
  src/tests/helpers/hash-route.test.js
  src/views/RealTimeEvents/TabsView.vue
  src/views/RealTimeEvents/blocks/content-filter-block.vue
  src/views/RealTimeEvents/blocks/interval-filter-block.vue
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
Labels: enhancement, unit-tests

#1625 [UXE-4533] refactor: added loading conditional to trusted CA fields in domains screen
  src/views/Domains/CreateView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
Labels: code-refactor

#1630 [NO-ISSUE] test: fix expected error message in team permissions spec assertion
  cypress/e2mock/teams-permissions.cy.js
Labels: bug, e2e tests

#1629 [NO-ISSUE] feat: revert use AzionConfig types
  .eslintrc.cjs
  azion.config.cjs
  jsconfig.json
  package.json
  yarn.lock
Labels: bug

#1633 [UXE-4373] feat: graphql playground events with filters and fields
  src/helpers/events-playground-opener.js
  src/helpers/get-static-urls-by-environment.js
  src/helpers/index.js
  src/helpers/open-graphql-playground.js
  src/router/routes/real-time-events-routes/index.js
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/stores/graphql-query.js
  src/tests/helpers/events-playground-opener.test.js
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/tests/services/digital-certificates-services/delete-digital-certificates-service.test.js
  src/tests/setup-tests.js
  src/views/RealTimeEvents/blocks/content-filter-block.vue
  vitest.config.js
Labels: enhancement, unit-tests

#1631 [UXE-3308] feat: add accordion to edge application rules engine criterias
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: enhancement

#1632 [UXE-4458] fix: reworked the behavior logic on the rule engine screen in edge app
  src/services/edge-application-rules-engine-services/create-rules-engine-service.js
  src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
  src/services/edge-application-rules-engine-services/helper-behavior.js
  src/services/edge-application-rules-engine-services/load-rules-engine-service.js
  src/tests/services/edge-application-rules-engine-services/create-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/helper-behavior.test.js
  src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1598 [UXE-3672] feat: add azion ask to console as module
  package.json
  src/assets/svg/ai-ask-azion.vue
  src/main.js
  src/modules/azion-ai-chat/assets/azion-logo.svg
  src/modules/azion-ai-chat/assets/intro-message-logo.svg
  src/modules/azion-ai-chat/assets/suggestion-icon-metrics.svg
  src/modules/azion-ai-chat/assets/suggestion-icon-security.svg
  src/modules/azion-ai-chat/azion-ai-chat-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-full-size-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-header-block.vue
  src/modules/azion-ai-chat/azion-ai-chat-suggestion.vue
  src/modules/azion-ai-chat/azion-ai-get-help.vue
  src/modules/azion-ai-chat/contextual-prompts/domains/index.js
  src/modules/azion-ai-chat/contextual-prompts/index.js
  src/modules/azion-ai-chat/directives/custom-ai-prompt.js
  src/modules/azion-ai-chat/index.vue
  src/modules/azion-ai-chat/services/load-prompt-suggestions.js
  src/modules/azion-ai-chat/services/make-azion-ai-base-url.js
  src/modules/azion-ai-chat/services/make-request-config.js
  src/modules/azion-ai-chat/services/make-session-id.js
  src/modules/azion-ai-chat/services/request-interceptor-service.js
  src/modules/azion-ai-chat/tests/load-prompt-suggestions.test.js
  src/modules/azion-ai-chat/tests/make-azion-ai-base-url.test.js
  src/modules/azion-ai-chat/tests/make-request-config.test.js
  src/modules/azion-ai-chat/tests/make-session-id.test.js
  src/modules/azion-ai-chat/tests/requestInterceptorService.test.js
  src/router/index.js
  src/router/routes/azion-ai-routes/index.js
  src/stores/azion-ai-chat-store.js
  src/templates/create-form-block/form-horizontal.vue
  src/templates/navbar-block/ai-chat-button.vue
  src/templates/navbar-block/help.vue
  src/templates/navbar-block/index.vue
  src/templates/page-heading-block/index.vue
  src/templates/shell-block/index.vue
  src/views/Copilot/CopilotView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  yarn.lock
Labels: enhancement, do-not-merge, unit-tests, WIP

#1641 [UXE-4638] feat: remove beta tag from lets encrypt
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: enhancement

#1626 [UXE-4507] refactor: adjust label in link - Create>Recommended
  src/templates/create-modal-block/index.vue
Labels: writing, waiting-for-uxe-to-merge

#1634 [UXE-4558] feat: remove credentials views, services, tests, routes and redirectors
  cypress/e2e/credentials/create-credentials.cy.js
  cypress/support/selectors.js
  cypress/support/selectors/view-selectors/credentials.js
  src/helpers/azion-documentation-catalog.js
  src/router/index.js
  src/router/routes/credentials-routes/index.js
  src/services/credential-services/create-credential-service.js
  src/services/credential-services/delete-credential-service.js
  src/services/credential-services/edit-credential-service.js
  src/services/credential-services/index.js
  src/services/credential-services/list-credentials-service.js
  src/services/credential-services/load-credential-service.js
  src/services/credential-services/make-credentials-base-url.js
  src/templates/navbar-block/switch-account.vue
  src/templates/profile-block/index.vue
  src/tests/helpers/azion-documentation-catalog.test.js
  src/tests/services/credentials-services/create-credential-service.test.js
  src/tests/services/credentials-services/delete-credential-service.test.js
  src/tests/services/credentials-services/edit-credential-service.test.js
  src/tests/services/credentials-services/list-credentials-service.test.js
  src/tests/services/credentials-services/load-credential-service.test.js
  src/views/Credentials/CreateView.vue
  src/views/Credentials/EditView.vue
  src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
  src/views/Credentials/FormFields/FormFieldsEditCredentials.vue
  src/views/Credentials/ListView.vue
Labels: enhancement

#1643 [NO-ISSUE] feat: Access Restrictions by IP
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  azion.config.cjs
Labels: enhancement, IAC

#1646 [NO-ISSUE] chore: manual sync with stage
  azion/stage/azion.json
Labels: IAC

#1636 [QA-2122] ci: add eslint plugins security, xss and no-unsanitized
  .eslintrc-security.cjs
  .github/workflows/package-audit.yaml
  .github/workflows/security-linter.yaml
  package.json
  yarn.lock
Labels: enhancement

#1648 [NO-ISSUE] fix: open accordion when there is error in fields inside it
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1650 [NO-ISSUE] feat: add map and ordered bar chart
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/constants/chart-rules.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/load-report-with-meta.js
  src/modules/real-time-metrics/reports/resolve-reports.js
  src/templates/graphs-card-block/components/chart/bar-chart.vue
  src/templates/graphs-card-block/components/chart/line-chart.vue
  src/templates/graphs-card-block/components/chart/ordered-bar-chart.vue
  src/templates/graphs-card-block/components/chart/spline-chart.vue
  src/templates/graphs-card-block/components/map/constants/color-scheme.js
  src/templates/graphs-card-block/components/map/json/countries.json
  src/templates/graphs-card-block/components/map/json/lakes.json
  src/templates/graphs-card-block/components/map/json/ocean.json
  src/templates/graphs-card-block/components/map/json/regions.json
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-legend-block.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-block.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/bubbles-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart-blocks/map-tooltip-contents/heatmap-tooltip.vue
  src/templates/graphs-card-block/components/map/map-chart.vue
  src/templates/graphs-card-block/components/map/utils/common-features-handler.js
  src/templates/graphs-card-block/components/map/utils/features-handler.js
  src/templates/graphs-card-block/components/map/utils/features-styler.js
  src/templates/graphs-card-block/index.vue
  src/tests/modules/real-time-metrics/chart/chart-fixtures.js
  src/tests/modules/real-time-metrics/chart/format-c3-graph-props.test.js
  src/tests/modules/real-time-metrics/constants/chart-rules.test.js
  src/views/Playground/PlaygroundView.vue
  src/views/Playground/charts/AreaChart.vue
  src/views/Playground/charts/BarChart.vue
  src/views/Playground/charts/BigNumbersChart.vue
  src/views/Playground/charts/DonutChart.vue
  src/views/Playground/charts/PieChart.vue
  src/views/Playground/charts/RotatedBarChart.vue
  src/views/Playground/mocks_data.js
Labels: enhancement

#1653 [QA-2169] test: add fail-fast in workflow
  .github/workflows/dev-e2e-tests.yml
Labels: e2e tests

#1647 [UXE-4527] feat: add redirectGuard in beforeEachRouter for login
  src/helpers/index.js
  src/helpers/login-redirect-manager.js
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/index.js
  src/router/hooks/guards/redirectGuard.js
  src/tests/helpers/hash-route.test.js
  src/tests/helpers/login-redirect-manager.test.js
Labels: enhancement, unit-tests

#1651 [NO-ISSUE] feat: update label for GraphQL Playground button in RealTimeEvents and RealTimeMetrics
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
  src/views/RealTimeMetrics/blocks/content-filter-block.vue
Labels: enhancement

#1652 [UXE-4589] fix: remove column domains in table edge firewall list
  src/services/edge-firewall-services/list-edge-firewall-service.js
  src/tests/services/edge-firewall-services/list-edge-firewall-service.test.js
  src/views/EdgeFirewall/ListView.vue
Labels: bug, unit-tests
