Repository aziontech/azion-console-kit, pull requests merged in 2024-01, with the labels that each got.

#523 [ENG-28869 feat: implementing access control to the menu
  src/templates/sidebar-block/index.vue
Labels: enhancement

#524 [ENG-28869] fix: adjustments to the drawer edge application origins
  src/assets/themes/scss/themes/azion-dark/extended-components/_divider.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_divider.scss
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: code-refactor

#526 [ENG-28869] feat: add props in component field textarea
  src/templates/form-fields-inputs/fieldTextArea.vue
Labels: enhancement

#528 [ENG-28869] fix: adjusted table delete dialog
  src/services/edge-application-origins-services/delete-origin-service.js
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/tests/services/edge-application-origins-services/delete-origin-service.test.js
Labels: unit-tests, code-refactor

#529 [ENG-28869] fix: bug fix on empty component border
  src/templates/empty-results-block/index.vue
  src/templates/list-table-block/no-header.vue
Labels: bug

#531 [UXE-1524] Apply overflow-auto for Create Dialog
  src/templates/create-modal-block/index.vue
  src/templates/navbar-block/create.vue
Labels: enhancement, theming

#530 [ENG-28869] fix: adjusted import tag in sidebar block
  src/templates/sidebar-block/index.vue
Labels: bug

#533 DEPLOY 2024.05.01
  package.json
  src/assets/icons/azionicons.scss
  src/assets/themes/scss/themes/azion-dark/extended-components/_divider.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_divider.scss
  src/helpers/get-array-changed-indexes.js
  src/services/edge-application-origins-services/delete-origin-service.js
  src/services/edge-application-rules-engine-services/delete-rules-engine-service.js
  src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
  src/templates/create-modal-block/index.vue
  src/templates/empty-results-block/index.vue
  src/templates/footer-block/index.vue
  src/templates/form-fields-inputs/fieldTextArea.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/list-table-block/no-header.vue
  src/templates/navbar-block/create.vue
  src/templates/sidebar-block/index.vue
  src/tests/helpers/get-array-changed-indexes.test.js
  src/tests/helpers/get-first-api-error.test.js
  src/tests/services/edge-application-origins-services/delete-origin-service.test.js
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: DEPLOY

#536 [ENG-28752] refactor: adjusted ui table in edge firewall
  src/services/edge-firewall-services/list-edge-firewall-service.js
  src/tests/services/edge-firewall-services/list-edge-firewall-service.test.js
  src/views/EdgeFirewall/ListView.vue
Labels: enhancement, unit-tests

#535 [EDU-3838] refactor: uxw adjust preview banner text
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
Labels: writing

#527 [ENG-28869] fix: adjusted labels and value default in drawer
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: enhancement, code-refactor

#537 [ENG-28072] feat: display social idps in signup and login views
  src/router/routes/login-routes/index.js
  src/router/routes/signup-routes/index.js
  src/services/social-idps-services/index.js
  src/services/social-idps-services/list-social-idps-service.js
  src/services/social-idps-services/make-list-social-idps-base-url.js
  src/templates/sign-in-block/index.vue
  src/templates/signup-block/social-signup-block.vue
  src/templates/social-idps-block/index.vue
  src/tests/services/social-idps-services/list-social-idps-service.test.js
  src/views/Login/LoginView.vue
  src/views/Signup/SignupView.vue
Labels: enhancement, unit-tests, code-refactor

#540 [ENG-28093] feat: add unit tests to cache settings services
  src/services/edge-application-cache-settings-services/create-cache-settings-service.js
  src/services/edge-application-cache-settings-services/delete-cache-settings-service.js
  src/services/edge-application-cache-settings-services/edit-cache-settings-service.js
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
  src/tests/services/edge-application-cache-settings-services/create-cache-settings-service.test.js
  src/tests/services/edge-application-cache-settings-services/delete-cache-settings-service.test.js
  src/tests/services/edge-application-cache-settings-services/edit-cache-settings-service.test.js
  src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
  vitest.config.js
Labels: unit-tests, code-refactor

#541 [ENG-28892] feat: add loading state on route change
  src/router/hooks/afterEachRoute.js
  src/router/hooks/beforeEachRoute.js
  src/router/index.js
  src/router/routes/cli-callback-routes/index.js
  src/router/routes/login-routes/index.js
  src/router/routes/signup-routes/index.js
  src/templates/loading-block/index.vue
  src/templates/main-menu-block/index.vue
  src/templates/navbar-block/index.vue
  src/templates/shell-block/index.vue
  src/templates/sign-in-block/index.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
Labels: bug, enhancement, code-refactor

#542 [ENG-28094] test: add cache settings unit tests to load service
  src/services/edge-application-cache-settings-services/list-cache-settings-service.js
  src/tests/services/edge-application-cache-settings-services/list-cache-settings-service.test.js
  src/tests/services/edge-application-cache-settings-services/load-cache-settings-service.test.js
  vitest.config.js
Labels: unit-tests

#538 [ENG-28276] feat: block editing edge functions that are from the marketplace
  src/services/edge-functions-services/load-edge-functions-service.js
  src/tests/services/edge-functions-services/load-edge-functions-service.test.js
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
  src/views/EdgeFunctions/components/code-editor.vue
Labels: enhancement

#547 [UXE-1217] style: include truncated text
  src/templates/switch-account-block/index.vue
Labels: theming

#534 [UXE-1175] theme ajuste em pick list
  src/assets/themes/scss/themes/azion-dark/_extensions.scss
  src/assets/themes/scss/themes/azion-dark/extended-components/_picklist.scss
  src/assets/themes/scss/themes/azion-light/_extensions.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_picklist.scss
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
Labels: theming

#545 [ENG-28718] feat: empty list improvements
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
  src/templates/switch-account-block/index.vue
  src/views/Credentials/ListView.vue
  src/views/DataStreaming/ListView.vue
  src/views/DigitalCertificates/ListView.vue
  src/views/Domains/ListView.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFunctions/ListView.vue
  src/views/EdgeNode/ListView.vue
  src/views/EdgeNode/ListViewTabServices.vue
  src/views/EdgeServices/ListView.vue
  src/views/EdgeServices/ListViewTabResources.vue
  src/views/IntelligentDNS/EditView.vue
  src/views/IntelligentDNS/ListView.vue
  src/views/NetworkLists/ListView.vue
  src/views/PersonalTokens/ListView.vue
  src/views/RealTimePurge/ListView.vue
  src/views/TeamsPermissions/ListView.vue
  src/views/Users/ListView.vue
  src/views/Variables/ListView.vue
Labels: enhancement, code-refactor

#548 [ENG-28073] feat: add console query string to url
  src/services/social-idps-services/list-social-idps-service.js
  src/templates/social-idps-block/index.vue
  src/tests/services/social-idps-services/list-social-idps-service.test.js
Labels: enhancement, unit-tests

#550 [ENG-28919] feat: create waf rules
  src/assets/themes/scss/themes/azion-dark/extended-components/_picklist.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_picklist.scss
  src/router/routes/waf-rules-routes/index.js
  src/services/waf-rules-services/create-waf-rules-service.js
  src/services/waf-rules-services/index.js
  src/services/waf-rules-services/list-waf-rules-service.js
  src/tests/services/waf-rules-services/create-waf-rules-service.test.js
  src/views/WafRules/CreateView.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
Labels: enhancement

#546 [EDU-3781] refactor: uxw digital certificates
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: writing

#556 [NO-ISSUE] change z-index on extensions
  src/assets/themes/scss/themes/azion-dark/extended-components/_divider.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_divider.scss
Labels: theming

#558 [ENG-28888]fix: remove loose close tag from code and orientation text on FormFieldsYourSettings
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: bug

#557 [NO-ISSUE] chore: update license model
  LICENSE
  src/services/edge-application-error-responses-services/list-error-responses-service.js
Labels: documentation

#561 [ENG-28965] feat: add switch-account route to handle login from social idp
  src/helpers/index.js
  src/helpers/switch-account-from-social-idp.js
  src/router/index.js
  src/router/routes/switch-account-routes/index.js
Labels: bug, enhancement

#565 [ENG-28965] test: add tests for switchAccountFromSocialIdp
  src/helpers/account-handler.js
  src/tests/helpers/account-handler.test.js
Labels: bug, unit-tests, code-refactor

#566 [NO-ISSUE] fix: signup button showing on additional data
  src/templates/signup-block/page-with-form-block.vue
  src/views/Signup/AdditionalDataView.vue
Labels: bug

#567 [ENG-27546] refactor: remove placeholder in input
  src/services/edge-application-error-responses-services/edit-error-responses-service.js
  src/tests/services/edge-application-functions-services/list-functions-service.test.js
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: code-refactor

#569 [EDU-3781] chore: change mapper of digital certificates list to use TLS name
  src/services/digital-certificates-services/list-digital-certificates-service.js
  src/tests/services/digital-certificates-services/list-digital-certificates-service.test.js
Labels: unit-tests, writing

#571 [ENG-28888] fix: template validation on create new journey
  src/templates/create-modal-block/LoadingListTemplate.vue
  src/templates/create-modal-block/index.vue
  src/templates/template-engine-block/FormLoading.vue
  src/templates/template-engine-block/index.vue
  src/views/CreateNew/CreateView.vue
  src/views/Marketplace/components/ListSolutions.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
Labels: bug

#574 [UXE-1578] styles: Remove pt of Delete Modal
  src/templates/list-table-block/dialog/delete-dialog.vue
Labels: theming

#576 [ENG-28979] fix: texts at switch account modal
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/navbar-block/switch-account.vue
  src/tests/services/metrics-services/search-domains-metrics-service.test.js
Labels: bug

#577 [ENG-28979] refactor: improve code readability with eslint variable name rule
  .eslintrc.cjs
  src/helpers/parse-api-body.js
  src/router/hooks/beforeEachRoute.js
  src/router/routes/signup-routes/index.js
  src/router/routes/switch-account-routes/index.js
  src/services/users-services/list-users-service.js
  src/templates/mfa-authenticate-block/index.vue
  src/templates/mfa-setup-block/index.vue
  src/templates/search-block/index.vue
  src/templates/template-engine-block/index.vue
  src/templates/toast-block/index.vue
  src/tests/services/credentials-services/list-credentials-service.test.js
  src/tests/services/edge-application-services/list-edge-applications-service.test.js
  src/tests/services/edge-functions-services/list-edge-functions-service.test.js
  src/tests/services/edge-node-service-services/list-service-edge-node-service.test.js
  src/tests/services/edge-service-resources-services/list-resources-services.test.js
  src/tests/services/edge-service-services/list-edge-service-services.test.js
  src/tests/services/personal-tokens-services/list-personal-tokens-service.test.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
  src/tests/utils/localeMock.js
  src/views/IntelligentDNS/EditView.vue
  src/views/Marketplace/MarketplaceHomeView.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: code-refactor

#587 [NO-ISSUE] tests: add rules engine unit tests
  src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
  src/services/edge-application-rules-engine-services/load-rules-engine-service.js
  src/services/edge-application-services/make-edge-application-base-url.js
  src/templates/create-modal-block/index.vue
  src/tests/services/edge-application-rules-engine-services/create-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/delete-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js
  src/tests/services/edge-firewall-functions-services/list-functions-service.test.js
  src/views/EdgeFirewall/TabsView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
Labels: unit-tests

#589 [NO-ISSUE] fix: adjust required in ui validation
  src/services/edge-application-functions-services/list-edge-application-functions-service.js
  src/tests/services/edge-application-functions-services/list-edge-application-functions-service.test.js
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: bug, code-refactor

#598 [NO-ISSUE] style: include padding-inline
  src/assets/themes/scss/themes/azion-dark/extended-components/_selectbutton.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_selectbutton.scss
  src/templates/create-modal-block/index.vue
Labels: theming

#600 [ENG-28993] feat: add new image to empty state
  src/assets/illustration-min.png
  src/assets/svg/empty.svg
  src/assets/svg/illustration-layers.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
Labels: enhancement

#607 [EDU-3886] chore: review cli callback uxw
  src/views/CliCallback/FailView.vue
  src/views/CliCallback/SuccessView.vue
Labels: writing

#608 [EDU-3886] chore: resource path placeholder uxw
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
Labels: writing

#619 [ENG-28461] feat: add name edge application to list domains
  src/services/domains-services/list-domains-service.js
  src/tests/services/domains-services/list-domains-service.test.js
Labels: enhancement, unit-tests

#618 [NO-ISSUE] feat: add edge function descriptions
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: writing

#633 DEPLOY 2024.01.24
  package.json
  src/router/routes/users-routes/index.js
  src/services/edge-application-functions-services/loader-function-service.js
  src/services/edge-firewall-functions-services/loader-function-service.js
  src/services/edge-service-resources-services/make-resources-base-url.js
  src/services/users-services/create-users-service.js
  src/services/users-services/edit-another-user-service.js
  src/services/users-services/index.js
  src/services/users-services/load-another-user-service.js
  src/templates/create-form-block/index.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/tests/services/edge-application-functions-services/load-function-service.test.js
  src/tests/services/edge-firewall-functions-services/load-function-service.test.js
  src/tests/services/edge-service-resources-services/create-resources-services.test.js
  src/tests/services/edge-service-resources-services/delete-resources-services.test.js
  src/tests/services/edge-service-resources-services/edit-resources-services.test.js
  src/tests/services/edge-service-resources-services/list-resources-services.test.js
  src/tests/services/edge-service-resources-services/load-resources-services.test.js
  src/tests/services/edge-service-resources-services/make-resources-base-url.test.js
  src/tests/services/users-services/create-users-service.test.js
  src/tests/services/users-services/edit-user-service.test.js
  src/tests/services/users-services/load-another-user-service.test.js
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewall/TabsView.vue
  src/views/Users/CreateView.vue
  src/views/Users/EditView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: DEPLOY

#638 [ENG-28754][ENG-28002] feat: implement reports data and services
  src/helpers/convert-date.js
  src/services/metrics-services/constants/dashboards-texts.js
  src/services/metrics-services/constants/reports.js
  src/services/metrics-services/index.js
  src/services/metrics-services/make-intelligent-dns-base-url.js
  src/services/metrics-services/search-domains-metrics-service.js
  src/services/metrics-services/search-domains-service.js
  src/services/metrics-services/search-idns-service.js
  src/stores/account.js
  src/stores/metrics-store/actions/load-report-with-meta.js
  src/templates/graphs-card-block/components/aggregation-info.vue
  src/templates/graphs-card-block/components/chart-owner.vue
  src/templates/graphs-card-block/components/more-options-menu.vue
  src/templates/graphs-card-block/index.vue
  src/views/Metrics/MetricsView.vue
  src/views/Metrics/blocks/dashboard-panel-block.vue
Labels: enhancement, code-refactor

#642 [N0-ISSUE] feat: connect store to detetime filter in metrics
  src/views/Metrics/blocks/interval-filter-block.vue
Labels: enhancement, code-refactor

#640 [NO-ISSUE] chore: review digital certificates v2
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: writing

#646 [ENG-29228] feat: implement report services
  src/services/metrics-services/fetch-metrics-data-from-beholder.js
  src/stores/metrics-store/actions/load-dataset-available-filters.js
  src/stores/metrics-store/actions/load-report-with-meta.js
  src/stores/metrics-store/actions/load-reports-data-by-selected-dashboard.js
  src/stores/metrics.js
  src/views/Metrics/MetricsView.vue
  src/views/Metrics/blocks/dashboard-panel-block.vue
  src/views/Metrics/blocks/interval-filter-block.vue
  src/views/Metrics/blocks/tabs-page-block.vue
Labels: bug, enhancement

#648 [ENG-29231] feat: display report chart
  src/assets/c3.scss
  src/main.js
  src/views/Metrics/blocks/dashboard-panel-block.vue
  src/views/Metrics/components/chart/bar-chart/bar-chart.vue
  src/views/Metrics/components/chart/line-chart/line-chart.vue
  src/views/Metrics/components/chart/spline-chart/spline-chart.vue
Labels: enhancement, code-refactor

#649 [NO-ISSUE] fix: [main] revert imports sort
  src/main.js
Labels: bug
