Repository aziontech/azion-console-kit, pull requests merged in 2024-07, with the labels that each got.

#1396 chore: upgrade project version from 1.16.3 to 1.17.0
  package.json
Labels: project version

#1368 [UXE-3793] test: e2e personal tokens crud
  cypress/e2e/personal-token.cy.js
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
  src/views/PersonalTokens/Dialog/CopyTokenDialog.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
Labels: e2e tests

#1392 [QA-2038] test: add Edge Firewall E2E test
  cypress/e2e/edge-firewall.cy.js
  cypress/support/selectors.js
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: e2e tests

#1379 [UXE-3247] test: e2e edge services crud
  cypress/e2e/edge-services.cy.js
  src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
Labels: e2e tests

#1395 [NO-ISSUE] fix: adjusting e2e tests to default
  cypress/e2e/credentials.cy.js
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/network-lists.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/variables.cy.js
  cypress/e2e/waf.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
Labels: e2e tests

#1340 [NO-ISSUE] test: add functions E2E test
  cypress/e2e/functions.cy.js
  cypress/support/selectors.js
Labels: e2e tests

#1385 [UXE-3780] test: e2e edge pulse copy
  cypress/e2e/edge-pulse.cy.js
  cypress/support/commands.js
  package.json
  src/views/EdgePulse/FormFields/FormFieldsDefault.vue
  src/views/EdgePulse/FormFields/FormFieldsTag.vue
  src/views/EdgePulse/ListView.vue
  yarn.lock
Labels: e2e tests

#1391 [EDU-4780] chore: review toasts
  cypress/e2e/credentials.cy.js
  cypress/e2e/edge-pulse.cy.js
  cypress/e2e/personal-token.cy.js
  src/templates/advanced-filter/component/fields/multiselect-filter.vue
  src/templates/advanced-filter/index.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/sign-in-block/index.vue
  src/views/CreateNew/DeployView.vue
  src/views/Credentials/CreateView.vue
  src/views/Credentials/EditView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
  src/views/Domains/CreateView.vue
  src/views/Domains/EditView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeDNS/CreateView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeNode/Dialog/Authorize.vue
  src/views/EdgePulse/ListView.vue
  src/views/EdgeServices/TabsView.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/PersonalTokens/CreateView.vue
  src/views/Users/EditView.vue
  src/views/WafRules/TabsView.vue
Labels: writing

#1400 [NO-ISSUE] chore: upload e2e coverage html report
  .github/workflows/e2e-tests.yml
Labels: e2e tests

#1399 [NO-ISSUE] chore: changed border color
  src/assets/themes/scss/themes/azion-dark/_variables.scss
  src/assets/themes/scss/themes/azion-light/_variables.scss
Labels: theming

#1383 [UXE-3787] test: e2e account settings crud
  cypress/e2e/account-settings.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: e2e tests

#1403 [UXE-3779] test: create e2e test for data stream
  cypress/e2e/data-stream.cy.js
  cypress/e2e/users-management.cy.js
  cypress/e2e/your-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/support/selectors.js
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/form-fields-inputs/fieldNumber.vue
  src/templates/form-fields-inputs/fieldSwitchBlock.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: e2e tests

#1405 [UXE-3769] refactor: add button to action column in table component
  src/templates/list-table-block/action-column.vue
  src/templates/list-table-block/dialog/delete-dialog-new.vue
Labels: code-refactor

#1404 [UXE-2762] feat: add payments tab and list payment methods
  src/helpers/azion-documentation-catalog.js
  src/router/index.js
  src/router/routes/billing-routes/index.js
  src/services/billing-services/delete-payment-service.js
  src/services/billing-services/index.js
  src/services/billing-services/list-payment-service.js
  src/services/billing-services/make-payment-base-url.js
  src/services/billing-services/set-as-default-payment-service.js
  src/templates/list-table-block/columns/column-builder.js
  src/templates/list-table-block/columns/credit-card-column.vue
  src/templates/list-table-block/columns/credit-expiration-column.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/templates/page-heading-block/index.vue
  src/tests/services/billing-services/delete-payment-service.test.js
  src/tests/services/billing-services/list-payment-service.test.js
  src/tests/services/billing-services/make-payment-base-url.test.js
  src/tests/services/billing-services/set-as-default-payment-service.test.js
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
Labels: enhancement

#1408 [UXE-3706] feat: added a new style and required label to all mandatory fields.
  cypress/e2mock/your-settings.cy.js
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/form-fields-inputs/fieldNumber.vue
  src/templates/form-fields-inputs/fieldText.vue
  src/templates/form-fields-inputs/fieldTextArea.vue
  src/templates/label-block/index.vue
  src/templates/profile-block/index.vue
  src/templates/template-engine-block/index.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/Credentials/FormFields/FormFieldsCreateCredentials.vue
  src/views/Credentials/FormFields/FormFieldsEditCredentials.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsDeviceGroups/FormFields/FormFieldsEdgeApplicationsDeviceGroups.vue
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
  src/views/EdgeNode/FormFields/FormFieldsDrawerService.vue
  src/views/EdgeNode/FormFields/FormFieldsEdgeNode.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
  src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
  src/views/Home/FormFields/FormFieldsHome.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
  src/views/PersonalTokens/FormFields/FormFieldsPersonalToken.vue
  src/views/Playground/PlaygroundView.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/Variables/FormFields/FormFieldsVariables.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: enhancement

#1406 [NO-ISSUE] chore: remove lcov-report folder before upload e2e artifacts
  .github/workflows/e2e-tests.yml
Labels: e2e tests

#1407 [NO-ISSUE] chore: remove yarn ci to speedup e2e workflow
  .github/workflows/e2e-tests.yml
Labels: e2e tests

#1393 [QA-2040] test: add Edge DNS Zone E2E test
  cypress/e2e/edge-dns.cy.js
  cypress/support/selectors.js
  src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
Labels: e2e tests

#1402 [NO-ISSUE] fix: cache varies by query string
  azion.config.cjs
Labels: bug

#1411 [NO-ISSUE] chore: zip coverage folder before upload
  .github/workflows/e2e-tests.yml
Labels: e2e tests

#1412 [UXE-3769] refactor: add action button to credentials
  cypress/e2e/credentials.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  src/templates/list-table-block/action-column.vue
  src/templates/list-table-block/dialog/delete-dialog-new.vue
  src/views/Credentials/ListView.vue
Labels: bug, code-refactor, e2e tests

#1414 [NO-ISSUE] fix: workflow CLA to run on latest ubuntu version with latest CLA assistant version
  .github/workflows/cla.yml
Labels: bug

#1410 [UXE-3941] test: create e2e test for new selectors in data stream
  cypress/e2e/data-stream.cy.js
  cypress/support/selectors.js
  src/services/data-stream-services/create-data-stream-service.js
  src/services/data-stream-services/edit-data-stream-service.js
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug, e2e tests

#1409 [QA-2042] feat: adding configurations for dynamic environments in cypress
  .github/workflows/e2e-tests.yml
  cypress.config.js
  cypress.config.preview-prod.js
  cypress.config.prod.js
  cypress.env.example.json
  cypress/e2e/account-settings.cy.js
  cypress/e2e/credentials.cy.js
  cypress/support/commands.js
  package.json
Labels: e2e tests

#1413 [UXE-3775] test: e2e domains main crud
  cypress.config.js
  cypress/e2e/account-settings.cy.js
  cypress/e2e/credentials.cy.js
  cypress/e2e/data-stream.cy.js
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/domains.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/edge-dns.cy.js
  cypress/e2e/edge-firewall.cy.js
  cypress/e2e/edge-pulse.cy.js
  cypress/e2e/edge-services.cy.js
  cypress/e2e/functions.cy.js
  cypress/e2e/network-lists.cy.js
  cypress/e2e/personal-token.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/users-management.cy.js
  cypress/e2e/variables.cy.js
  cypress/e2e/waf.cy.js
  cypress/e2e/your-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  cypress/support/utils.js
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/views/Domains/Dialog/CopyDomainDialog.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
Labels: e2e tests

#1417 [UXE-3966] fix: adjusted method edit in edge firewall
  src/views/EdgeFirewall/EditView.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFirewall/TabsView.vue
Labels: bug

#1415 [NO-ISSUE] docs: update README.md
  README.md
Labels: documentation

#1416 [UXE-2762] refactor: add search and sort in the payment list
  src/helpers/convert-date.js
  src/helpers/payment-method.js
  src/services/billing-services/list-payment-service.js
  src/tests/helpers/convert-date.test.js
  src/tests/helpers/payment-method.test.js
  src/tests/services/billing-services/list-payment-service.test.js
  src/views/Billing/PaymentListView.vue
Labels: code-refactor

#1420 [UXE-3658] fix: fix bug in the select domain field with pick list component
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1421 [UXE-3943] fix: change Secure Headers Cross Origin Opener Policy from same-origin to same-origin-allow-popups
  azion.config.cjs
Labels: bug

#1419 [UXE-3962] test: create e2e for edge dns records
  cypress/e2e/edge-dns.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  src/templates/list-table-block/no-header.vue
  src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
Labels: e2e tests

#1424 [UXE-3677] feat: add account status check before redirecting to billing page
  src/router/hooks/beforeEachRoute.js
Labels: enhancement

#1422 [UXE-3943] fix: change Cross-Origin-Opener-Policy to unsafe-none to avoid blockin Github pop-up
  azion.config.cjs
Labels: bug

#1426 [NO-ISSUE] fix: remove redirect to billing in beforeEachHook that causes effect on github integration
  src/router/hooks/beforeEachRoute.js
Labels: bug

#1425 [UXE-2763] feat: create view bills in billing
  src/helpers/azion-documentation-catalog.js
  src/helpers/convert-date.js
  src/helpers/index.js
  src/router/routes/billing-routes/index.js
  src/services/billing-services/index.js
  src/services/billing-services/list-payment-history-service.js
  src/services/billing-services/list-payment-methods-service.js
  src/templates/list-table-block/action-column.vue
  src/templates/list-table-block/columns/column-builder.js
  src/templates/list-table-block/columns/text-full-with-clipboard-column.vue
  src/templates/list-table-block/columns/text-with-clipboard-column.vue
  src/tests/helpers/convert-date.test.js
  src/tests/services/billing-services/list-payment-history-service.test.js
  src/tests/services/billing-services/list-payment-methods-service.test.js
  src/views/Billing/BillsView.vue
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
  src/views/Credentials/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeDNS/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/EdgeFunctions/ListView.vue
  src/views/EdgeNode/ListViewTabServices.vue
  src/views/Users/ListView.vue
Labels: enhancement, unit-tests, code-refactor

#1431 [NO-ISSUE] chore: remove unnecessary import of define props at text-full-width-clipboard column
  src/templates/list-table-block/columns/text-full-with-clipboard-column.vue
Labels: enhancement

#1430 [UXE-3970] refactor: adjust delete commands to avoid unnecessary page loads
  cypress.config.js
  cypress/README.md
  cypress/e2e/credentials.cy.js
  cypress/e2e/data-stream.cy.js
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/domains.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/edge-dns.cy.js
  cypress/e2e/edge-firewall.cy.js
  cypress/e2e/edge-services.cy.js
  cypress/e2e/functions.cy.js
  cypress/e2e/network-lists.cy.js
  cypress/e2e/personal-token.cy.js
  cypress/e2e/purge.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/users-management.cy.js
  cypress/e2e/variables.cy.js
  cypress/e2e/waf.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
Labels: documentation, code-refactor, BREAKING-CHANGES, e2e tests

#1434 [NO-ISSUE] Stripe input theme
  src/templates/add-payment-method-block/index.vue
Labels: theming

#1429 [UXE-3677] feat: add account status check before redirecting to billing page
  src/helpers/get-static-urls-by-environment.js
  src/tests/helpers/get-static-urls-by-environment.test.js
Labels: code-refactor

#1433 [UXE-3634] fix: adding the correct add response value
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1428 [UXE-3769] refactor add action button to list table block
  src/templates/list-table-block/action-column.vue
  src/templates/list-table-block/dialog/delete-dialog-new.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
  src/views/Billing/BillsView.vue
  src/views/Billing/PaymentListView.vue
  src/views/Credentials/ListView.vue
  src/views/DataStream/ListView.vue
  src/views/DigitalCertificates/ListView.vue
  src/views/Domains/ListView.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/ListView.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/EdgeFunctions/ListView.vue
  src/views/EdgeNode/Dialog/Authorize.vue
  src/views/EdgeNode/ListView.vue
  src/views/EdgeNode/ListViewTabServices.vue
  src/views/EdgeServices/Dialog/EdgeServicesToggleStatus.vue
  src/views/EdgeServices/ListView.vue
  src/views/EdgeServices/ListViewTabResources.vue
  src/views/NetworkLists/ListView.vue
  src/views/PersonalTokens/ListView.vue
  src/views/RealTimeEventsActivityHistory/ListView.vue
  src/views/RealTimeEventsDataStream/ListView.vue
  src/views/RealTimeEventsEdgeDNS/ListView.vue
  src/views/RealTimeEventsEdgeFunctions/ListView.vue
  src/views/RealTimeEventsEdgeFunctionsConsole/ListView.vue
  src/views/RealTimeEventsHTTPRequests/ListView.vue
  src/views/RealTimeEventsImageProcessor/ListView.vue
  src/views/RealTimeEventsTieredCache/ListView.vue
  src/views/RealTimePurge/Dialog/index.vue
  src/views/RealTimePurge/ListView.vue
  src/views/TeamsPermissions/ListView.vue
  src/views/Users/ListView.vue
  src/views/Variables/ListView.vue
  src/views/WafRules/ListView.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: code-refactor, BREAKING-CHANGES

#1436 [UXE-3946] test: add e2e teams permissions (view only)
  cypress/e2e/teams-permissions.cy.js
  cypress/support/selectors.js
Labels: e2e tests

#1432 [UXE-3646] feat: create add payment method drawer
  package.json
  src/main.js
  src/plugins/StripeIntegrationPlugin.js
  src/plugins/factories/stripe-integration-factory.js
  src/router/routes/billing-routes/index.js
  src/services/billing-services/create-payment-method-service.js
  src/services/billing-services/index.js
  src/templates/add-payment-method-block/index.vue
  src/tests/plugins/factories/stripe-integration-factory.test.js
  src/tests/services/billing-services/create-payment-method-service.test.js
  src/views/Billing/PaymentListView.vue
  src/views/Playground/PlaygroundView.vue
  yarn.lock
Labels: enhancement

#1439 [UXE-3947] test: create e2e/e2mock for missing account settings flow
  cypress/e2e/account-settings.cy.js
  cypress/e2mock/account-settings.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/fixtures/account-settings.json
  cypress/fixtures/cities/all-countries.json
  cypress/fixtures/cities/all-timezones.json
  cypress/support/selectors.js
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: code-refactor, e2e tests

#1440 [NO-ISSUE] fix: check service props has passed in list table block
  src/templates/list-table-block/action-column.vue
  src/templates/list-table-block/index.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#1445 [NO-ISSUE] chore: updated the value production in env for stage
  azion/stage/azion.json
Labels: enhancement

#1441 [NO-ISSUE] tooling defect: adjusting the deletion process of an edgeApp and correcting the flow of domains
  cypress/e2e/domains.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/support/utils.js
  src/templates/add-payment-method-block/index.vue
Labels: e2e tests

#1448 [UXE-3957] test: e2e for variable edition with secrets
  cypress.config.js
  cypress/e2e/variables.cy.js
  cypress/support/selectors.js
  src/views/Variables/FormFields/FormFieldsVariables.vue
Labels: e2e tests

#1442 [UXE-3944] fix: add initiatorType field in edge functions
  src/views/EdgeFunctions/CreateView.vue
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: bug

#1437 [UXE-3942] test: e2e domains major cases
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/domains.cy.js
  cypress/fixtures/digital-certificates.js
  cypress/support/commands.js
  cypress/support/selectors.js
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: e2e tests

#1423 [NO-ISSUE] fix: theme table border + hover color
  src/assets/themes/scss/themes/azion-dark/_variables.scss
  src/assets/themes/scss/themes/azion-dark/variables/_data.scss
  src/assets/themes/scss/themes/azion-light/_variables.scss
  src/assets/themes/scss/themes/azion-light/variables/_data.scss
  tailwind.config.js
Labels: theming

#1453 [NO-ISSUE] chore: update environment variables for production and stage deployments
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  azion.config.cjs
  azion/stage/azion.json
  src/helpers/get-environment.js
  vite.config.js
Labels: github-actions

#1457 [NO-ISSUE] chore: update environment variables for production and stage deployments
  azion.config.cjs
  src/helpers/get-environment.js
  src/tests/helpers/account-expired.test.js
  src/tests/helpers/get-environment.test.js
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/tests/helpers/go-to-classic-interface.test.js
Labels: bug, code-refactor

#1459 [UXE-4029] chore: update environment variables for production and stage deployments
  .github/workflows/deploy-production.yml
  src/helpers/get-environment.js
  src/plugins/factories/stripe-integration-factory.js
  vite.config.js
Labels: bug, WIP

#1458 [UXE-3948] test: create e2e for waf rule with some threat types
  cypress/e2e/waf.cy.js
  cypress/support/selectors.js
  src/views/WafRules/FormFields/FormFieldsWafRules.vue
Labels: code-refactor, e2e tests

#1463 [UXE-4029] fix: adjusted redirect billing in production and stage
  src/helpers/account-expired.js
  src/helpers/get-static-urls-by-environment.js
  src/templates/navbar-block/switch-account.vue
  src/templates/profile-block/index.vue
  src/tests/helpers/get-static-urls-by-environment.test.js
Labels: bug

#1464 [UXE-2761] feat: implements new service current invoice
  src/services/billing-services/index.js
  src/services/billing-services/load-current-invoice-service.js
  src/services/billing-services/make-billing-base-url.js
  src/tests/services/billing-services/list-current-invoice-service.test.js
  src/tests/services/billing-services/make-billing-base-url.test.js
  vite.config.js
Labels: unit-tests, console-measurements

#1466 [UXE-4029] fix: adjust redirect billing in production and stage
  src/helpers/account-expired.js
  src/helpers/get-static-urls-by-environment.js
  src/templates/navbar-block/switch-account.vue
  src/templates/profile-block/index.vue
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/views/Billing/PaymentListView.vue
Labels: bug

#1465 [NO-ISSUE] chore: upgrade project version from 1.17.0 to 1.18.0
  package.json
Labels: project version

#1471 [NO-ISSUE] test: store e2e session across specs
  cypress/support/commands.js
Labels: e2e tests

#1455 [UXE-3951] test: create countries and ip/cidr network lists
  cypress/e2e/network-lists.cy.js
  cypress/support/selectors.js
  src/views/NetworkLists/FormFields/FormFieldsCreateNetworkLists.vue
  src/views/NetworkLists/FormFields/FormFieldsEditNetworkLists.vue
Labels: e2e tests

#1473 [UXE-3944] chore: texts revisions in Initiator Type
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: writing

#1469 [UXE-3959] test: add tests to origins creation and edit
  cypress/e2e/edge-application.cy.js
  cypress/support/selectors.js
  src/templates/action-bar-block/go-back.vue
  src/templates/dialog-unsaved-block/index.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
Labels: e2e tests

#1472 [NO-ISSUE] test: remove cypress delay when typing
  cypress/e2e/account-settings.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/e2e/functions.cy.js
Labels: e2e tests

#1454 [UXE-3954] test: add edge firewall function E2E
  .hypothesis/unicode_data/13.0.0/charmap.json.gz
  cypress/e2e/edge-firewall.cy.js
  cypress/support/selectors.js
  src/views/EdgeFirewall/TabsView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: e2e tests

#1475 [UXE-4012] feat: create UI invoice details
  src/router/routes/billing-routes/index.js
  src/services/billing-services/load-current-invoice-service.js
  src/tests/services/billing-services/list-current-invoice-service.test.js
  src/views/Billing/InvoiceDetailsView.vue
  src/views/EdgeApplications/TabsView.vue
Labels: console-measurements

#1474 [UXE-3953] test: e2e for edit resource in edge service
  cypress/e2e/edge-services.cy.js
  cypress/support/selectors.js
  src/templates/list-table-block/index.vue
  src/views/EdgeServices/FormFields/FormFieldsDrawerResource.vue
  src/views/EdgeServices/FormFields/FormFieldsEdgeService.vue
  src/views/EdgeServices/ListViewTabResources.vue
  src/views/EdgeServices/TabsView.vue
Labels: code-refactor, e2e tests

#1479 [UXE-4041] fix: template imgs borders
  src/templates/create-modal-block/index.vue
  src/views/CreateNew/CreateView.vue
  src/views/Marketplace/components/ListSolutions.vue
Labels: bug

#1478 [UXE-3953] test: update e2e for better assertion of edge service creation
  cypress/e2e/edge-services.cy.js
  cypress/support/selectors.js
Labels: e2e tests

#1482 [UXE-3949] test: create waf e2e with different match zones
  cypress/e2e/waf.cy.js
  cypress/support/selectors.js
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
  src/views/WafRules/ListWafRulesAllowed.vue
  src/views/WafRules/TabsView.vue
Labels: e2e tests

#1481 [UXE-3790] test: add e2mock test for activity history list
  cypress/e2mock/activity-history.cy.js
  cypress/fixtures/activity-history.json
  cypress/support/selectors.js
Labels: e2e tests

#1484 [UXE-4112] chore: remove log level config from vite config file to show localhost url on dev script execution
  vite.config.js
Labels: code-refactor

#1485 [NO-ISSUE] chore: add log level to e2e workflow
  .github/workflows/dev-e2e-tests.yml
  .github/workflows/manual-e2e-tests.yml
Labels: github-actions

#1488 [UXE-3281] chore: review content in Billing pages
  src/templates/add-payment-method-block/index.vue
  src/views/Billing/BillsView.vue
  src/views/Billing/Drawer/index.vue
  src/views/Billing/FormFields/FormFieldsCreateCredit.vue
  src/views/Billing/InvoiceDetailsView.vue
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
Labels: writing

#1487 [NO-ISSUE] fix: adjustment to e2e test coverage and addition of @xfail in the account settings test
  .github/workflows/dev-e2e-tests.yml
  .github/workflows/prod-e2e-tests.yml
  .github/workflows/stage-e2e-tests.yml
  cypress/e2e/account-settings.cy.js
  package.json
Labels: e2e tests

#1489 [UXE-3958] test: create e2e for cache settings edition in edge application
  cypress/e2e/account-settings.cy.js
  cypress/e2e/edge-application.cy.js
  cypress/support/selectors.js
  cypress/support/selectors/edge-application.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
Labels: code-refactor, e2e tests

#1494 [NO-ISSUE] chore: replace console log on Cypress commands for Cy.log() function
  cypress/support/commands.js
Labels: code-refactor, e2e tests

#1499 [QA-2077] refactor: move e2e selectors to its own file and folder structure
  cypress/support/selectors.js
  cypress/support/selectors/block-selectors/form-fields-block.js
  cypress/support/selectors/block-selectors/list-table-block.js
  cypress/support/selectors/block-selectors/menu-account.js
  cypress/support/selectors/block-selectors/menu-sidebar.js
  cypress/support/selectors/block-selectors/teams-block.js
  cypress/support/selectors/block-selectors/toast-block.js
  cypress/support/selectors/product-selectors/data-stream.js
  cypress/support/selectors/product-selectors/digital-certificates.js
  cypress/support/selectors/product-selectors/domains.js
  cypress/support/selectors/product-selectors/edge-application.js
  cypress/support/selectors/product-selectors/edge-dns.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  cypress/support/selectors/product-selectors/edge-functions.js
  cypress/support/selectors/product-selectors/edge-pulse.js
  cypress/support/selectors/product-selectors/edge-purge.js
  cypress/support/selectors/product-selectors/edge-services.js
  cypress/support/selectors/product-selectors/network-lists.js
  cypress/support/selectors/product-selectors/personal-tokens.js
  cypress/support/selectors/product-selectors/variables-product.js
  cypress/support/selectors/product-selectors/waf-product.js
  cypress/support/selectors/view-selectors/account-settings.js
  cypress/support/selectors/view-selectors/activity-history.js
  cypress/support/selectors/view-selectors/credentials.js
  cypress/support/selectors/view-selectors/login.js
  cypress/support/selectors/view-selectors/users-management.js
  cypress/support/selectors/view-selectors/your-settings.js
Labels: code-refactor, e2e tests

#1501 [UXE-4029] feat: redirect to billing page when client status is BLOCKED or DEFAULTING
  src/helpers/account-expired.js
  src/router/hooks/beforeEachRoute.js
  src/stores/account.js
  src/tests/helpers/account-expired.test.js
Labels: enhancement

#1500 [UXE-3961] test: create e2e for edition of rules engine in edge applications
  cypress/e2e/edge-application.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: code-refactor, e2e tests

#1502 [UXE-4015] refactor: adjusted section card payment
  cypress/e2e/data-stream.cy.js
  src/views/Billing/BillsView.vue
  src/views/Billing/Components/Notification-payment.vue
  src/views/Billing/TabsView.vue
Labels: code-refactor

#1503 [UXE-4111] chore: add rules route for billing in config vulcan
  azion.config.cjs
Labels: enhancement

#1505 [UXE-3698] feat: add the anchor for Azion's service plans
  src/helpers/azion-documentation-window-opener.js
Labels: enhancement

#1506 [NO-ISSUE] test: ensure to use fixed string to show url change impacts on azion documentation helper function
  src/tests/helpers/azion-documentation-window-opener.test.js
Labels: unit-tests, code-refactor

#1490 [UXE-4043] test: e2e digital certificate major cases csr and import
  cypress/e2e/digital-certificates.cy.js
  cypress/support/selectors/product-selectors/digital-certificates.js
  src/services/digital-certificates-services/edit-digital-certificates-service.js
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: e2e tests

#1507 [UXE-3956] test: e2e edge firewall major cases
  cypress/e2e/edge-firewall.cy.js
  cypress/e2e/network-lists.cy.js
  cypress/e2e/waf.cy.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: e2e tests

#1504 [UXE-4118] test: add e2e tests to billing
  cypress.config.js
  cypress/e2e/billing.cy.js
  cypress/fixtures/billing.json
  cypress/support/selectors.js
  cypress/support/selectors/block-selectors/list-table-block.js
  cypress/support/selectors/product-selectors/billing.js
  src/services/billing-services/create-payment-method-service.js
  src/services/billing-services/delete-payment-service.js
  src/services/billing-services/set-as-default-payment-service.js
  src/templates/add-payment-method-block/index.vue
  src/tests/services/billing-services/create-payment-method-service.test.js
  src/tests/services/billing-services/delete-payment-service.test.js
  src/tests/services/billing-services/set-as-default-payment-service.test.js
  src/views/Billing/FormFields/FormFieldsDrawerCredit.vue
  src/views/Billing/PaymentListView.vue
Labels: e2e tests

#1508 [UXE-4111] chore: rename rules route for billing in config vulcan
  azion.config.cjs
Labels: code-refactor

#1509 [UXE-4028] refactor: improve card payment section and update button download
  src/templates/list-table-block/columns/credit-card-column.vue
  src/templates/list-table-block/index.vue
  src/views/Billing/BillsView.vue
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
Labels: code-refactor

#1511 [NO-ISSUE] chore: update azion deploy command to include debug flag
  .github/workflows/deploy-stage.yml
Labels: github-actions

#1512 [UXE-4117] test: replace api wait with time wait
  cypress/e2e/account-settings.cy.js
Labels: code-refactor, e2e tests

#1510 [NO-ISSUE] fix: adjust validation issues
  src/router/routes/billing-routes/index.js
  src/services/billing-services/index.js
  src/services/billing-services/load-current-invoice-service.js
  src/services/billing-services/load-invoice-data-service.js
  src/tests/services/billing-services/load-current-invoice-service.test.js
  src/tests/services/billing-services/load-invoice-data-service.test.js
  src/views/Billing/BillsView.vue
  src/views/Billing/InvoiceDetailsView.vue
  src/views/Billing/TabsView.vue
Labels: bug

#1514 [UXE-3698] refactor: add default card number in your service plan card
  src/services/billing-services/load-current-invoice-service.js
  src/services/billing-services/load-invoice-data-service.js
  src/services/billing-services/load-your-service-plan-service.js
  src/tests/services/billing-services/load-your-service-plan-service.test.js
  src/views/Billing/BillsView.vue
Labels: code-refactor

#1518 [UXE-4157] refactor: update card number search in list-payment-methods-service
  src/services/billing-services/list-payment-methods-service.js
  src/tests/services/billing-services/list-payment-methods-service.test.js
  src/views/Billing/PaymentListView.vue
Labels: code-refactor

#1517 [UXE-4029] refactore: adjusted the redirect to handle forced tabs and conditions during login
  src/router/hooks/beforeEachRoute.js
  src/router/routes/billing-routes/index.js
  src/services/billing-services/load-your-service-plan-service.js
  src/templates/add-payment-method-block/index.vue
  src/tests/services/billing-services/create-payment-method-service.test.js
  src/views/Billing/Drawer/DrawerPaymentMethod.vue
  src/views/Billing/TabsView.vue
Labels: code-refactor

#1520 [UXE-3698] refactor: load the default credit card when bill tab it is active
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
Labels: code-refactor

#1521 [NO-ISSUE] chore: fixing environments in lowercase
  README.md
  vite.config.js
Labels: code-refactor

#1516 [UXE-3955] test: e2e edge app functions major cases
  cypress/e2e/edge-application.cy.js
  cypress/e2e/edge-functions.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: e2e tests

#1524 [UXE-3318] fix: rename edge node drawer title to Bind Service
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/EdgeNode/Drawer/index.vue
Labels: bug, code-refactor

#1522 [UXE-3917] fix: waf allowed rules cancel button redirect url
  src/router/routes/waf-rules-routes/index.js
  src/views/WafRules/EditView.vue
  src/views/WafRules/TabsView.vue
Labels: bug

#1523 [UXE-3592] fix: limit custom header in 5 items
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: bug

#1519 [UXE-4155] feat: clicking on payment history should open the invoice details
  src/templates/list-table-block/index.vue
  src/views/Billing/BillsView.vue
Labels: enhancement

#1526 [UXE-4205] spike: verify possibility of 100% of data-testid in components
  cypress/README.md
  cypress/e2e/billing.cy.js
  cypress/e2e/credentials.cy.js
  cypress/e2e/digital-certificates.cy.js
  cypress/e2e/domains.cy.js
  cypress/e2e/edge-firewall.cy.js
  cypress/e2e/edge-services.cy.js
  cypress/e2e/purge.cy.js
  cypress/e2e/teams-permissions.cy.js
  cypress/e2e/waf.cy.js
  cypress/e2mock/your-settings.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  cypress/support/selectors/block-selectors/list-table-block.js
  cypress/support/selectors/block-selectors/teams-block.js
  cypress/support/selectors/block-selectors/toast-block.js
  cypress/support/selectors/product-selectors/billing.js
  cypress/support/selectors/product-selectors/data-stream.js
  cypress/support/selectors/product-selectors/digital-certificates.js
  cypress/support/selectors/product-selectors/domains.js
  cypress/support/selectors/product-selectors/edge-application.js
  cypress/support/selectors/product-selectors/edge-dns.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  cypress/support/selectors/product-selectors/edge-services.js
  cypress/support/selectors/product-selectors/network-lists.js
  cypress/support/selectors/product-selectors/personal-tokens.js
  cypress/support/selectors/product-selectors/variables-product.js
  cypress/support/selectors/product-selectors/waf-product.js
  cypress/support/selectors/view-selectors/account-settings.js
  cypress/support/selectors/view-selectors/users-management.js
  cypress/support/selectors/view-selectors/your-settings.js
  cypress/support/utils.js
  docs/E2E_SELECTORS.md
  src/templates/add-payment-method-block/index.vue
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/list-table-block/columns/expand-column.vue
  src/templates/list-table-block/columns/expand-text-column.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/with-lazy-and-dropdown-filter.vue
  src/templates/page-heading-block-tabs/index.vue
  src/templates/page-heading-block/index.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/Domains/Dialog/CopyDomainDialog.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/TeamsPermissions/FormFields/FormFieldsTeamPermissions.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
  src/views/WafRules/EditView.vue
  src/views/WafRules/TabsView.vue
  src/views/YourSettings/FormFields/FormFieldsYourSettings.vue
Labels: bug, documentation, code-refactor, e2e tests

#1529 [UXE-3997] fix: digital certificate errors are not being formatted
  src/services/digital-certificates-services/create-digital-certificates-csr-service.js
  src/services/digital-certificates-services/create-digital-certificates-service.js
  src/services/digital-certificates-services/edit-digital-certificates-service.js
  src/services/digital-certificates-services/msg-error.js
Labels: bug

#1525 [UXE-4143] refactor: add go to Payments and add credit button options on empty payment list of bills page
  src/helpers/convert-date.js
  src/services/billing-services/load-current-invoice-service.js
  src/services/billing-services/load-your-service-plan-service.js
  src/templates/empty-results-block/index.vue
  src/tests/helpers/convert-date.test.js
  src/tests/services/billing-services/load-current-invoice-service.test.js
  src/tests/services/billing-services/load-your-service-plan-service.test.js
  src/views/Billing/BillsView.vue
Labels: code-refactor

#1535 [UXE-4215] fix: billing view design adjustments
  src/services/billing-services/list-payment-history-service.js
  src/templates/list-table-block/columns/text-with-tag-column.vue
  src/tests/services/billing-services/list-payment-history-service.test.js
  src/views/Billing/BillsView.vue
  src/views/Billing/Components/Notification-payment.vue
  src/views/Billing/Drawer/DrawerAddCredit.vue
  src/views/Billing/FormFields/FormFieldsDrawerCredit.vue
  src/views/Billing/InvoiceDetailsView.vue
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
Labels: bug

#1536 [UXE-3804] fix: format correctly digital certificates error messages
  src/services/digital-certificates-services/create-digital-certificates-csr-service.js
  src/services/digital-certificates-services/create-digital-certificates-service.js
  src/services/digital-certificates-services/edit-digital-certificates-service.js
  src/tests/services/digital-certificates-services/create-digital-certificates-csr-service.test.js
  src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js
  src/tests/services/digital-certificates-services/edit-digital-certificates-service.test.js
Labels: bug

#1538 [NO-ISSUE] chore: revert upgrade project version to 1.18.0
  package.json
Labels: project version

#1537 [UXE-3455] fix: screen goes white when clicking on active marketplace category
  src/views/Marketplace/MarketplaceHomeView.vue
Labels: bug

#1549 [UXE-4300] feat: add last updated to billing
  src/helpers/convert-date.js
  src/router/routes/billing-routes/index.js
  src/services/billing-services/index.js
  src/services/billing-services/load-invoice-last-updated-service.js
  src/tests/services/billing-services/load-invoice-last-updated-service.test.js
  src/views/Billing/TabsView.vue
Labels: console-measurements

#1550 [UXE-4303] chore: update readme with stripe env info
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  README.md
  src/plugins/StripeIntegrationPlugin.js
  src/plugins/factories/stripe-integration-factory.js
  src/tests/plugins/factories/stripe-integration-factory.test.js
Labels: documentation, unit-tests

#1554 [NO-ISSUE] fix: recreating stage console configuration with vulkan
  .gitignore
  azion/stage/azion.json
  azion/stage/files.json
Labels: bug, BREAKING-CHANGES

#1531 [UXE-3648] feat: implement service and product changes table
  src/router/routes/billing-routes/index.js
  src/services/billing-services/index.js
  src/services/billing-services/list-service-and-products-changes.js
  src/tests/services/billing-services/list-service-and-products-changes.test.js
  src/views/Billing/BillsView.vue
  src/views/Billing/InvoiceDetailsView.vue
  src/views/Billing/components/notification-payment.vue
  src/views/Billing/components/table-services-products.vue
Labels: console-measurements

#1556 [UXE-3686] fix: change spaces in sign up page
  src/views/Signup/SignupView.vue
Labels: bug

#1555 [UXE-3320] refactor: service unbinding treated as deletion in edge node
  src/services/edge-node-service-services/delete-service-edge-node-service.js
  src/tests/services/edge-node-service-services/delete-service-edge-node-service.test.js
  src/views/EdgeNode/Dialog/Unbind.vue
  src/views/EdgeNode/ListViewTabServices.vue
Labels: unit-tests, code-refactor

#1560 [NO-ISSUE] chore: upgrade project version from 1.18.0 to 1.19.0
  package.json
Labels: project version

#1566 [NO-ISSUE] chore: update Azion CLI to version 1.34.2 in deployment workflows
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
Labels: bug, github-actions

#1567 [UXE-3455] fix: remove the category query when the filter is all
  src/views/Marketplace/MarketplaceHomeView.vue
Labels: bug

#1558 [UXE-4303] chore: rename dev stripe token env var
  README.md
  src/plugins/factories/stripe-integration-factory.js
  src/tests/plugins/factories/stripe-integration-factory.test.js
Labels: documentation, enhancement

#1570 [NO-ISSUE] chore: upgrade project version from 1.19.0 to 1.19.1
  package.json
Labels: project version
