Repository aziontech/azion-console-kit, pull requests merged in 2024-12, with the labels that each got.

#1978 [UXE-5803] feat: migrate edge application functions instance creation to api v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-functions-services/v4/create-function-service.js
  src/services/edge-application-functions-services/v4/index.js
  src/tests/services/edge-application-functions-services/v4/edge-function-service.test.js
Labels: api-v4-migration

#1981 [UXE-5817] feat: remove edge application column from domains table
  src/services/domains-services/v4/list-domain-service.js
  src/tests/services/domains-services/v4/list-domain-service.test.js
  src/views/Domains/ListView.vue
Labels: console-measurements

#1979 [UXE-5757] feat: migrated edge firewall delete function to api v4
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-functions-services/v4/delete-function-service.js
  src/services/edge-firewall-functions-services/v4/index.js
  src/tests/services/edge-firewall-functions-services/v4/delete-edge-firewall-functions-service.test.js
Labels: api-v4-migration

#1986 [UXE-5804] feat: migrate edge application function instances edit page to api v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-functions-services/v4/edit-function-instance-service.js
  src/services/edge-application-functions-services/v4/index.js
  src/services/edge-application-functions-services/v4/load-function-instance-service.js
  src/tests/services/edge-application-functions-services/v4/edit-function-instance-service.test.js
  src/tests/services/edge-application-functions-services/v4/load-function-instance-service.test.js
Labels: api-v4-migration

#1968 [UXE-5779] fix: create allowed rules by tuning page
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/tests/services/waf-rules-services/create-waf-rules-allowed-tuning-service.test.js
  src/views/WafRules/Dialog/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#1992 [UXE-5852] fix: add readonly in domain name field
  src/services/domains-services/v4/list-domain-service.js
  src/services/edge-application-functions-services/v4/index.js
  src/tests/services/domains-services/v4/list-domain-service.test.js
  src/views/Domains/Dialog/CopyDomainDialog.vue
Labels: bug

#1982 [UXE-5776] fix: incorrect error handling when managing accounts
  src/services/accounts-management-services/list-accounts-service.js
  src/tests/services/accounts-management-services/list-accounts-service.test.js
Labels: bug

#1985 [UXE-5472] fix: incorrect error message when creating Personal Token
  src/services/personal-tokens-services/create-personal-tokens-service.js
  src/tests/services/personal-tokens-services/create-personal-tokens-service.test.js
Labels: bug

#1989 [UXE-5805] feat: migrate edge app function instances delete api to v4
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-functions-services/v4/delete-function-service.js
  src/services/edge-application-functions-services/v4/index.js
  src/tests/services/edge-application-functions-services/v4/delete-function-service.test.js
Labels: api-v4-migration

#1990 [UXE-5825] feat: lazy load Edge Function for Edge Firewall Function Instances
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-functions-services/v4/make-edge-functions-base-url.js
  src/services/edge-functions-services/v4/index.js
  src/services/edge-functions-services/v4/list-edge-functions-dropdown-service.js
  src/services/edge-functions-services/v4/load-edge-function-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/tests/services/edge-functions-services/v4/list-edge-functions-dropdown-service.test.js
  src/tests/services/edge-functions-services/v4/load-edge-function-service.test.js
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/ListView.vue
Labels: console-measurements

#1994 [UXE-5851] feat: implements lazy loader dropdown function instance edge app
  cypress/e2e/edge-application/create-function-instance.cy.js
  cypress/e2e/edge-application/edit-function-instance.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/router/routes/edge-application-routes/index.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
Labels: console-measurements

#1991 [UXE-5756] feat: migrated function firewall update to API v4
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-functions-services/index.js
  src/services/edge-firewall-functions-services/load-function-service.js
  src/services/edge-firewall-functions-services/v4/edit-function-service.js
  src/services/edge-firewall-functions-services/v4/index.js
  src/services/edge-firewall-functions-services/v4/load-function-service.js
  src/tests/services/edge-firewall-functions-services/v4/edit-function-service.test.js
  src/tests/services/edge-firewall-functions-services/v4/load-function-service.test.js
Labels: api-v4-migration

#1999 [UXE-5701] feat: update report dataset and data handling in real-time metrics
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/modules/real-time-metrics/reports/load-report-with-meta.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#1964 [UXE-5746] refactor: change is_active to active on Edge Firewall Rules Engine
  src/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.js
  src/tests/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.test.js
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: do-not-merge, code-refactor

#2003 [UXE-3721] feat: Domains List - name/subject name columns use "show more" component
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/services/edge-application-functions-services/v4/index.js
  src/services/edge-firewall-functions-services/v4/index.js
  src/services/edge-functions-services/v4/list-edge-functions-dropdown-service.js
  src/services/edge-functions-services/v4/load-edge-function-service.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/services/edge-functions-services/v4/list-edge-functions-dropdown-service.test.js
  src/views/DigitalCertificates/ListView.vue
Labels: enhancement, code-refactor

#1993 [UXE-5759] feat: migrated rules engine CREATE edge firewall to api v4
  cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-header-criteria.cy.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/v4/index.js
  src/tests/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.test.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: do-not-merge, api-v4-migration

#2001 [UXE-5808] feat: migrate edge application rules engine deletion to api v4
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-cache-policy.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine.cy.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-rules-engine-services/v4/delete-rule-service.js
  src/services/edge-application-rules-engine-services/v4/index.js
  src/tests/services/edge-application-rules-engine-services/v4/delete-rule-service.test.js
Labels: api-v4-migration

#1996 [UXE-5853] fix: WAF Tunning won't open drawer when clicking to uncheck item
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/templates/list-table-block/with-selection-behavior.vue
  src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#2004 [UXE-5856] fix: additional data screen is misaligned
  src/layout/index.vue
  src/services/edge-application-rules-engine-services/v4/index.js
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/views/Signup/SignupView.vue
Labels: bug

#2014 [UXE-5760] fix: update edge firewall rules engine to use 'active' property instead of 'is_active'
  src/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.js
  src/tests/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.test.js
Labels: bug

#2015 [UXE-5904] fix: prevent duplicate options in dropdown by checking for existing values
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
Labels: bug

#2005 [UXE-5823] fix: List users beyond 200 users
  src/services/users-services/list-users-service.js
  src/tests/services/users-services/list-users-service.test.js
  src/views/Users/ListView.vue
Labels: bug

#1975 [UXE-5813] fix: show name of instance function instead of function on Edge App Rules Engine
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-waf.cy.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-functions-services/v4/index.js
  src/services/edge-application-functions-services/v4/list-edge-functions-options-service.js
  src/tests/services/edge-application-functions-services/v4/list-edge-functions-options-service.test.js
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#2017 [UXE-5850] feat: Data Stream - disable inputs/buttons for users without edit permissions
  src/stores/account.js
  src/views/DataStream/EditView.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/ListView.vue
Labels: bug, enhancement

#2020 [UXE-5888] refactor: update WAF rules services to use API v4 for editing and loading rules
  src/router/routes/waf-rules-routes/index.js
  src/services/waf-rules-services/v4/edit-waf-rules-service.js
  src/services/waf-rules-services/v4/index.js
  src/services/waf-rules-services/v4/load-waf-rules-service.js
  src/tests/services/waf-rules-services/v4/edit-waf-rules-service.test.js
  src/tests/services/waf-rules-services/v4/load-waf-rules-service.test.js
Labels: api-v4-migration

#2023 [UXE-5896] test: remove flag xfail and fix broken tests
  cypress/e2e/account-settings/update-address.cy.js
  cypress/e2e/account-settings/update-billing-email.cy.js
  cypress/e2e/billing/add-credit.cy.js
  cypress/e2e/data-stream/create-data-stream-awskinesis.cy.js
  cypress/e2e/data-stream/create-data-stream-azureblobstorage.cy.js
  cypress/e2e/data-stream/create-data-stream-azuremonitor.cy.js
  cypress/e2e/data-stream/create-data-stream-bigquery.cy.js
  cypress/e2e/data-stream/create-data-stream-datadog.cy.js
  cypress/e2e/data-stream/create-data-stream-elasticsearch.cy.js
  cypress/e2e/data-stream/create-data-stream-ibmqradar.cy.js
  cypress/e2e/data-stream/create-data-stream-kafka.cy.js
  cypress/e2e/data-stream/create-data-stream-s3.cy.js
  cypress/e2e/data-stream/create-data-stream-splunk.cy.js
  cypress/e2e/data-stream/create-data-stream-standard.cy.js
  cypress/e2e/digital-certificates/create-csr-certificate.cy.js
  cypress/e2e/domains/create-domain-lets-encrypt.cy.js
  cypress/e2e/domains/create-domain-mtls.cy.js
  cypress/e2e/edge-application/edit-origin.cy.js
  cypress/e2e/edge-application/instantiate-function-rules-engine.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  cypress/e2e/edge-functions/create-edge-function.cy.js
  cypress/e2e/edge-pulse/copy-tags-edge-pulse.cy.js
  cypress/e2e/network-lists/create-network-list-asn.cy.js
  cypress/e2e/network-lists/create-network-list-countries.cy.js
  cypress/e2e/teams-permissions/create-team-full-permissions.cy.js
  cypress/e2e/teams-permissions/create-team-view-permissions.cy.js
  cypress/e2e/users-management/create-user-with-team.cy.js
  cypress/e2e/variables/edit-variable.cy.js
  cypress/e2e/your-settings/edit-user-phone.cy.js
Labels: e2e tests

#2026 [UXE-5921] fix: remove back to list button from edge application function instances
  cypress/e2e/edge-application/function-instance/edit-function-instance.cy.js
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
Labels: bug

#2028 chore: update dev from main
  .github/workflows/pre-merge.yml
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: sync-main-to-dev-after-deploy

#2016 [UXE-5923] fix: rename Edge DNS endpoint and change code to match project standard
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-services/index.js
  src/services/edge-dns-services/v4/index.js
  src/services/edge-dns-services/v4/list-edge-dns-service.js
  src/services/edge-dns-services/v4/make-edge-dns-base-url.js
  src/tests/services/edge-dns-services/v4/list-edge-dns-service.test.js
  src/tests/services/edge-dns-services/v4/make-edge-dns-base-url.test.js
  src/views/EdgeDNS/ListView.vue
Labels: bug, unit-tests

#2010 [NO-ISSUE] chore: update version to 1.31.0
  package.json
Labels: project version

#2036 [UXE-5953] fix: Edge Function Instance Json Args is overwritten
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: bug

#2035 [UXE-5952] fix: edge firewall behavior handling with new rate limit properties and selectors
  cypress/e2e/edge-firewall/create-edge-firewall-rule-engine-rate-limit.cy.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  src/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/v4/edit-edge-firewall-rules-engine-service.js
  src/tests/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.test.js
Labels: bug

#2038 [UXE-5966] fix: incorrect argument when saving criteria rules engine
  src/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.js
  src/services/edge-application-rules-engine-services/v4/helper-criteria.js
  src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
Labels: bug

#2040 [NO-ISSUE] chore: update version to 1.31.1
  package.json
Labels: project version

#2044 [UXE-5981] test: remove unused assert from domains test
  cypress/e2e/domains/create-domain-mtls.cy.js
Labels: e2e tests

#2042 [UXE-5892] feat: migrate edge function delete to api v4
  cypress/e2e/edge-functions/create-edge-function.cy.js
  src/router/routes/edge-functions-routes/index.js
  src/services/edge-functions-services/v4/delete-edge-function-service.js
  src/services/edge-functions-services/v4/index.js
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/tests/services/edge-functions-services/v4/delete-edge-function-service.test.js
Labels: api-v4-migration
