Repository aziontech/azion-console-kit, pull requests merged in 2024-04, with the labels that each got.

#950 [UXE-2648] fix: action bar is being overlapped by other components
  src/templates/content-block/index.vue
  src/templates/create-drawer-block/index.vue
  src/templates/edit-drawer-block/index.vue
Labels: bug

#945 [NO-ISSUE] style: apply the same action button style for tables
  src/templates/list-table-block/columns/text-with-clipboard-column.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/no-header.vue
Labels: do-not-merge, blocks

#943 [NO-ISSUE] fix: main-content layout
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
  src/views/Marketplace/MarketplaceHomeView.vue
Labels: do-not-merge, blocks, code-refactor

#949 [UXE-2339] feat: new signup flow created
  src/assets/svg/vtex-logo.vue
  src/helpers/azion-documentation-window-opener.js
  src/helpers/index.js
  src/router/routes/signup-routes/index.js
  src/templates/footer-block/index.vue
  src/templates/navbar-block/index.vue
  src/templates/sign-in-block/index.vue
  src/templates/signup-block/account-activation.vue
  src/templates/signup-block/client-testimonials-block.vue
  src/templates/signup-block/form-signup-block.vue
  src/templates/signup-block/login-with-email-block.vue
  src/templates/social-idps-block/index.vue
  src/tests/helpers/azion-documentation-window-opener.test.js
  src/views/Playground/PlaygroundView.vue
  src/views/Signup/SignupActivationView.vue
  src/views/Signup/SignupView.vue
  tailwind.config.js
Labels: enhancement

#948 [UXE-2294] refactor: configure metrics service to use abortController
  src/modules/real-time-metrics/filters/load-dataset-available-filters.js
  src/modules/real-time-metrics/filters/load-info-available-filters.js
  src/modules/real-time-metrics/reports/load-report-with-meta.js
  src/modules/real-time-metrics/reports/load-reports-data-by-selected-dashboard.js
  src/services/real-time-metrics-services/fetch-metrics-data-from-beholder.js
  src/services/real-time-metrics-services/index.js
  src/services/real-time-metrics-services/load-real-time-metrics-data.js
  src/services/real-time-metrics-services/make-beholder-base-url.js
  src/services/real-time-metrics-services/search-domains-service.js
  src/services/real-time-metrics-services/search-edge-dns-service.js
  src/services/real-time-metrics-services/search-edge-functions.js
  src/tests/services/real-time-metrics-services/load-real-time-metrics-data.test.js
  src/tests/services/real-time-metrics-services/make-beholder-base-url.test.js
  src/tests/services/real-time-metrics-services/search-domains-service.test.js
  src/tests/services/real-time-metrics-services/search-edge-dns-service.test.js
  src/tests/services/real-time-metrics-services/search-edge-functions-service.test.js
  vite.config.js
Labels: unit-tests, code-refactor

#941 [UXE-2659] fix: change more details button position and add description to solut…
  src/templates/template-engine-block/index.vue
  src/views/CreateNew/CreateView.vue
Labels: bug

#954 [UXE-2552] feat: added import from github section in create modal
  src/router/index.js
  src/router/routes/import-github-routes/index.js
  src/templates/create-modal-block/index.vue
  src/views/ImportGitHub/ImportStaticView.vue
Labels: enhancement

#957 [UXE-1985] refactor: change verb in application banner home
  src/views/Home/HomeView.vue
Labels: writing, waiting-for-uxe-to-merge

#960 [UXE-2511] feat: add button GitHub integration to templates marketplace
  src/router/index.js
  src/router/routes/create-new-routes/index.js
  src/router/routes/github-routes/index.js
  src/services/version-control-system-integration-services/index.js
  src/services/version-control-system-integration-services/list-integrations-service.js
  src/services/version-control-system-integration-services/list-platforms-service.js
  src/services/version-control-system-integration-services/make-version-control-system-base-url.js
  src/services/version-control-system-integration-services/post-callback-url-service.js
  src/templates/template-engine-block/form-loading.vue
  src/templates/template-engine-block/index.vue
  src/templates/template-engine-block/oauth-github.vue
  src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
  src/tests/services/version-control-system-integration-services/list-platforms-service.test.js
  src/tests/services/version-control-system-integration-services/post-callback-url-service.test.js
  src/views/CreateNew/CreateView.vue
  src/views/GitHubConnectionPopup/index.vue
  vite.config.js
Labels: categorized, console-measurements

#962 [NO-SSUE] fix: resolve incorrect prop access
  src/stores/metrics.js
Labels: bug

#961 [NO-ISSUE] fix: endpoint url of version control system service to use v4 api
  src/services/version-control-system-integration-services/make-version-control-system-base-url.js
  src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
  src/tests/services/version-control-system-integration-services/list-platforms-service.test.js
  src/tests/services/version-control-system-integration-services/post-callback-url-service.test.js
  src/views/ImportGitHub/ImportStaticView.vue
Labels: bug

#959 [UXE-2729]feat-apply-icon-profile-to-menu
  src/templates/profile-block/index.vue
  tailwind.config.js
Labels: enhancement

#966 [UXE-1720] fix: add validations when certificate or private key are empty strings
  src/services/digital-certificates-services/create-digital-certificates-service.js
  src/tests/services/digital-certificates-services/create-digital-certificates-service.test.js
Labels: bug, unit-tests

#969 [UXE-2759] fix: add validation to weight field based on originType
  src/services/edge-application-origins-services/create-origin-service.js
  src/tests/services/edge-application-origins-services/create-origin-service.test.js
Labels: bug, unit-tests

#968 [UXE-2708] feat: include frameworks for azion icons
  src/assets/icons/azionicons.scss
  src/assets/icons/azionicons.woff2
Labels: enhancement

#967 [UXE-1770] fix: filter domains that already have an edge firewall instancied
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
Labels: bug

#970 [UXE-2732] feat: recommend templates by user job role
  src/router/hooks/beforeEachRoute.js
  src/services/account-settings-services/index.js
  src/services/account-settings-services/load-account-job-role-service.js
  src/templates/create-modal-block/create-modal-block-loading-state.vue
  src/templates/create-modal-block/index.vue
  src/templates/create-modal-block/make-create-modal-block.vue
  src/templates/navbar-block/create.vue
  src/templates/profile-block/index.vue
  src/tests/services/account-settings-services/load-account-job-role-service.test.js
Labels: enhancement, unit-tests

#952 [UXE-2401] fix: incorrect loading of digital certificates status on the edit domains screen
  src/services/domains-services/edit-domain-service.js
  src/services/domains-services/load-domain-service.js
  src/tests/services/domains-services/edit-domain-service.test.js
  src/tests/services/domains-services/load-domain-service.test.js
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: bug

#971 [UXE-2339] fix: adjust style signup page
  src/templates/signup-block/client-testimonials-block.vue
  src/templates/signup-block/form-signup-block.vue
  src/views/Signup/SignupView.vue
Labels: bug, categorized

#978 [UXE-1769] refactor: adjusted imports and css in selectors
  src/templates/form-fields-inputs/fieldGroupCheckbox.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/form-fields-inputs/fieldGroupSwitch.vue
  src/templates/selector-block/index.vue
  src/views/Playground/PlaygroundView.vue
Labels: code-refactor

#972 [UXE-2686] fix: remove application acelerator options from cache setting when this option is disabled
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
Labels: bug

#977 feat: add trigger event sign up
  src/templates/signup-block/login-with-email-block.vue
  src/views/Login/LoginView.vue
Labels: categorized, console-measurements

#980 [NO-ISSUE] fix: remove url chars from name signup
  src/templates/signup-block/login-with-email-block.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: bug

#982 [UXE-2339] fix: adjust view signup
  src/templates/signup-block/form-signup-block.vue
  src/views/Signup/SignupView.vue
Labels: categorized, console-measurements

#981 [UXE-2609] feat: Create clicked to create edge firewall event
  src/views/EdgeFirewall/ListView.vue
Labels: console-measurements

#983 [NO-ISSUE] fix: add platform_feature__vcs_integration__uuid name to display github button
  src/services/script-runner-service/create-script-runner-execution-service.js
  src/templates/template-engine-block/index.vue
  src/tests/helpers/get-script-runner-image.test.js
Labels: bug

#984 [UXE-2792] fix: add option to add more scopes and fix create journey for mobile devices
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/navbar-block/create.vue
  src/templates/template-engine-block/index.vue
  src/views/ImportGitHub/ImportStaticView.vue
Labels: bug

#986 [UXE-2752] fix: changed the height of the dropdown
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
Labels: bug

#985 [UXE-2790] feat: redirect to classic interface rtm
  src/helpers/go-to-classic-interface.js
  src/templates/content-block/banner.vue
  src/templates/content-block/index.vue
Labels: categorized, console-measurements

#987 [UXE-2643] fix: remove requires application acceleration from description
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: bug

#988 [UXE-1769] refactor: adjusted props and design selectores
  src/templates/form-fields-inputs/fieldGroupCheckbox.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/templates/form-fields-inputs/fieldGroupSwitch.vue
  src/templates/selector-block/index.vue
  src/views/Playground/PlaygroundView.vue
Labels: enhancement

#990 [UXE-2644] feat: disable behavior optimize images
  src/helpers/go-to-classic-interface.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: categorized, console-measurements

#992 [NO-ISSUE] feat: add auto complete off to signup and template engine blocks
  index.html
  src/helpers/go-to-classic-interface.js
  src/helpers/index.js
  src/templates/signup-block/login-with-email-block.vue
  src/tests/helpers/go-to-classic-interface.test.js
  src/views/CreateNew/CreateView.vue
  src/views/Marketplace/drawer/IntegrationInstall.vue
Labels: enhancement, unit-tests

#991 [UXE-1609] fix: removed z-index from profileMenu
  src/templates/profile-block/index.vue
Labels: bug

#993 [UXE-1760] refactor: add tiered cache to cache settings
  src/utils/constants.js
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: enhancement

#997 feat: add client testimonial text to signup view
  src/router/routes/create-new-routes/index.js
  src/templates/signup-block/client-testimonials-block.vue
Labels: enhancement

#995 [NO-ISSUE] refactor: function update options requires in rules engine
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: code-refactor

#1000 [NO-ISSUE] feat: add track to the signup event to be trigger immediately
  src/views/Login/LoginView.vue
Labels: console-measurements

#998 [UXE-2757] feat: created dialog for scheduling onboarding additional data
  src/App.vue
  src/helpers/azion-onboarding-window-opener.js
  src/helpers/index.js
  src/main.js
  src/templates/dialogs-block/dialog-onboarding-scheduling.vue
  src/tests/helpers/azion-onboarding-window-opener.test.js
  src/views/Home/HomeView.vue
Labels: enhancement, unit-tests, code-refactor

#1001 [UXE-2636] fix: rules engine with message problems
  src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
  src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
Labels: bug

#996 [UXE-2717] feat: new framework detector service/tests and refactor of vulcan presets
  .vscode/extensions.json
  src/helpers/get-vulcan-presets.js
  src/helpers/index.js
  src/router/routes/import-github-routes/index.js
  src/services/axios/makeGithubApi.js
  src/services/github-services/framework-detector-services.js
  src/services/github-services/index.js
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/services/vulcan-services/get-mode-by-preset-service.js
  src/tests/helpers/get-vulcan-presets.test.js
  src/tests/services/github-services/framework-detector-services.test.js
  src/views/ImportGitHub/FormFields/FormFieldsImportStatic.vue
  src/views/ImportGitHub/ImportStaticView.vue
Labels: enhancement, unit-tests, code-refactor

#1003 [NO-ISSUE] refactor: refactor signup and login process
  src/templates/signup-block/form-signup-block.vue
  src/templates/signup-block/login-with-email-block.vue
Labels: bug, code-refactor

#999 [UXE-2566] fix: edge function error message
  src/helpers/go-to-classic-interface.js
  src/services/edge-functions-services/delete-edge-functions-service.js
  src/tests/services/edge-functions-services/delete-edge-functions-service.test.js
Labels: bug

#1004 [UXE-2474] feat: new additional data
  src/plugins/analytics/trackers/SignUpTracker.js
  src/router/routes/signup-routes/index.js
  src/services/signup-services/index.js
  src/services/signup-services/list-additional-data-info-service.js
  src/services/signup-services/make-additional-data-base-url.js
  src/services/signup-services/make-patch-fullname-service-base-url.js
  src/services/signup-services/make-post-additional-data-base-url.js
  src/services/signup-services/patch-fullname-service.js
  src/services/signup-services/post-additional-data-service.js
  src/services/signup-services/put-additional-data-service.js
  src/stores/account.js
  src/templates/action-bar-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/tests/plugins/analytics/AnalyticsTrackerAdapter.test.js
  src/tests/services/signup-services/list-additional-data-info-service.test.js
  src/tests/services/signup-services/patch-fullname-service.test.js
  src/tests/services/signup-services/post-additional-data-service.test.js
  src/tests/services/signup-services/put-additional-data-service.test.js
  src/views/Signup/AdditionalDataView.vue
  tailwind.config.js
Labels: unit-tests, code-refactor, BREAKING-CHANGES

#1005 [NO-ISSUE] fix: add placeholder to GitHub integration dropdown and layout shift at onboarding modal
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/template-engine-block/index.vue
  src/views/Home/HomeView.vue
Labels: bug

#1002 [UXE-2753] fix: tiered cache options purge
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
Labels: bug

#1006 [UXE-1944] fix: add json language in vue monaco editor
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: bug

#1007 [UXE-2833] fix: escape special use in error message of template fields
  src/templates/template-engine-block/index.vue
Labels: bug

#1010 [NO-ISSUE] chore: upgrade project version from 1.12.0 to 1.13.0
  package.json
Labels: project version

#1014 [NO-ISSUE] fix: ensure to call integrations only with github integration field on input schema
  src/templates/template-engine-block/index.vue
Labels: bug

#1016 [NO-ISSUE] chore: improve project version from 1.13.0 to 1.13.1
  package.json
Labels: project version

#1013 [NO-ISSUE] fix: adjusting the triggering of the user activated account event
  src/views/Login/LoginView.vue
Labels: bug, do-not-merge, console-measurements

#1030 [UXE-2127] fix: failed to create edge firewall
  src/utils/errorHandlingTracker.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeFirewall/CreateView.vue
Labels: enhancement, console-measurements

#1031 [UXE-1760] fix: add minimum value to input
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
Labels: bug

#1032 [UXE-2730] fix: apply fixed position for profile menu
  src/templates/profile-block/index.vue
Labels: bug, theming

#1033 [UXE-2871] fix: adjusting journey github template
  src/templates/template-engine-block/index.vue
Labels: bug

#1035 [UXE-2654] fix: fixed-position-to-action-bar-drawer
  src/assets/themes/scss/themes/azion-dark/extended-components/_sidebar.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_sidebar.scss
  src/templates/action-bar-block/go-back.vue
  src/templates/action-bar-block/index.vue
  src/templates/create-drawer-block/index.vue
  src/templates/edit-drawer-block/index.vue
Labels: bug, theming

#1037 [UXE-2475] feat: additional data improvements
  src/assets/svg/additional-data-illustration.vue
  src/router/routes/signup-routes/index.js
  src/services/signup-services/index.js
  src/services/signup-services/make-update-account-info-service-base-url.js
  src/services/signup-services/update-account-info-service.js
  src/templates/signup-block/additional-data-form-block.vue
  src/tests/services/signup-services/update-account-info-service.test.js
  src/views/Signup/AdditionalDataView.vue
Labels: bug, unit-tests, code-refactor

#1038 [UXE-2718] feat: integrate import from github with template engine
  src/assets/icons/azionicons.scss
  src/helpers/get-script-runner-image.js
  src/helpers/get-vulcan-presets.js
  src/helpers/index.js
  src/router/routes/import-github-routes/index.js
  src/services/github-services/framework-detector-services.js
  src/services/marketplace-services/list-solutions-service.js
  src/services/script-runner-service/create-script-runner-execution-service.js
  src/services/script-runner-service/index.js
  src/services/template-engine-services/instantiate-template.js
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/services/vulcan-services/get-mode-by-preset-service.js
  src/services/vulcan-services/list-vulcan-presets-service.js
  src/stores/solution-create.js
  src/templates/create-modal-block/index.vue
  src/tests/helpers/get-script-runner-image.test.js
  src/tests/helpers/get-vulcan-presets.test.js
  src/tests/services/github-services/framework-detector-services.test.js
  src/tests/services/version-control-system-integration-services/list-repositories-service.test.js
  src/tests/services/vulcan-services/get-mode-by-preset-service.test.js
  src/tests/services/vulcan-services/list-vulcan-presets-service.test.js
  src/views/CreateNew/CreateView.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: bug, enhancement, unit-tests

#1040 DEPLOY 2024.04.23
  package.json
  src/assets/icons/azionicons.scss
  src/assets/svg/additional-data-illustration.vue
  src/assets/themes/scss/themes/azion-dark/extended-components/_sidebar.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_sidebar.scss
  src/helpers/get-script-runner-image.js
  src/helpers/get-vulcan-presets.js
  src/helpers/index.js
  src/router/routes/import-github-routes/index.js
  src/router/routes/signup-routes/index.js
  src/services/github-services/framework-detector-services.js
  src/services/marketplace-services/list-solutions-service.js
  src/services/script-runner-service/create-script-runner-execution-service.js
  src/services/script-runner-service/index.js
  src/services/signup-services/index.js
  src/services/signup-services/make-update-account-info-service-base-url.js
  src/services/signup-services/update-account-info-service.js
  src/services/template-engine-services/instantiate-template.js
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/services/vulcan-services/get-mode-by-preset-service.js
  src/services/vulcan-services/list-vulcan-presets-service.js
  src/stores/solution-create.js
  src/templates/action-bar-block/go-back.vue
  src/templates/action-bar-block/index.vue
  src/templates/create-drawer-block/index.vue
  src/templates/create-modal-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/profile-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/templates/template-engine-block/index.vue
  src/tests/helpers/get-script-runner-image.test.js
  src/tests/helpers/get-vulcan-presets.test.js
  src/tests/services/github-services/framework-detector-services.test.js
  src/tests/services/signup-services/update-account-info-service.test.js
  src/tests/services/version-control-system-integration-services/list-repositories-service.test.js
  src/tests/services/vulcan-services/get-mode-by-preset-service.test.js
  src/tests/services/vulcan-services/list-vulcan-presets-service.test.js
  src/utils/errorHandlingTracker.js
  src/views/CreateNew/CreateView.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeFirewall/CreateView.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
  src/views/Login/LoginView.vue
  src/views/Signup/AdditionalDataView.vue
Labels: DEPLOY

#1045 [UXE-2885] fix: add method to verify error_description query in login url
  src/templates/sign-in-block/index.vue
Labels: bug

#1044 [NO-ISSUE] fix: remove vite vulcan preset and added default root directory value
  src/helpers/get-vulcan-presets.js
  src/router/routes/import-github-routes/index.js
  src/tests/helpers/get-vulcan-presets.test.js
  src/tests/services/script-runner-services/load-script-runner-execution-results-service.test.js
  src/views/CreateNew/DeployView.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: bug

#1043 [UXE-2855] fix: requires delivery protocol with https
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1048 [NO-ISSUE] fix: verify if variables exist in import from github journey
  src/views/CreateNew/DeployView.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: bug

#1049 [UXE-2830] fix: default rule presents set origin behavior with empty value
  src/services/edge-application-origins-services/list-origins-service.js
Labels: bug, categorized

#1046 [NO-ISSUE] fix: responsive dialogs
  src/assets/themes/scss/themes/azion-dark/extended-components/_dialog.scss
  src/assets/themes/scss/themes/azion-light/extended-components/_dialog.scss
  src/templates/create-modal-block/create-modal-block-loading-state.vue
  src/templates/create-modal-block/index.vue
  src/templates/dialog-unsaved-block/index.vue
  src/templates/dialogs-block/dialog-onboarding-scheduling.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/navbar-block/create.vue
Labels: theming, code-refactor

#1051 [NO-ISSUE] chore: improve project version from 1.14.0 to 1.14.1
  package.json
  src/views/ImportGitHub/ImportGithubView.vue
Labels: project version

#1054 [UXE-2855] fix: requires delivery protocol with https
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#1055 [UXE-2886] fix: add redirect to real time metrics
  src/views/CreateNew/DeployView.vue
Labels: bug

#1057 [NO-ISSUE] chore: improve project version from 1.14.1 to 1.14.2
  package.json
  src/tests/helpers/generate-formatted-timestamp.test.js
Labels: project version

#1060 [UXE-2892] fix: save button not enabled in some templates
  src/templates/template-engine-block/index.vue
Labels: bug

#1062 [NO-ISSUE] fix: ensure to update account job role after additional data submitted
  src/services/signup-services/update-account-info-service.js
  src/templates/signup-block/additional-data-form-block.vue
  src/tests/services/signup-services/update-account-info-service.test.js
Labels: bug

#1061 [UXE-2896] Change color for $inputPlaceholderTextColor token
  src/assets/themes/scss/themes/azion-dark/variables/_form.scss
  src/assets/themes/scss/themes/azion-light/variables/_form.scss
Labels: theming

#1063 [UXE-2688] feat: add animation to additional data
  package.json
  src/assets/animations/additional-data-dark.json
  src/assets/animations/additional-data-light.json
  src/services/signup-services/list-additional-data-info-service.js
  src/templates/signup-block/additional-data-form-block.vue
  src/tests/services/signup-services/list-additional-data-info-service.test.js
  src/views/Signup/AdditionalDataView.vue
  yarn.lock
Labels: enhancement, unit-tests, code-refactor

#1067 [UXE-2809] fix: onsaved dialog being opened even after saving changes
  src/templates/edit-form-block/index.vue
  src/views/EdgeApplications/EditView.vue
Labels: bug, categorized

#1068 [UXE-2811] fix: payload value to edit and create an edge application
  src/services/edge-application-services/create-edge-application-service.js
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-application-services/load-edge-application-service.js
  src/tests/services/edge-application-services/create-edge-application-service.test.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: bug, unit-tests

#1069 [UXE-2774] fix: reset loading state on login mount
  src/templates/sign-in-block/index.vue
Labels: bug

#1070 [NO-ISSUE] chore: improve project version from 1.14.2 to 1.14.3
  package.json
Labels: project version

#1071 DEPLOY 2024.04.24
  package.json
  src/assets/animations/additional-data-dark.json
  src/assets/animations/additional-data-light.json
  src/assets/themes/scss/themes/azion-dark/variables/_form.scss
  src/assets/themes/scss/themes/azion-light/variables/_form.scss
  src/services/edge-application-services/create-edge-application-service.js
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-application-services/load-edge-application-service.js
  src/services/signup-services/list-additional-data-info-service.js
  src/services/signup-services/update-account-info-service.js
  src/templates/edit-form-block/index.vue
  src/templates/sign-in-block/index.vue
  src/templates/signup-block/additional-data-form-block.vue
  src/templates/template-engine-block/index.vue
  src/tests/services/edge-application-services/create-edge-application-service.test.js
  src/tests/services/edge-application-services/edit-edge-application-service.test.js
  src/tests/services/signup-services/list-additional-data-info-service.test.js
  src/tests/services/signup-services/update-account-info-service.test.js
  src/views/CreateNew/DeployView.vue
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/Signup/AdditionalDataView.vue
  yarn.lock
Labels: DEPLOY

#1073 [NO-ISSUE] feat: added root directory env to template engine and added some regex to invalid paths
  src/services/vulcan-services/list-vulcan-presets-service.js
  src/tests/services/vulcan-services/list-vulcan-presets-service.test.js
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: enhancement, code-refactor

#1074 [NO-ISSUE] refactor: removed static name of import github template card
  src/templates/create-modal-block/index.vue
Labels: code-refactor

#1075 [NO-ISSUE] fix: default value of tls version on change the delivery protocol
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: bug

#1076 [NO-ISSUE] feat: add azion samples link to fork at GitHub form
  src/templates/create-form-block/form-horizontal.vue
  src/views/CreateNew/DeployView.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
Labels: enhancement

#1077 chore: improve project version from 1.14.3 to 1.14.4
  package.json
Labels: project version

#1079 [UXE-2774] fix: reset page state if page is cached by browser
  src/templates/sign-in-block/index.vue
  src/templates/social-idps-block/index.vue
Labels: bug

#1080 [NO-ISSUE] fix: send user to home view even on request error
  src/templates/signup-block/additional-data-form-block.vue
Labels: bug

#1081 [UXE-2432] fix: remove tag event on the edge firewall
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#1084 [UXE-2578] refactor: hide frame preview for lua functions
  src/views/EdgeFunctions/EditView.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
  src/views/EdgeFunctions/components/code-editor.vue
  src/views/EdgeFunctions/components/mobile-code-preview.vue
Labels: code-refactor

#1082 [UXE-2806] fix: added a default value for ttl field in edge dns records field
  src/tests/services/edge-dns-records-services/create-records-service.test.js
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
Labels: bug

#1086 [UXE-2537] fix: displaying the list of entries in idns records
  src/services/edge-dns-records-services/list-records-service.js
  src/tests/services/edge-dns-records-services/list-records-service.test.js
  src/views/EdgeDNS/EditView.vue
Labels: bug

#1085 [UXE-2539] refactor: remove changelogs from help center and add release notes hyperlink
  src/templates/help-center-block/index.vue
Labels: code-refactor

#1087 [UXE-2879] fix: adjust breakpont signup and additional data
  src/views/Signup/AdditionalDataView.vue
  src/views/Signup/SignupView.vue
Labels: bug, categorized

#1088 [UXE-2539] fix: remove typo from release notes menu
  src/templates/help-center-block/index.vue
Labels: bug

#1089 [NO-ISSUE] fix: remove typo in release notes
  src/templates/help-center-block/index.vue
Labels: bug

#1090 [UXE-2817] fix: Creating Allowed Rule through Tuning is creating with wrong ruleId
  src/services/waf-rules-services/list-waf-rules-tuning-attacks-service.js
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#1092 [UXE-2812] fix: adjust radio inputs with unexpected behavior
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: bug
