Repository aziontech/azion-console-kit, pull requests merged in 2025-01, with the labels that each got.

#2051 [UXE-5976] fix: correct typo in 'does not start with' label on edge firewall
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#2053 [UXE-5739] Fix: adjusting the layout of the buttons on the empty block edge node
  src/templates/empty-results-block/empty-edge-node.vue
  src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
Labels: bug, code-refactor

#2008 [UXE-5885] refactor: update WAF rules service to use API v4 endpoint (Create/Update/Delete)
  src/router/routes/waf-rules-routes/index.js
  src/services/waf-rules-services/v4/clone-waf-rules-service.js
  src/services/waf-rules-services/v4/create-waf-rules-service.js
  src/services/waf-rules-services/v4/delete-waf-rules-service.js
  src/services/waf-rules-services/v4/edit-waf-rules-service.js
  src/services/waf-rules-services/v4/index.js
  src/services/waf-rules-services/v4/list-waf-rules-service.js
  src/services/waf-rules-services/v4/load-waf-rules-service.js
  src/services/waf-rules-services/v4/make-waf-rules-base-url.js
  src/tests/services/waf-rules-services/v4/create-waf-rules-service.test.js
  src/tests/services/waf-rules-services/v4/delete-waf-rules-service.test.js
  src/tests/services/waf-rules-services/v4/edit-waf-rules-service.test.js
  src/tests/services/waf-rules-services/v4/load-waf-rules-service.test.js
  src/tests/services/waf-rules-services/v4/make-waf-rules-make-base-url.test.js
Labels: do-not-merge, api-v4-migration

#2054 [UXE-5951] fix: prevent drawer closure after edge application rules engine edition fail
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
Labels: bug

#2048 [UXE-5366] fix: standardize edge functions titles to display item names instead of product names
  src/views/EdgeFunctions/EditView.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: enhancement

#2047 [UXE-4724] fix: capture groups input gaps
  src/services/waf-rules-services/v4/create-waf-rules-service.js
  src/services/waf-rules-services/v4/edit-waf-rules-service.js
  src/templates/form-fields-inputs/fieldText.vue
  src/tests/services/waf-rules-services/v4/edit-waf-rules-service.test.js
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#2031 [UXE-5631] feat: auto focus input to mfa/authentication page
  src/templates/mfa-authenticate-block/index.vue
Labels: enhancement

#2029 [UXE-5572] feat: [edit/create domain] edge firewall dropdown with clear function
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: enhancement

#2045 [UXE-5824] fix: real-time-purge route name conflict
  src/router/routes/real-time-purge/index.js
Labels: bug

#2057 [UXE-5981] test: remove clipboard asserts from edge pulse test
  cypress/e2e/edge-pulse/copy-tags-edge-pulse.cy.js
Labels: e2e tests

#2049 [UXE-5005] fix: empty links integrations marketplace
  src/helpers/azion-documentation-window-opener.js
  src/helpers/index.js
  src/router/routes/marketplace-routes/index.js
  src/tests/helpers/azion-documentation-window-opener.test.js
  src/views/Marketplace/SolutionView.vue
Labels: bug

#2056 [UXE-5802] fix: add json validation to edge application and edge firewall function instance arguments field
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFunctions/components/code-editor.vue
Labels: bug

#2032 [UXE-5045] fix: remove origin key from origin creation via drawer
  cypress/e2e/edge-application/add-origin.cy.js
  cypress/e2e/edge-application/edit-origin.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/templates/dialog-copy-key/index.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: enhancement

#2062 [NO-ISSUE] test: add wait for api response before clicking in origins dropdown
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
Labels: e2e tests

#2064 [UXE-5935] test: remove wait for api respose and use assert in loading state instead
  cypress/e2e/account-settings/update-address.cy.js
  cypress/e2e/your-settings/edit-user-phone.cy.js
  cypress/support/selectors/view-selectors/account-settings.js
Labels: e2e tests

#2072 [UXE-5342] fix: adjust social login redirection to bypass MFA prompt for accounts using social login
  src/helpers/account-handler.js
  src/router/routes/switch-account-routes/index.js
Labels: experimental-changes

#2075 [UXE-6069] fix: add account owner option to UI and adjust team listing behavior in view users
  src/router/routes/switch-account-routes/index.js
  src/services/users-services/list-teams-service.js
  src/tests/services/users-services/list-teams-service.test.js
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: bug, unit-tests

#2076 [UXE-6073] fix: edit data stream in account owner
  src/stores/account.js
  src/views/DataStream/EditView.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/ListView.vue
Labels: bug

#2079 DEPLOY 2025-01-21
  src/helpers/account-handler.js
  src/router/routes/switch-account-routes/index.js
  src/services/users-services/list-teams-service.js
  src/stores/account.js
  src/tests/services/users-services/list-teams-service.test.js
  src/views/DataStream/EditView.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/ListView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: DEPLOY

#2080 [NO-ISSUE] chore: update version to 1.31.2
  package.json
Labels: project version

#2073 [UXE-6010] Feat: migrate create domains to v4
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/e2e/domains/create-domain-lets-encrypt.cy.js
  cypress/e2e/domains/create-domain-mtls.cy.js
  cypress/e2e/domains/edit-domain.cy.js
  cypress/e2e/purge/create-purge-domain.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/router/routes/domains-routes/index.js
  src/services/digital-certificates-services/v4/list-digital-certificates-dropdown-service.js
  src/services/domains-services/v4/create-domain-service.js
  src/services/domains-services/v4/index.js
  src/services/domains-services/v4/list-domain-service.js
  src/services/domains-services/v4/make-domains-base-url.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-dropdown-service.test.js
  src/tests/services/domains-services/v4/create-domain-service.test.js
  src/tests/services/domains-services/v4/make-domains-base-url.test.js
  src/views/Domains/CreateView.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
Labels: enhancement

#2082 [UXE-6014] feat: add query for disabled redirect to console
  src/views/Home/HomeView.vue
Labels: enhancement

#2084 DEPLOY 2025-01-23
  package.json
  src/views/Home/HomeView.vue
Labels: DEPLOY

#2078 [UXE-6071] fix: send payload correctly when change from load balancer to single origin
  cypress/e2e/edge-application/edit-origin.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: bug

#2061 [UXE-6003] feat: migrate network list delete to v4
  src/router/routes/network-lists-routes/index.js
  src/services/network-lists-services/v4/delete-network-list-service.js
  src/services/network-lists-services/v4/index.js
  src/tests/services/network-lists-services/v4/delete-network-list-service.test.js
  src/tests/services/network-lists-services/v4/list-network-list-service.test.js
Labels: enhancement

#2060 [UXE-6001] feat: migrate network-list create to v4
  src/router/routes/network-lists-routes/index.js
  src/services/network-lists-services/v4/create-network-list-service.js
  src/services/network-lists-services/v4/index.js
  src/tests/services/network-lists-services/v4/create-network-list-service.test.js
Labels: enhancement

#2089 [UXE-6086] fix: handle optional body results to resolved error toast false
  src/services/edge-application-services/load-edge-application-service.js
Labels: bug

#2034 [UXE-5890][UXE-5891] feat: migrate edge functions create/edit pages to api v4
  src/router/routes/edge-functions-routes/index.js
  src/services/edge-functions-services/v4/create-edge-functions-service.js
  src/services/edge-functions-services/v4/edit-edge-functions-service.js
  src/services/edge-functions-services/v4/index.js
  src/services/edge-functions-services/v4/load-edge-function-service.js
  src/tests/services/edge-functions-services/v4/create-edge-functions-service.test.js
  src/tests/services/edge-functions-services/v4/edit-edge-functions-service.test.js
  src/tests/services/edge-functions-services/v4/load-edge-function-service.test.js
  src/views/EdgeFunctions/CreateView.vue
  src/views/EdgeFunctions/Drawer/index.vue
  src/views/EdgeFunctions/EditView.vue
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: api-v4-migration

#2090 [UXE-6067] fix: adjust placeholder to correct format in edge app rules engine
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#2083 [UXE-6002] feat: migrate network lists edit to api v4
  cypress/e2e/network-lists/create-network-list-asn.cy.js
  cypress/e2e/network-lists/create-network-list-countries.cy.js
  cypress/e2e/network-lists/create-network-list-ip-cidr.cy.js
  cypress/e2e/network-lists/edit-network-list-asn.cy.js
  cypress/e2e/network-lists/edit-network-list-countries.cy.js
  cypress/e2e/network-lists/edit-network-list-ip-cidr.cy.js
  cypress/e2e/network-lists/network-lists.cy.js
  src/router/routes/network-lists-routes/index.js
  src/services/network-lists-services/v4/edit-network-list-service.js
  src/services/network-lists-services/v4/index.js
  src/services/network-lists-services/v4/load-network-list-service.js
  src/tests/services/network-lists-services/v4/edit-network-list-service.test.js
  src/tests/services/network-lists-services/v4/load-network-list-service.test.js
Labels: api-v4-migration

#2092 [UXE-6039] fix: adjust alignment fields of criteria in edge firewall rules engine
  src/templates/form-fields-inputs/fieldDropdown.vue
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#2091 [UXE-6102] fix: improve status parsing and handle optional results in list data stream
  src/services/data-stream-services/list-data-stream-service.js
  src/tests/services/data-stream-services/list-data-stream-service.test.js
Labels: bug

#2096 [UXE-6148] feat: add hide create options flag to create modal block
  src/stores/account.js
  src/templates/create-modal-block/index.vue
Labels: enhancement

#2100 [UXE-6155] fix: list more than 200 edge dns records
  src/services/edge-dns-records-services/list-records-service.js
  src/tests/services/edge-dns-records-services/list-records-service.test.js
Labels: bug

#2104 [UXE-6022] fix: checking if the fields exist in the edge certificates return
  src/services/data-stream-services/list-data-stream-service.js
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
Labels: bug

#2105 DEPLOY 2025-01-29 2
  src/services/data-stream-services/list-data-stream-service.js
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/services/edge-dns-records-services/list-records-service.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
  src/tests/services/edge-dns-records-services/list-records-service.test.js
Labels: DEPLOY

#2098 [UXE-6011] feat: migrate delete domain to v4 api
  src/router/routes/domains-routes/index.js
  src/services/domains-services/v4/delete-domain-service.js
  src/services/domains-services/v4/index.js
  src/tests/services/domains-services/v4/delete-domain-service.test.js
Labels: enhancement

#2107 [UXE-6217] fix: args is not being loaded in edge firewall and edge app
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
Labels: bug

#2109 chore: upgrade project version from 1.31.2 to 1.31.3
  package.json
Labels: project version

#2108 DEPLOY 2025-01-30
  package.json
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
Labels: DEPLOY

#2110 [UXE-6010] fix: create and edit workload after validation
  src/services/domains-services/v4/create-domain-service.js
  src/services/domains-services/v4/edit-domain-service.js
  src/services/domains-services/v4/load-domain-service.js
  src/tests/services/domains-services/v4/create-domain-service.test.js
  src/tests/services/domains-services/v4/edit-domain-service.test.js
Labels: code-refactor

#2099 [UXE-6007] fix: Billing/Payment - add message to alert user to complete address
  src/helpers/account-data.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/templates/add-payment-method-block/index.vue
  src/views/AccountSettings/AccountSettingsView.vue
  src/views/Billing/Drawer/DrawerPaymentMethod.vue
Labels: bug

#2114 [UXE-6243] test: fix edit origin flaky test
  cypress/e2e/edge-application/edit-origin.cy.js
Labels: e2e tests

#2094 [UXE-5765] feat: migrate edge dns zone deletion to api v4
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-services/v4/delete-edge-dns-zone-service.js
  src/services/edge-dns-services/v4/index.js
  src/tests/services/edge-dns-services/v4/delete-edge-dns-zone-service.test.js
Labels: api-v4-migration
