Repository aziontech/azion-console-kit, pull requests merged in 2025-05, with the labels that each got.

#2395 [UXE-7098] feat: add new edge connectors
  src/router/routes/edge-connectors-routes/index.js
  src/services/edge-connectors/create-edge-connectors-service.js
  src/services/edge-connectors/index.js
  src/tests/services/sidebar-menus-services/list-sidebar-menus-service.test.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
  src/views/EdgeConnectors/ListView.vue
Labels: console-measurements

#2396 [UXE-7132] feat: added list edge connectors in custom pages form
  src/router/routes/custom-pages-routes/index.js
  src/services/edge-connectors/index.js
  src/services/edge-connectors/list-edge-connectors-service.js
  src/services/edge-connectors/make-edge-connectors-base-url.js
  src/views/CustomPages/CreateView.vue
  src/views/CustomPages/EditView.vue
  src/views/CustomPages/FormFields/FormFieldsCustomPages.vue
Labels: enhancement

#2400 [UXE-7181] fix: adjustment in creating WAF rules without further details and path
  cypress/e2e/real-time-events/advanced-filter.cy.js
  cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
Labels: hotfix, e2mock

#2403 [NO-ISSUE] chore: update project version to 1.38.1
  package.json
Labels: project version

#2402 [UXE-7132] refactor: removes outdated status code entry
  src/views/CustomPages/FormFields/FormFieldsCustomPages.vue
Labels: code-refactor

#2404 DEPLOY 2025-05-06
  cypress/e2e/real-time-events/advanced-filter.cy.js
  cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
  package.json
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
Labels: DEPLOY

#2397 [UXE-7158] feat: adjust timestamp in function instance for Edge App
  src/services/edge-application-functions-services/list-edge-application-functions-service.js
  src/services/edge-application-functions-services/v4/list-edge-functions-service.js
  src/tests/services/edge-application-functions-services/list-edge-application-functions-service.test.js
  src/tests/services/edge-application-functions-services/list-edge-functions-service.test.js
  src/tests/services/edge-application-functions-services/list-functions-service.test.js
  src/tests/services/edge-application-functions-services/load-function-service.test.js
  src/tests/services/edge-application-functions-services/v4/list-edge-functions-service.test.js
  src/tests/services/edge-firewall-functions-services/list-functions-service.test.js
  src/tests/services/edge-firewall-functions-services/load-function-service.test.js
  src/tests/services/edge-firewall-functions-services/v4/load-function-service.test.js
  src/views/EdgeApplicationsFunctions/ListView.vue
Labels: enhancement

#2401 [UXE-7177] fix: Image Processor product not visible on Billing
  src/services/billing-services/index.js
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
  src/tests/services/billing-services/list-service-and-products-changes-accounting-service.test.js
Labels: bug, code-refactor

#2406 [UXE-7150] feat: add custom pages dropdown to workloads form
  src/router/routes/workload-routes/index.js
  src/services/custom-pages-services/v4/index.js
  src/services/custom-pages-services/v4/list-custom-pages-service.js
  src/services/custom-pages-services/v4/load-custom-pages-services.js
  src/services/custom-pages-services/v4/make-custom-pages-base-url.js
  src/services/workload-deployment-service/edit-workload-deployment-service.js
  src/services/workload-deployment-service/list-workload-deployment-service.js
  src/views/Workload/DeploymentView.vue
  src/views/Workload/FormFields/FormFieldsEditWorkload.vue
  src/views/Workload/TabsView.vue
Labels: enhancement

#2408 [UXE-7057] fix: difficulty in making the user the owner of the account
  cypress/e2e/users-management/create-user-owner.cy.js
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: bug

#2409 [UXE-7208] fix: introduces unescaping and try-catch to handle JSON parsing in real time purge list
  src/services/real-time-purge/list-real-time-purge-service.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
Labels: bug

#2407 [UXE-7095] fix: adjustments found in validation
  src/composables/user-flag.js
  src/helpers/azion-documentation-catalog.js
  src/router/hooks/guards/flagGuard.js
  src/router/routes/edge-connectors-routes/index.js
  src/services/edge-connectors/create-edge-connectors-service.js
  src/services/edge-connectors/edit-edge-connectors-service.js
  src/services/edge-connectors/list-edge-connectors-service.js
  src/services/edge-connectors/load-edge-connectors-service.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/EditView.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
  src/views/EdgeConnectors/ListView.vue
Labels: bug

#2419 [UXE-7211] refactor: remove productVersion field from edge connectors forms
  src/assets/images/connectors.gif
  src/services/edge-connectors/load-edge-connectors-service.js
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/EditView.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
Labels: code-refactor

#2422 [UXE-7128] feat: refactor behavior options to use dynamic function
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: console-measurements

#2417 [UXE-7150] feat: add Custom Pages selector in Workload Deployments screen
  src/services/custom-pages-services/v4/list-custom-pages-service.js
  src/views/Workload/FormFields/FormFieldsEditWorkload.vue
Labels: enhancement

#2426 [UXE-7240] feat: Migrate to Edge Connector when using Edge App v4 API
  cypress/e2e/edge-application/accordion/create-all-steps-done.cy.js
  cypress/e2e/edge-application/accordion/create-edge-connector.cy.js
  cypress/e2e/edge-application/accordion/create-origin.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-cache-policy.cy.js
  cypress/support/selectors.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-connectors/create-edge-connectors-service.js
  src/views/EdgeApplications/Config/ConfigView.vue
  src/views/EdgeApplications/Config/EdgeConnectorApplication.vue
  src/views/EdgeApplications/Config/OriginEdgeApplcation.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
Labels: enhancement

#2425 [NO-ISSUE] refactor: Edge Connector - adjust validations
  cypress/e2mock/edge-connectors/create-edge-connectors.cy.js
  cypress/support/selectors/product-selectors/edge-connectors.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/EditView.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
Labels: code-refactor

#2427 [UXE-7184] feat: custom pages in error responses tab flag
  src/assets/images/customPages.gif
  src/views/EdgeApplicationsErrorResponses/EditView.vue
Labels: enhancement

#2428 [UXE-7184] refactor: change Custom Page gif in Edge App with new icons
  src/assets/images/connectors.gif
  src/assets/images/customPages.gif
  src/assets/images/edgeConnectors.gif
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
Labels: code-refactor

#2429 [UXE-7159] feat: implements flag-based API versioning marketplace request
  src/templates/create-modal-block/index.vue
Labels: enhancement

#2420 [UXE-7184] feat: integrates custom pages drawer in workloads
  .github/workflows/package-audit.yaml
  .github/workflows/security-linter.yaml
  cypress/e2e/edge-application/accordion/create-all-steps-done.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-cache-policy.cy.js
  src/services/custom-pages-services/v4/create-custom-pages-services.js
  src/views/CustomPages/Drawer/index.vue
  src/views/CustomPages/FormFields/FormFieldsCustomPages.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
  src/views/Workload/FormFields/FormFieldsEditWorkload.vue
Labels: enhancement

#2424 [UXE-7184] feat: Custom Pages - adds lazy loading for Edge Connectors
  src/router/routes/custom-pages-routes/index.js
  src/templates/create-drawer-block/index.vue
  src/templates/create-form-block/index.vue
  src/templates/edit-drawer-block/index.vue
  src/templates/edit-form-block/index.vue
  src/views/CustomPages/CreateView.vue
  src/views/CustomPages/EditView.vue
  src/views/CustomPages/FormFields/FormFieldsCustomPages.vue
  src/views/EdgeConnectors/Drawer/index.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
Labels: enhancement, code-refactor

#2421 [UXE-7183] feat: created new service adapter and error handling of vcs service
  src/router/routes/create-new-routes/index.js
  src/router/routes/import-github-routes/index.js
  src/services/v2/adapters/vcs-adapter.js
  src/services/v2/base/abortManager.js
  src/services/v2/base/httpClient.js
  src/services/v2/base/httpService.js
  src/services/v2/base/httpServiceFactory.js
  src/services/v2/index.js
  src/services/v2/utils/buildQueryParams.js
  src/services/v2/utils/errorHandler.js
  src/services/v2/utils/index.js
  src/services/v2/vcs-service.js
  src/services/version-control-system-integration-services/index.js
  src/services/version-control-system-integration-services/list-integrations-service.js
  src/services/version-control-system-integration-services/list-platforms-service.js
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/services/version-control-system-integration-services/make-version-control-system-base-url.js
  src/services/version-control-system-integration-services/post-callback-url-service.js
  src/templates/template-engine-block/index.vue
  src/templates/template-engine-block/oauth-github.vue
  src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
  src/tests/services/version-control-system-integration-services/list-platforms-service.test.js
  src/tests/services/version-control-system-integration-services/list-repositories-service.test.js
  src/tests/services/version-control-system-integration-services/post-callback-url-service.test.js
  src/views/CreateNew/CreateView.vue
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
  src/views/Marketplace/SolutionView.vue
Labels: enhancement

#2414 [UXE-6925] feat: Real-Time Events - format json in the stacktrace and requestData fields
  src/helpers/build-summary.js
  src/views/RealTimeEvents/Drawer/tableEvents.vue
Labels: enhancement

#2433 [UXE-7182] feat: update preset automatically on the import github page
  src/services/vulcan-services/list-vulcan-presets-service.js
  src/services/vulcan-services/make-project-samples-base-url.js
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
Labels: enhancement

#2435 [UXE-7184] refactor: edge connector integration with custom pages
  src/views/CustomPages/CreateView.vue
  src/views/CustomPages/Drawer/index.vue
  src/views/CustomPages/FormFields/FormFieldsCustomPages.vue
Labels: code-refactor

#2449 [UXE-7340] feat: adds purge service integration and error handling
  src/services/real-time-purge/create-real-time-purge-service.js
  src/services/real-time-purge/index.js
  src/services/v2/adapters/purge-adapter.js
  src/services/v2/index.js
  src/services/v2/purge-service.js
  src/templates/create-form-block/index.vue
  src/tests/services/real-time-purge/create-real-time-purge.test.js
  src/views/RealTimePurge/CreateView.vue
Labels: enhancement, code-refactor

#2453 [UXE-7334] feat: edge application function service integration and error handling
  cypress/e2e/edge-application/V3/function-instance/create-function-instance.cy.js
  cypress/e2e/edge-application/V3/function-instance/edit-function-instance.cy.js
  cypress/e2e/edge-application/V3/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/function-instance/create-function-instance.cy.js
  cypress/e2e/edge-application/function-instance/edit-function-instance.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  src/helpers/convert-date.js
  src/helpers/index.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-functions-services/create-function-service.js
  src/services/edge-application-functions-services/delete-function-service.js
  src/services/edge-application-functions-services/edit-function-service.js
  src/services/edge-application-functions-services/index.js
  src/services/edge-application-functions-services/list-edge-application-functions-service.js
  src/services/edge-application-functions-services/list-edge-functions-service.js
  src/services/edge-application-functions-services/list-functions-service.js
  src/services/edge-application-functions-services/loader-function-service.js
  src/services/edge-application-functions-services/make-edge-functions-base-url.js
  src/services/edge-application-functions-services/v4/create-function-service.js
  src/services/edge-application-functions-services/v4/delete-function-service.js
  src/services/edge-application-functions-services/v4/edit-function-instance-service.js
  src/services/edge-application-functions-services/v4/index.js
  src/services/edge-application-functions-services/v4/list-edge-functions-options-service.js
  src/services/edge-application-functions-services/v4/list-edge-functions-service.js
  src/services/edge-application-functions-services/v4/load-function-instance-service.js
  src/services/edge-application-functions-services/v4/make-edge-function-base-url.js
  src/services/v2/adapters/edge-application-functions-adapter.js
  src/services/v2/adapters/edge-function-adapter.js
  src/services/v2/edge-application-functions-service.js
  src/services/v2/edge-function-service.js
  src/services/v2/index.js
  src/services/v2/utils/adaptServiceDataResponse.js
  src/tests/services/edge-application-functions-services/create-edge-application-functions-service.test.js
  src/tests/services/edge-application-functions-services/delete-edge-application-functions-service.test.js
  src/tests/services/edge-application-functions-services/list-edge-application-functions-service.test.js
  src/tests/services/edge-application-functions-services/list-edge-functions-service.test.js
  src/tests/services/edge-application-functions-services/list-functions-service.test.js
  src/tests/services/edge-application-functions-services/load-function-service.test.js
  src/tests/services/edge-application-functions-services/v4/delete-function-service.test.js
  src/tests/services/edge-application-functions-services/v4/edge-function-service.test.js
  src/tests/services/edge-application-functions-services/v4/edit-function-instance-service.test.js
  src/tests/services/edge-application-functions-services/v4/list-edge-functions-options-service.test.js
  src/tests/services/edge-application-functions-services/v4/list-edge-functions-service.test.js
  src/tests/services/edge-application-functions-services/v4/load-function-instance-service.test.js
  src/tests/services/edge-application-functions-services/v4/make-edge-application-v4-base-url.test.js
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: console-measurements
