Repository aziontech/azion-console-kit, pull requests merged in 2025-04, with the labels that each got.

#2324 [UXE-6733] fix: prevent query execution when errors are present in the query
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
Labels: bug

#2308 [UXE-5820] feat: save filters change tabs in real time events
  src/templates/advanced-filter/advanced-filter-no-hash.vue
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
Labels: console-measurements

#2335 chore: updated project version to 1.36.0
  package.json
Labels: project version

#2334 DEPLOY 2025-04-01
  cypress/support/commands.js
  package.json
  src/helpers/convert-date.js
  src/layout/components/menu-profile/index.vue
  src/layout/components/navbar/switch-account.vue
  src/services/billing-services/list-payment-history-service.js
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
  src/services/billing-services/list-service-and-products-changes.js
  src/services/billing-services/load-invoice-data-service.js
  src/services/data-stream-services/edit-data-stream-service.js
  src/services/users-services/create-users-service.js
  src/services/users-services/edit-another-user-service.js
  src/templates/advanced-filter/advanced-filter-no-hash.vue
  src/tests/helpers/convert-date.test.js
  src/tests/services/data-stream-services/edit-data-stream-service.test.js
  src/views/Billing/InvoiceDetailsView.vue
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
  src/views/Users/CreateView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: DEPLOY

#2338 [UXE-5325] fix: Real Time Metrics - problem with graphics in a specific range
  src/modules/real-time-metrics/constants/time-intervals.js
  src/modules/real-time-metrics/reports/fill-result-query.js
  src/tests/modules/real-time-metrics/constants/time-interval.test.js
Labels: bug

#2339 [UXE-6853] fix: remove current month bill from list
  cypress/e2e/billing/list-payments.cy.js
  cypress/support/selectors/product-selectors/billing.js
  src/services/billing-services/list-payment-history-service.js
Labels: bug

#2337 [UXE-6858] fix: send allow rule payload correctly to attacks with ruleId 11
  cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
  cypress/fixtures/waf-rules/tuning/available-domains.json
  cypress/fixtures/waf-rules/tuning/details.json
  cypress/fixtures/waf-rules/tuning/tuning-list.json
  cypress/fixtures/waf-rules/waf-list.json
  cypress/fixtures/waf-rules/waf-main-settings.json
  cypress/support/selectors.js
  cypress/support/selectors/product-selectors/waf-tuning.js
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/templates/list-table-block/with-selection-behavior.vue
  src/views/WafRules/Dialog/index.vue
  src/views/WafRules/Drawer/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#2340 [UXE-6736] feat: implements highlight syntax in filter advanced
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/content-editable.vue
Labels: console-measurements

#2348 chore: updated project version to 1.36.1
  package.json
Labels: project version

#2347 Deploy - 2025-04-08
  CODEOWNERS
  cypress/e2e/billing/list-payments.cy.js
  cypress/e2mock/data-stream/data-stream-edit-sampling.cy.js
  cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
  cypress/fixtures/account/info/with_data_streaming_sampling_flag.json
  cypress/fixtures/account/info/without_data_streaming_sampling.json
  cypress/fixtures/data-streaming/data_stream_templates.json
  cypress/fixtures/data-streaming/domains_by_data_stream.json
  cypress/fixtures/data-streaming/list-all.json
  cypress/fixtures/data-streaming/with_sampling_active.json
  cypress/fixtures/waf-rules/tuning/available-domains.json
  cypress/fixtures/waf-rules/tuning/details.json
  cypress/fixtures/waf-rules/tuning/tuning-list.json
  cypress/fixtures/waf-rules/waf-list.json
  cypress/fixtures/waf-rules/waf-main-settings.json
  cypress/support/selectors.js
  cypress/support/selectors/product-selectors/billing.js
  cypress/support/selectors/product-selectors/data-stream.js
  cypress/support/selectors/product-selectors/waf-tuning.js
  package.json
  src/modules/real-time-metrics/constants/time-intervals.js
  src/modules/real-time-metrics/reports/fill-result-query.js
  src/services/billing-services/list-payment-history-service.js
  src/services/data-stream-services/load-data-stream-service.js
  src/services/waf-rules-services/create-waf-rules-allowed-tuning-service.js
  src/templates/list-table-block/with-selection-behavior.vue
  src/tests/modules/real-time-metrics/constants/time-interval.test.js
  src/views/Billing/components/notification-payment.vue
  src/views/DataStream/EditView.vue
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/content-editable.vue
  src/views/WafRules/Dialog/index.vue
  src/views/WafRules/Drawer/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: DEPLOY

#2349 [UXE-6874] fix: edge firewall rule with network lists criteria not loading correctly
  cypress/e2mock/edge-firewall/rules-engine/network-in-list.cy.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
Labels: bug

#2331 [UXE-5991] feat: add delete account option in account settings page
  cypress/e2mock/delete-account.cy.js
  cypress/support/selectors/view-selectors/account-settings.js
  src/services/account-services/delete-account-service.js
  src/services/account-services/index.js
  src/services/account-services/make-account-delete-base-url.js
  src/templates/create-form-block/form-horizontal.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: enhancement

#2351 [UXE-6702] fix: clear form fields after submission feedback
  cypress/e2mock/feedback.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  cypress/support/selectors/block-selectors/header-block.js
  src/layout/components/navbar/feedback.vue
Labels: bug, e2e tests

#2354 [NO-ISSUE] chore: update project version to 1.36.2
  package.json
Labels: project version

#2352 [UXE-6939] fix: allow to remove selected edge firewall in domains edit page
  cypress/e2e/domains/edit-domain.cy.js
  cypress/support/selectors/product-selectors/domains.js
  src/services/domains-services/edit-domain-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/tests/services/domains-services/edit-domain-service.test.js
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: bug

#2355 [UXE-5991] fix: update delete account service to use async/await for improved handling
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: bug

#2353 DEPLOY 2025-04-10
  cypress/e2e/domains/edit-domain.cy.js
  cypress/e2mock/delete-account.cy.js
  cypress/e2mock/edge-firewall/rules-engine/network-in-list.cy.js
  cypress/e2mock/feedback.cy.js
  cypress/support/commands.js
  cypress/support/selectors.js
  cypress/support/selectors/block-selectors/header-block.js
  cypress/support/selectors/product-selectors/domains.js
  cypress/support/selectors/product-selectors/edge-firewall.js
  cypress/support/selectors/view-selectors/account-settings.js
  package.json
  src/layout/components/navbar/feedback.vue
  src/services/account-services/delete-account-service.js
  src/services/account-services/index.js
  src/services/account-services/make-account-delete-base-url.js
  src/services/domains-services/edit-domain-service.js
  src/templates/create-form-block/form-horizontal.vue
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/tests/services/domains-services/edit-domain-service.test.js
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: DEPLOY

#2344 [UXE-6931] fix: enhance AQL operator error handling and update advanced filter mappings
  src/helpers/convert-gql.js
  src/templates/advanced-filter/component/index.js
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/content-editable.vue
Labels: bug

#2357 [UXE-6729] fix: allow to disable large file optimization in tiered cache settings
  cypress/e2e/edge-application/edit-cache-setting.cy.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: bug

#2359 [UXE-6908] refactor: remove unused connection timeout and byte timeout from origin
  src/services/edge-application-origins-services/create-origin-service.js
  src/services/edge-application-origins-services/edit-origin-service.js
  src/tests/services/edge-application-origins-services/create-origin-service.test.js
  src/tests/services/edge-application-origins-services/edit-origin-service.test.js
Labels: code-refactor

#2361 [NO-ISSUE] chore: update project version to 1.37.0
  package.json
Labels: project version

#2350 [UXE-6980] feat: migrate delete data stream to v4
  cypress/e2e/data-stream/delete-data-stream-s3.cy.js
  cypress/support/commands.js
  src/router/routes/data-stream-routes/index.js
  src/services/data-stream-services/v4/delete-data-stream-service.js
  src/services/data-stream-services/v4/index.js
  src/services/data-stream-services/v4/make-data-stream-base-url.js
  src/tests/services/data-stream-services/v4/delete-data-stream-service.test.js
  src/tests/services/data-stream-services/v4/make-data-stream-base-url.test.js
Labels: enhancement, do-not-merge

#2345 [UXE-6879] fix: migrate behavior set of WAF rules to v4/lazy loader component
  cypress/e2e/edge-firewall/create-edge-firewall-waf.cy.js
  cypress/e2mock/waf-rules/waf-rules-tuning.cy.js
  cypress/fixtures/waf-rules/waf-list-second-page.json
  cypress/fixtures/waf-rules/waf-list.json
  cypress/support/selectors/product-selectors/edge-firewall.js
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-rules-engine-services/create-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/edit-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/v4/load-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/v4/parser-utils.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/tests/services/edge-firewall-rules-engine-services/create-edge-firewall-rules-engine-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/edit-edge-firewall-rules-engine-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/v4/create-edge-firewall-rules-engine-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/v4/edit-edge-firewall-rules-engine-service.test.js
  src/tests/services/edge-firewall-rules-engine-services/v4/parser-utils.test.js
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: bug

#2364 [NO ISSUE] fix: remove toast error message 'false' when deleting an entity
  src/templates/list-table-block/dialog/delete-dialog.vue
Labels: bug

#2360 [UXE-6932] feat: add new tests cypress to advanced filter
  cypress/e2e/real-time-events/advanced-filter.cy.js
  cypress/support/e2e.js
  cypress/support/selectors.js
  cypress/support/selectors/product-selectors/real-time-events.js
  package.json
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
  yarn.lock
Labels: console-measurements, e2e tests

#2366 [UXE-6879] Refactor: Return only name and ID when fetching WAF rules
  src/services/waf-rules-services/v4/list-waf-rules-service.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: code-refactor

#2356 [UXE-6979] feat: migrate list data stream to v4
  cypress/e2e/data-stream/delete-data-stream-s3.cy.js
  cypress/e2mock/data-stream/data-stream-edit-sampling.cy.js
  src/router/routes/data-stream-routes/index.js
  src/services/data-stream-services/v4/delete-data-stream-service.js
  src/services/data-stream-services/v4/index.js
  src/services/data-stream-services/v4/list-data-stream-service.js
  src/services/data-stream-services/v4/make-data-stream-sets-base-url.js
  src/tests/services/data-stream-services/v4/delete-data-stream-service.test.js
  src/tests/services/data-stream-services/v4/list-data-stream-service.test.js
  src/views/DataStream/ListView.vue
Labels: enhancement, do-not-merge

#2372 [UXE-6854] feat: add wafEvheaders field to Real Time Events drawer
  cypress/e2mock/real-time-events/http-requests.cy.js
  cypress/fixtures/real-time-events/list-http-requests.json
  cypress/fixtures/real-time-events/load-http-requests-second.json
  cypress/fixtures/real-time-events/load-http-requests.json
  src/services/real-time-events-service/http-request/load-http-request.js
  src/tests/services/real-time-events-service/http-request/load-http-request.test.js
  src/views/RealTimeEvents/Blocks/tab-panel-block.vue
  src/views/RealTimeEvents/Drawer/tableEvents.vue
Labels: console-measurements

#2368 [UXE-6990] feat: implement CLI login support with create personal token
  src/helpers/local-storage-manager.js
  src/helpers/redirect-cli.js
  src/router/hooks/guards/loadingGuard.js
  src/router/hooks/guards/redirectGuard.js
  src/tests/helpers/local-storage-manager.test.js
Labels: enhancement

#2373 [UXE-6986] refactor: remove field MODE and update list presets in page import github
  src/router/routes/import-github-routes/index.js
  src/services/vulcan-services/get-mode-by-preset-service.js
  src/services/vulcan-services/index.js
  src/services/vulcan-services/list-vulcan-presets-service.js
  src/tests/services/vulcan-services/get-mode-by-preset-service.test.js
  src/tests/services/vulcan-services/list-vulcan-presets-service.test.js
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
Labels: enhancement, code-refactor

#2376 [UXE-7147] fix: update current payment for online users in payment history
  src/services/billing-services/list-payment-history-service.js
  src/tests/services/billing-services/list-payment-history-service.test.js
Labels: bug

#2370 [UXE-7059] feat: banner event component
  src/assets/svg/launchweek-logo.vue
  src/helpers/azion-documentation-window-opener.js
  src/layout/index.vue
  src/templates/banner-full-block/index.vue
Labels: do-not-merge, blocks

#2379 [NO-ISSUE] feat: add user flag functionality and integrate flag guard in routing
  src/composables/user-flag.js
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/flagGuard.js
  src/router/hooks/guards/index.js
  src/stores/account.js
Labels: console-measurements

#2378 [UXE-7095] feat: add edge connectors routes and services
  src/helpers/azion-documentation-catalog.js
  src/router/index.js
  src/router/routes/edge-connectors-routes/index.js
  src/services/edge-connectors/index.js
  src/services/edge-connectors/list-edge-connectors-service.js
  src/services/edge-connectors/make-edge-connectors-base-url.js
  src/views/EdgeConnectors/ListView.vue
Labels: console-measurements

#2377 [NO-ISSUE] test: fixed test Teams Permissions to correctly mock the listing
  cypress/e2mock/teams-permissions.cy.js
Labels: e2mock

#2371 [UXE-7046] feat: add list MFA view
  src/helpers/azion-documentation-catalog.js
  src/router/index.js
  src/router/routes/mfa-management-routes/index.js
  src/services/mfa-services/v4/delete-mfa-service.js
  src/services/mfa-services/v4/index.js
  src/services/mfa-services/v4/list-mfa-users-service.js
  src/services/mfa-services/v4/load-user-service.js
  src/services/mfa-services/v4/make-mfa-management-base-url.js
  src/tests/services/mfa-services/v4/delete-mfa-service.test.js
  src/tests/services/mfa-services/v4/list-mfa-users-service.test.js
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/MFAManagement/ListView.vue
Labels: enhancement

#2326 [EDU-6355] refactor: adjust delete dialog message
  src/templates/list-table-block/dialog/delete-dialog.vue
Labels: writing

#2381 [UXE-7097] feat: add delete edge connectors
  src/router/routes/edge-connectors-routes/index.js
  src/services/edge-connectors/delete-edge-connectors-service.js
  src/services/edge-connectors/index.js
  src/services/edge-connectors/list-edge-connectors-service.js
  src/services/edge-connectors/make-edge-connectors-base-url.js
  src/services/sidebar-menus-services/menus.js
  src/views/EdgeConnectors/ListView.vue
Labels: do-not-merge, console-measurements

#2380 [UXE-7130] feat: new custom pages get and delete features
  src/helpers/azion-documentation-catalog.js
  src/router/index.js
  src/router/routes/custom-pages-routes/index.js
  src/services/custom-pages-services/v4/delete-custom-pages-service.js
  src/services/custom-pages-services/v4/index.js
  src/services/custom-pages-services/v4/list-custom-pages-service.js
  src/services/custom-pages-services/v4/make-custom-pages-base-url.js
  src/services/sidebar-menus-services/menus.js
  src/views/CustomPages/ListView.vue
Labels: enhancement

#2382 [UXE-7085] feat: domain string changes for workloads
  src/helpers/handle-text-workload-domain-flag.js
  src/helpers/index.js
  src/helpers/real-time-filters-rules.js
  src/modules/real-time-metrics/filters/load-info-available-filters.js
  src/router/hooks/guards/domainsLimitGuard.js
  src/router/routes/domains-routes/index.js
  src/router/routes/edge-application-routes/index.js
  src/services/domains-services/v4/index.js
  src/services/domains-services/v4/list-domain-service.js
  src/services/domains-services/v4/make-domains-base-url.js
  src/services/sidebar-menus-services/menus.js
  src/services/workloads-services/create-workloads-service.js
  src/services/workloads-services/delete-workloads-service.js
  src/services/workloads-services/edit-workloads-service.js
  src/services/workloads-services/index.js
  src/services/workloads-services/list-workloads-dynamic-fields-service.js
  src/services/workloads-services/list-workloads-service.js
  src/services/workloads-services/load-workloads-service.js
  src/services/workloads-services/make-workloads-base-url.js
  src/templates/advanced-filter/component/fields/multiselect-lazy-loader-filter.vue
  src/templates/create-modal-block/index.vue
  src/tests/helpers/realt-time-filter-rules.test.js
  src/tests/services/domains-services/v4/make-domains-base-url.test.js
  src/tests/services/workloads-services/create-workloads-service.test.js
  src/tests/services/workloads-services/delete-workloads-service.test.js
  src/tests/services/workloads-services/edit-workloads-service.test.js
  src/tests/services/workloads-services/list-workloads-service.test.js
  src/tests/services/workloads-services/list-workloads.test.js
  src/tests/services/workloads-services/load-workloads-service.test.js
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/ListView.vue
  src/views/DigitalCertificates/CreateView.vue
  src/views/EdgeApplications/Config/ConfigView.vue
  src/views/EdgeApplications/Config/WorkloadEdgeApplication.vue
  src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/constants/query-fields.js
  src/views/WafRules/Drawer/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
  src/views/Workload/CreateView.vue
  src/views/Workload/DeploymentView.vue
  src/views/Workload/Dialog/CopyDomainDialog.vue
  src/views/Workload/Drawer/index.vue
  src/views/Workload/EditView.vue
  src/views/Workload/FormFields/FormFieldsCreateDomains.vue
  src/views/Workload/FormFields/FormFieldsEditDomains.vue
  src/views/Workload/FormFields/FormFieldsEditWorkload.vue
  src/views/Workload/ListView.vue
  src/views/Workload/TabsView.vue
Labels: enhancement

#2385 [UXE-6986] revert: remove mock data implementation for Vulcan presets
  src/services/vulcan-services/list-vulcan-presets-service.js
  src/tests/services/vulcan-services/list-vulcan-presets-service.test.js
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
Labels: revert

#2386 [UXE-6924] refactor: improve error handling in edit domain by cnames
  cypress/e2e/domains/edit-domain.cy.js
  src/services/domains-services/edit-domain-service.js
Labels: bug

#2389 [NO-ISSUE] chore: update project version to 1.38.0
  package.json
Labels: project version
