Repository aziontech/azion-console-kit, pull requests merged in 2025-02, with the labels that each got.

#2095 [UXE-5764] feat: migrate edge dns edit page to api v4
  cypress/e2e/edge-dns/create-edge-dns-zone.cy.js
  cypress/e2e/edge-dns/create-record-type-a.cy.js
  cypress/e2e/edge-dns/create-record-type-aaaa.cy.js
  cypress/e2e/edge-dns/create-record-type-aname.cy.js
  cypress/e2e/edge-dns/create-record-type-caa.cy.js
  cypress/e2e/edge-dns/create-record-type-cname.cy.js
  cypress/e2e/edge-dns/create-record-type-ds.cy.js
  cypress/e2e/edge-dns/create-record-type-mx.cy.js
  cypress/e2e/edge-dns/create-record-type-ns.cy.js
  cypress/e2e/edge-dns/create-record-type-ptr.cy.js
  cypress/e2e/edge-dns/create-record-type-srv.cy.js
  cypress/e2e/edge-dns/create-record-type-txt.cy.js
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-services/v4/edit-edge-dn-zone-service.js
  src/services/edge-dns-services/v4/index.js
  src/services/edge-dns-services/v4/load-edge-dns-zone-service.js
  src/tests/services/edge-dns-services/v4/edit-edge-dns-zone-service.test.js
  src/tests/services/edge-dns-services/v4/load-edge-dns-zone-service.test.js
Labels: api-v4-migration

#2117 [UXE-6220] feat: add menu siem to clients bb
  src/layout/components/menu-production/index.vue
  src/services/sidebar-menus-services/menus.js
Labels: console-measurements

#2118 [UXE-6127] feat: add chart top waf threat request by ip
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2115 [UXE-5459] feat: update edge node list view and service import to v4
  src/router/routes/edge-node-routes/index.js
  src/services/edge-node-services/v4/index.js
  src/services/edge-node-services/v4/list-edge-node-service.js
  src/services/edge-node-services/v4/make-edge-node-base-url.js
  src/tests/services/edge-node-services/v4/list-edge-node-service.test.js
  src/views/EdgeNode/ListView.vue
Labels: api-v4-migration

#2112 [UXE-6146] feat: services create edge app api v4
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/e2e/domains/create-domain-lets-encrypt.cy.js
  cypress/e2e/domains/create-domain-mtls.cy.js
  cypress/e2e/domains/edit-domain.cy.js
  cypress/e2e/edge-application/accordion/create-all-steps-done.cy.js
  cypress/e2e/edge-application/accordion/create-associete-domain.cy.js
  cypress/e2e/edge-application/accordion/create-cache-settings.cy.js
  cypress/e2e/edge-application/accordion/create-origin.cy.js
  cypress/e2e/edge-application/add-error-response.cy.js
  cypress/e2e/edge-application/add-origin.cy.js
  cypress/e2e/edge-application/create-device-groups.cy.js
  cypress/e2e/edge-application/edit-cache-setting.cy.js
  cypress/e2e/edge-application/edit-origin.cy.js
  cypress/e2e/edge-application/function-instance/create-function-instance.cy.js
  cypress/e2e/edge-application/function-instance/edit-function-instance.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-cache-policy.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-origin.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine.cy.js
  cypress/e2e/edge-application/rules-engine/edit-rule-engine.cy.js
  cypress/e2e/edge-application/rules-engine/reorder-rules-engine.cy.js
  cypress/e2e/purge/create-purge-domain.cy.js
  cypress/support/selectors/block-selectors/form-fields-block.js
  cypress/support/selectors/product-selectors/edge-application.js
  src/router/routes/edge-application-routes/index.js
  src/services/domains-services/v4/create-domain-service.js
  src/services/edge-application-cache-settings-services/v4/create-cache-settings-service.js
  src/services/workload-deployment-service/edit-workload-deployment-service.js
  src/services/workload-deployment-service/list-workload-deployment-service.js
  src/templates/action-bar-block/action-bar-accordion.vue
  src/templates/action-bar-block/action-bar-skit-config.vue
  src/templates/create-form-block/form-horizontal.vue
  src/views/Domains/Drawer/index.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/EdgeApplications/Config/CacheEdgeApplication.vue
  src/views/EdgeApplications/Config/ConfigView.vue
  src/views/EdgeApplications/Config/DomainEdgeApplication.vue
  src/views/EdgeApplications/Config/OriginEdgeApplcation.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateDomain.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateOrigin.vue
Labels: enhancement

#2124 [UXE-5459] feat: enhance edge node list view with fetch table block
  src/services/edge-node-services/v4/list-edge-node-service.js
  src/tests/services/edge-node-services/v4/make-edge-node-list-base-url.test.js
  src/views/EdgeNode/ListView.vue
Labels: api-v4-migration

#2126 [NO-ISSUE] fix: change success status in edge dns create api response
  src/services/edge-dns-services/v4/create-edge-dns-zones-service.js
  src/tests/services/edge-dns-services/v4/create-edge-dns-zones-service.test.js
Labels: bug

#2125 [UXE-6128] feat: add charts status codes
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2122 [UXE-6266] feat: add origin type live_ingest form to origin pages
  src/services/contract-services/index.js
  src/services/contract-services/load-products-list-service.js
  src/services/edge-application-origins-services/create-origin-service.js
  src/services/edge-application-origins-services/edit-origin-service.js
  src/services/edge-application-origins-services/list-origins-service.js
  src/services/edge-application-origins-services/load-origin-service.js
  src/tests/services/edge-application-origins-services/create-origin-service.test.js
  src/tests/services/edge-application-origins-services/edit-origin-service.test.js
  src/tests/services/edge-application-origins-services/list-origins-service.test.js
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/FormFields/FormFieldsEdgeApplicationsOrigins.vue
Labels: enhancement

#2128 [UXE-6129] feat: add chart average request time
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2130 [UXE-5704] feat: migrate edit edge application to v4
  cypress/e2e/domains/create-domain-edge-application.cy.js
  cypress/e2e/domains/create-domain-lets-encrypt.cy.js
  cypress/e2e/domains/edit-domain.cy.js
  cypress/e2e/edge-application/create-device-groups.cy.js
  cypress/e2e/edge-application/function-instance/create-function-instance.cy.js
  cypress/e2e/edge-application/function-instance/edit-function-instance.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  cypress/e2e/edge-application/rules-engine/edit-rule-engine.cy.js
  src/router/routes/domains-routes/index.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-services/v4/edit-edge-application-service.js
  src/services/edge-application-services/v4/index.js
  src/services/edge-application-services/v4/load-edge-application-service-dropdown.js
  src/services/edge-application-services/v4/load-edge-application-service.js
  src/tests/services/edge-application-services/v4/create-edge-applications-service.test.js
  src/tests/services/edge-application-services/v4/edit-edge-applications-service.test.js
  src/tests/services/edge-application-services/v4/load-edge-application-dropdown-service.test.js
  src/tests/services/edge-application-services/v4/load-edge-applications-service.test.js
  src/views/EdgeApplications/Config/ConfigView.vue
  src/views/EdgeApplications/Drawer/index.vue
  src/views/EdgeApplications/EditView.vue
  src/views/EdgeApplications/FormFields/FormFieldsEditEdgeApplications.vue
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsOrigins/Drawer/index.vue
  src/views/EdgeApplicationsOrigins/ListView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement

#2138 [UXE-6221] feat: add chart request by scheme
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2145 [UXE-6224] feat: add chart top waf request by family attack
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2146 chore: include credentials in chat service request for improved security
  src/modules/azion-ai-chat/services/chat-service.js
Labels: experimental-changes

#2148 [UXE-6225] feat: add chart top waf request by host
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/constants/reports.js
  src/templates/graphs-card-block/components/chart/line-chart.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2137 [UXE-6155] feat: migrate edge dns records list to api v4
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-records-services/v4/index.js
  src/services/edge-dns-records-services/v4/list-records-service.js
  src/services/edge-dns-records-services/v4/make-edge-dns-records-base-url.js
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/tests/services/edge-dns-records-services/v4/list-records-service.test.js
  src/tests/services/edge-dns-records-services/v4/make-edge-dns-records-base-url.test.js
  src/views/EdgeDNS/EditView.vue
Labels: api-v4-migration

#2151 [UXE-6227] feat: add chart top bot traffic
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2143 [NO-ISSUE] fix: Improvements in Edge App Editing After Code Review
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-cache-settings-services/v4/create-cache-settings-service.js
  src/services/edge-application-origins-services/create-origin-service.js
  src/tests/services/edge-application-cache-settings-services/v4/create-cache-settings-service.test.js
  src/views/EdgeApplications/Config/CacheEdgeApplication.vue
  src/views/EdgeApplications/Config/ConfigView.vue
  src/views/EdgeApplications/Config/OriginEdgeApplcation.vue
Labels: code-refactor

#2149 [UXE-6319] feat: migrate edge dns records edit page to api v4
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-records-services/v4/edit-records-service.js
  src/services/edge-dns-records-services/v4/index.js
  src/services/edge-dns-records-services/v4/load-record-service.js
  src/tests/services/edge-dns-records-services/v4/edit-records-service.test.js
  src/tests/services/edge-dns-records-services/v4/load-record-service.test.js
Labels: api-v4-migration

#2150 [UXE-6337] feat: migrate edge dns records deletion to api v4
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-records-services/v4/delete-record-service.js
  src/services/edge-dns-records-services/v4/index.js
  src/tests/services/edge-dns-records-services/v4/delete-record-service.test.js
Labels: api-v4-migration

#2152 [UXE-6228] feat: updated chart request by method
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: console-measurements

#2157 [NO-ISSUE] chore: upgrade gitHub actions cache action to v4
  .github/workflows/eslint.yml
Labels: github-actions

#2153 [UXE-6348] feat: updated chart description
  .github/workflows/eslint.yml
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: console-measurements

#2141 [UXE-6134] feat: add Requests by Status and Upstream
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/templates/graphs-card-block/components/chart/list-chart.vue
  src/templates/list-table-block/graphic.vue
  src/templates/list-table-block/index.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: enhancement

#2160 [NO-ISSUE] fix: implements filter empty values and filter attack chart label
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/templates/graphs-card-block/components/chart/pie-chart.vue
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: bug

#2164 [UXE-6373] fix: adjust check disable invoice details
  src/views/Billing/BillsView.vue
Labels: bug

#2165 [UXE-5949] chore: update Azion CLI version to 2.5.3 in deployment workflows
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
Labels: github-actions, IAC, github_actions

#2167 [NO-ISSUE] fix: adjust filter to support contains and not contains metrics filter
  src/templates/advanced-filter/dialog-filter.vue
Labels: bug

#2156 [UXE-6007] fix: validate account address before adding payment method
  src/helpers/account-data.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/templates/add-payment-method-block/index.vue
  src/views/AccountSettings/AccountSettingsView.vue
  src/views/Billing/Drawer/DrawerPaymentMethod.vue
Labels: bug

#2169 [UXE-6226] feat: Added request breakdown table graphic
  src/modules/real-time-metrics/constants/chart-rules.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/tests/modules/real-time-metrics/constants/chart-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: enhancement

#2139 [UXE-5982] fix: ensure default ordering is set when reloading list table
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
Labels: bug

#2163 [UXE-6358] feat: remove unused files of api v3 edge dns services
  src/router/routes/edge-dns-routes/index.js
  src/services/edge-dns-records-services/create-records-service.js
  src/services/edge-dns-records-services/delete-records-service.js
  src/services/edge-dns-records-services/edit-records-service.js
  src/services/edge-dns-records-services/index.js
  src/services/edge-dns-records-services/list-records-service.js
  src/services/edge-dns-records-services/load-records-service.js
  src/services/edge-dns-records-services/make-edge-dns-records-base-url.js
  src/services/edge-dns-services/create-edge-dns-service.js
  src/services/edge-dns-services/delete-edge-dns-service.js
  src/services/edge-dns-services/edit-edge-dns-service.js
  src/services/edge-dns-services/index.js
  src/services/edge-dns-services/list-edge-dns-service.js
  src/services/edge-dns-services/load-edge-dns-service.js
  src/services/edge-dns-services/make-edge-dns-base-url.js
  src/tests/services/edge-dns-records-services/create-records-service.test.js
  src/tests/services/edge-dns-records-services/delete-records-service.test.js
  src/tests/services/edge-dns-records-services/edit-records-service.test.js
  src/tests/services/edge-dns-records-services/list-records-service.test.js
  src/tests/services/edge-dns-records-services/load-records-service.test.js
  src/tests/services/edge-dns-records-services/make-edge-dns-records-base-url.test.js
  src/tests/services/edge-dns-services/create-edge-dns-service.test.js
  src/tests/services/edge-dns-services/delete-edge-dns-service.test.js
  src/tests/services/edge-dns-services/edit-edge-dns-service.test.js
  src/tests/services/edge-dns-services/list-edge-dns-service.test.js
  src/tests/services/edge-dns-services/load-edge-dns-service.test.js
  src/tests/services/edge-dns-services/make-edge-dns-base-url.test.js
Labels: api-v4-migration

#2174 [UXE-6226] feat: add region column table graphic
  src/modules/real-time-metrics/constants/chart-rules.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/chart-rules.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
Labels: enhancement

#2175 [NO-ISSUE] chore: updated description charts
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: writing

#2181 [UXE-6402] feat: implement banner visibility logic based on FORCE_REDIRECT_TO_CONSOLE flag
  src/stores/account.js
  src/views/Home/HomeView.vue
Labels: enhancement

#2186 [NO-ISSUE] chore: update version to 1.31.6
  package.json
Labels: project version

#2197 DEPLOY 2025-02-18
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  azion.config.cjs
  azion.config.mjs
  azion/production/azion.json
  azion/stage/azion.json
  package.json
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/modules/real-time-metrics/constants/chart-rules.js
  src/modules/real-time-metrics/constants/dashboards.js
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports-texts.js
  src/modules/real-time-metrics/constants/reports.js
  src/modules/real-time-metrics/filters/filter-to-graphql-string.js
  src/modules/real-time-metrics/reports/convert-beholder-to-chart.js
  src/templates/advanced-filter/dialog-filter.vue
  src/templates/graphs-card-block/components/chart/line-chart.vue
  src/templates/graphs-card-block/components/chart/list-chart.vue
  src/templates/graphs-card-block/components/chart/pie-chart.vue
  src/templates/list-table-block/graphic.vue
  src/templates/list-table-block/index.vue
  src/tests/modules/real-time-metrics/constants/chart-rules.test.js
  src/tests/modules/real-time-metrics/constants/dashboards.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/modules/real-time-metrics/reports/fixtures/gql-fixtures.js
  yarn.lock
Labels: DEPLOY

#2182 [UXE-6214] fix: improve GraphQL type handling for complex filter queries
  src/helpers/convert-gql.js
  src/tests/helpers/convert-gql.test.js
Labels: bug

#2179 [UXE-5920] fix: parse correctly git hub installation callback post errors
  src/services/version-control-system-integration-services/post-callback-url-service.js
  src/templates/template-engine-block/index.vue
Labels: bug

#2198 [NO-ISSUE] chore: bump version to 1.31.7
  package.json
Labels: project version

#2190 [UXE-6407] fix: redirect to list page when click on the cancel button
  src/views/Domains/DeploymentView.vue
  src/views/Domains/TabsView.vue
Labels: code-refactor

#2183 [UXE-6404] fix: reload edge application create page when enter key is pressed
  src/templates/form-fields-inputs/fieldText.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
Labels: code-refactor

#2191 [UXE-6411] refactor: add null value to cipher suite option and minimum tls version
  src/services/domains-services/v4/create-domain-service.js
  src/services/domains-services/v4/edit-domain-service.js
  src/services/domains-services/v4/load-domain-service.js
  src/tests/services/domains-services/v4/edit-domain-service.test.js
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: code-refactor

#2180 [UXE-6389] Fix: disable browser back in the edge app config page
  src/helpers/browser-back-button.js
  src/helpers/index.js
  src/templates/dialog-unsaved-block/index.vue
  src/tests/helpers/browser-back-button.test.js
Labels: code-refactor

#2202 [NO-ISSUE] refactor: remove banner for redirect rtm
  src/views/Home/HomeView.vue
  vulcan.config.js
Labels: code-refactor

#2203 [NO-ISSUE] chore: add rules engine manually in IAC
  azion/production/azion.json
Labels: IAC

#2200 [UXE-6422] test: fix digital certificate status flag assertion selector
  cypress/support/selectors/block-selectors/list-table-block.js
Labels: e2e tests

#2171 [UXE-6024] refactor: improve data volume formatting with new calculation method
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/templates/graphs-card-block/components/chart/line-chart.vue
Labels: bug, enhancement

#2205 DEPLOY 2025-02-20
  azion/production/azion.json
  cypress/support/selectors/block-selectors/list-table-block.js
  package.json
  src/helpers/convert-gql.js
  src/modules/real-time-metrics/chart/format-c3-graph-props.js
  src/services/version-control-system-integration-services/post-callback-url-service.js
  src/templates/graphs-card-block/components/chart/line-chart.vue
  src/templates/template-engine-block/index.vue
  src/tests/helpers/convert-gql.test.js
  src/views/Home/HomeView.vue
  vulcan.config.js
Labels: DEPLOY

#2206 [NO-ISSUE] chore: add debug flag to deployment command in production workflow
  .github/workflows/deploy-production.yml
Labels: IAC

#2209 [NO-ISSUE] feat: add gzip enable rule to rules engine configuration
  azion/production/azion.json
Labels: IAC

#2210 DEPLOY 2025-02-21 2
  azion/production/azion.json
Labels: DEPLOY

#2211 [NO-ISSUE] refactor: remove obsolete gzip enable rules from configuration
  azion/production/azion.json
Labels: IAC

#2208 [UXE-6422] chore: add variables deletion to cleanup action
  scripts/cleanup.js
Labels: e2e tests

#2214 [NO-ISSUE] fix: enhance messaging for product access with WebSocket support
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-functions-services/edit-edge-functions-service.js
Labels: bug

#2215 [UXE-6467] fix: allow account settings access during payment review
  src/router/hooks/guards/billingGuard.js
Labels: bug

#2216 DEPLOY 2025-02-21 (4)
  scripts/cleanup.js
  src/router/hooks/guards/billingGuard.js
  src/services/edge-application-services/edit-edge-application-service.js
  src/services/edge-functions-services/edit-edge-functions-service.js
Labels: DEPLOY

#2213 [NO-ISSUE] refactor: enhance stage environment handling for origin cities
  azion.config.mjs
  vite.config.js
Labels: IAC

#2193 [UXE-6354] feat: add total records found tag in waf rules tunning page
  src/services/waf-rules-services/list-waf-rules-tuning-service.js
  src/tests/services/waf-rules-services/list-waf-rules-tuning-service.test.js
  src/views/WafRules/ListWafRulesTuning.vue
Labels: enhancement

#2194 [UXE-6359] feat: add export to csv button to waf rules tuning page
  src/templates/list-table-block/with-selection-behavior.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: enhancement

#2218 [UXE-6354] fix: reset total records value when there is no domain selected
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#2220 [UXE-6335] fix: fix format filter paramenter
  src/helpers/convert-gql.js
Labels: code-refactor

#2069 [UXE-6030] feat: update Real-Time Metrics, Events, Billing, and Accounting Services to API v4 with Origin Configuration Changes
  azion.config.mjs
  cypress/e2mock/activity-history.cy.js
  src/helpers/get-static-urls-by-environment.js
  src/services/axios/AxiosHttpClientAdapter.js
  src/services/axios/AxiosHttpClientSignalDecorator.js
  src/services/axios/makeEventsApi.js
  src/services/billing-services/list-payment-history-service.js
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
  src/services/billing-services/list-service-and-products-changes.js
  src/services/billing-services/load-current-invoice-service.js
  src/services/billing-services/load-invoice-data-service.js
  src/services/billing-services/load-invoice-last-updated-service.js
  src/services/billing-services/load-your-service-plan-service.js
  src/services/billing-services/make-accounting-base-url.js
  src/services/billing-services/make-billing-base-url.js
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-dns/load-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/load-fields-real-time-events-data.js
  src/services/real-time-events-service/make-real-time-events-service.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/services/real-time-metrics-services/load-real-time-metrics-data.js
  src/services/real-time-metrics-services/make-beholder-base-url.js
  src/tests/helpers/events-playground-opener.test.js
  src/tests/helpers/get-static-urls-by-environment.test.js
  src/tests/helpers/metrics-playground-opener.test.js
  src/tests/services/billing-services/list-payment-history-service.test.js
  src/tests/services/billing-services/load-your-service-plan-service.test.js
  src/tests/services/billing-services/make-billing-base-url.test.js
  src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
  src/tests/services/real-time-events-service/activity-history/load-activity-history.test.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/data-stream/load-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-dns/load-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions-console/load-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/edge-functions/load-edge-functions.test.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
  src/tests/services/real-time-events-service/http-request/load-http-request.test.js
  src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
  src/tests/services/real-time-events-service/image-processor/load-image-processor.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
  src/tests/services/real-time-events-service/tiered-cache/load-tiered-cache.test.js
  src/tests/services/real-time-metrics-services/load-real-time-metrics-data.test.js
  src/tests/services/real-time-metrics-services/make-beholder-base-url.test.js
  vite.config.js
Labels: unit-tests, api-v4-migration

#2222 chore: upgrade from version-1.31.9 to version-1.32.0
  package.json
  src/tests/services/real-time-events-service/get-total-records.test.js
Labels: project version

#2223 [NO-ISSUE] chore: sync with azion cli for iac update
  azion/stage/azion.json
Labels: IAC

#2224 [NO-ISSUE] chore: remove GraphQL Billing and Accounting route configurations
  azion/stage/azion.json
Labels: IAC

#2225 [NO-ISSUE] fix: update getTotalRecords service with baseURL configuration
  src/services/real-time-events-service/get-total-records.js
  src/tests/services/real-time-events-service/get-total-records.test.js
Labels: bug

#2226 [NO-ISSUE] chore: add API Version 4 routing configuration
  azion/production/azion.json
Labels: IAC

#2227 DEPLOY 2025-02-25 2
  azion/production/azion.json
  src/services/real-time-events-service/get-total-records.js
  src/tests/services/real-time-events-service/get-total-records.test.js
Labels: DEPLOY

#2192 [UXE-6131] feat: standardize error handling in load services with extractApiError
  src/services/digital-certificates-services/v4/load-digital-certificates-service.js
  src/services/edge-application-cache-settings-services/v4/load-cache-settings-service.js
  src/services/edge-application-device-groups-services/v4/load-device-group-service.js
  src/services/edge-application-functions-services/v4/load-function-instance-service.js
  src/services/edge-application-rules-engine-services/v4/load-rules-engine-service.js
  src/services/edge-application-services/v4/load-edge-application-service.js
  src/services/edge-dns-records-services/v4/load-record-service.js
  src/services/edge-dns-services/v4/load-edge-dns-zone-service.js
  src/services/edge-functions-services/v4/load-edge-function-service.js
  src/services/network-lists-services/v4/load-network-list-service.js
  src/templates/edit-form-block/index.vue
  src/tests/services/digital-certificates-services/v4/load-digital-certificates-service.test.js
Labels: code-refactor

#2022 [EDU-5813] chore: adjust description and placeholder - Object Key prefix in Data Stream
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
Labels: writing

#2228 [NO-ISSUE] chore: fix clean up action timeout to be executed between resources delete
  scripts/cleanup.js
Labels: github-actions

#2201 [UXE-6322] feat: add new properties for identify tracking
  src/App.vue
Labels: code-refactor
