Repository aziontech/azion-console-kit, pull requests merged in 2025-03, with the labels that each got.

#2232 [UXE-5880] feat implements azion query language
  src/templates/advanced-filter/component/index.js
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
  src/views/RealTimeEvents/Blocks/components/chips-default-display.vue
  src/views/RealTimeEvents/Blocks/components/chips-in-display.vue
  src/views/RealTimeEvents/Blocks/components/code-editor.vue
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
Labels: console-measurements

#2231 [UXE-6347] feat: console real time events UI replace drawer sections with table
  package.json
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-dns/load-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/templates/info-drawer-block/index.vue
  src/templates/info-drawer-block/info-section/index.vue
  src/templates/list-table-block/columns/log-body.vue
  src/templates/list-table-block/index.vue
  src/tests/modules/real-time-events/constants/tabs-events.test.js
  src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
  src/tests/services/real-time-events-service/activity-history/load-activity-history.test.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/data-stream/load-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-dns/load-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions-console/load-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/edge-functions/load-edge-functions.test.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
  src/tests/services/real-time-events-service/http-request/load-http-request.test.js
  src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
  src/tests/services/real-time-events-service/image-processor/load-image-processor.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
  src/tests/services/real-time-events-service/tiered-cache/load-tiered-cache.test.js
  src/views/RealTimeEvents/Blocks/constants/tabs-events.js
  src/views/RealTimeEvents/Drawer/activityHistory.vue
  src/views/RealTimeEvents/Drawer/dataStream.vue
  src/views/RealTimeEvents/Drawer/edgeDNS.vue
  src/views/RealTimeEvents/Drawer/edgeFunctions.vue
  src/views/RealTimeEvents/Drawer/edgeFunctionsConsole.vue
  src/views/RealTimeEvents/Drawer/httpRequests.vue
  src/views/RealTimeEvents/Drawer/imageProcessor.vue
  src/views/RealTimeEvents/Drawer/tableEvents.vue
  src/views/RealTimeEvents/Drawer/tieredCache.vue
  yarn.lock
Labels: enhancement

#2235 [UXE-6347] fix: fixed showing the skeleton
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/templates/info-drawer-block/info-section/index.vue
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
  src/views/RealTimeEvents/Blocks/azion-query-language.js
Labels: code-refactor

#2236 Refactor: code refactor after validation real-time events
  src/helpers/build-summary.js
  src/layout/components/navbar/feedback.vue
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/templates/info-drawer-block/index.vue
  src/templates/info-drawer-block/info-section/index.vue
  src/tests/services/real-time-events-service/http-request/load-http-request.test.js
  src/views/RealTimeEvents/Drawer/activityHistory.vue
  src/views/RealTimeEvents/Drawer/dataStream.vue
  src/views/RealTimeEvents/Drawer/edgeDNS.vue
  src/views/RealTimeEvents/Drawer/edgeFunctions.vue
  src/views/RealTimeEvents/Drawer/edgeFunctionsConsole.vue
  src/views/RealTimeEvents/Drawer/httpRequests.vue
  src/views/RealTimeEvents/Drawer/imageProcessor.vue
  src/views/RealTimeEvents/Drawer/tieredCache.vue
Labels: code-refactor

#2238 Refactor: Remove source fields on the real time events
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-dns/load-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
Labels: code-refactor

#2243 [NO-ISSUE] refactor: order by desc real-time events
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
  src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
Labels: code-refactor

#2245 [NO-ISSUE] chore: add new workflows github actions
  .github/workflows/ai-review.yml
  .github/workflows/complexity_check.yml
Labels: workflow-github

#2247 [UXE-6706] fix: disabled button re-purge to rows with request data null
  src/services/real-time-purge/list-real-time-purge-service.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
  src/views/RealTimePurge/ListView.vue
Labels: bug

#2246 [UXE-6732] fix: Show correct query from real-time events in GQL Playground
  src/services/real-time-events-service/get-total-records.js
Labels: bug

#2248 [UXE-6708] feat: update link for opening tickets in the console
  src/helpers/azion-documentation-window-opener.js
Labels: enhancement

#2249 [UXE-6740] feat: add 5 minutes option to Real Time Events filter
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/tests/services/real-time-events-service/activity-history/list-activity-history.test.js
  src/tests/services/real-time-events-service/data-stream/list-data-stream.test.js
  src/tests/services/real-time-events-service/edge-dns/list-edge-dns.test.js
  src/tests/services/real-time-events-service/edge-functions-console/list-edge-functions-console.test.js
  src/tests/services/real-time-events-service/edge-functions/list-edge-functions.test.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
  src/tests/services/real-time-events-service/image-processor/list-image-processor.test.js
  src/tests/services/real-time-events-service/tiered-cache/list-tiered-cache.test.js
  src/views/RealTimeEvents/Blocks/constants/date-time-interval.js
  src/views/RealTimeEvents/Blocks/interval-filter-block.vue
Labels: enhancement

#2254 [UXE-6026] fix: hide Edge Firewall field for users without view permission on Add/Edit Domain page
  src/services/domains-services/create-domain-service.js
  src/services/domains-services/edit-domain-service.js
  src/services/edge-firewall-services/v4/list-edge-firewall-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: bug

#2258 [UXE-6744] fix: Events drawer not displaying data for specific events
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/tests/services/real-time-events-service/http-request/list-http-request.test.js
Labels: bug

#2262 [UXE-6707] feat: check the edge and workload are locked
  src/services/edge-application-services/v4/clone-edge-application-service.js
  src/tests/services/edge-application-services/v4/clone-edge-applications-service.test.js
Labels: enhancement

#2257 [UXE-6650] fix: Adjust Billing values between rtm and console (Tiered Cache)
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
Labels: bug

#2260 [UXE-6469] fix: allow users without WAF or NL permissions to edit Rule in EF
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#2270 [UXE-6484] fix: remove error message when user has no access to edge functions and disable selector
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#2265 [UXE-6612] fix: update time filter on the Real-Time Events for each request
  src/views/RealTimeEvents/Blocks/constants/filter-time.js
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
  src/views/RealTimeEvents/Blocks/interval-filter-block.vue
Labels: enhancement

#2264 [UXE-6641] fix: adjust timezone in requests to real time events
  src/helpers/convert-date.js
  src/helpers/index.js
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/get-timezone.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
Labels: bug

#2271 [UXE-6718] fix: behavior not contains in Real Time Events
  src/helpers/convert-gql.js
  src/views/RealTimeEvents/Blocks/azion-query-language.js
Labels: bug

#2253 [UXE-6704] feat: add action export invoice in billing
  src/helpers/convert-date.js
  src/helpers/invoice.js
  src/services/billing-services/list-payment-history-service.js
  src/services/billing-services/load-invoice-data-service.js
  src/tests/services/billing-services/list-payment-history-service.test.js
  src/tests/services/billing-services/load-invoice-data-service.test.js
  src/views/Billing/BillsView.vue
  src/views/Billing/InvoiceDetailsView.vue
Labels: console-measurements

#2278 [UXE-6778] feat: remove "per" from subtitles on billing page
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
  src/services/billing-services/list-service-and-products-changes.js
  src/tests/services/billing-services/list-service-and-products-changes-accounting-service.test.js
  src/tests/services/billing-services/list-service-and-products-changes.test.js
Labels: enhancement

#2275 [UXE-6703] fix: ordering billing regions A->Z
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
Labels: bug

#2279 [UXE-6779] chore: remove edge storage billing page
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
  src/services/billing-services/list-service-and-products-changes.js
Labels: enhancement

#2282 [NO-ISSUE] fix: remove object view on domains edge application dropdown
  src/services/edge-application-services/v4/list-edge-applications-service.js
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: bug

#2285 [UXE-6492] fix: Edge Firewall Rules Engine - Network Lists no loading
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
Labels: bug

#2289 [UXE-6312] fix: add missing Criteria variables in edge application rules engine
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#2288 [UXE-6072] fix: format the date with the correct timezone digital certificates
  src/helpers/account-timezone.js
  src/helpers/index.js
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/get-timezone.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/tests/helpers/account-timezone.test.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
Labels: bug

#2292 [UXE-6422] chore: add personal tokens, domains and variables to cleanup script
  cypress/e2e/teams-permissions/create-team-view-permissions.cy.js
  scripts/cleanup.js
Labels: e2e tests

#2290 [UXE-6790] fix: ensure summary values are converted to strings to CSV formating
  src/templates/list-table-block/index.vue
Labels: bug

#2294 [UXE-5353] fix: added 3600 seconds as default ttl value
  src/tests/utils/constants.test.js
  src/utils/constants.js
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
Labels: bug

#2287 [UXE-6789] fix: Real Time Events - Unable to filter by Request URI Contains
  src/helpers/convert-gql.js
Labels: bug

#2293 [UXE-6424] fix: update help center URLs in reports
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
Labels: bug

#2296 [UXE-6093] fix: change the origin id to null when there is no error response
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
Labels: bug

#2298 [NO-ISSUE] fix: adjust clone edge application
  src/views/EdgeApplications/Dialog/Clone.vue
Labels: bug

#2299 [NO-ISSUE] fix: format filter query in convertGQLTotalRecords function
  src/helpers/convert-gql.js
Labels: bug

#2295 DEPLOY 2025-03-20
  azion/production/azion.json
  cypress/e2e/teams-permissions/create-team-view-permissions.cy.js
  package.json
  scripts/cleanup.js
  src/helpers/account-timezone.js
  src/helpers/convert-gql.js
  src/helpers/index.js
  src/helpers/invoice.js
  src/modules/real-time-metrics/constants/help-center-urls.js
  src/modules/real-time-metrics/constants/reports.js
  src/services/digital-certificates-services/v4/list-digital-certificates-service.js
  src/services/real-time-events-service/activity-history/list-activity-history.js
  src/services/real-time-events-service/activity-history/load-activity-history.js
  src/services/real-time-events-service/data-stream/list-data-stream.js
  src/services/real-time-events-service/data-stream/load-data-stream.js
  src/services/real-time-events-service/edge-dns/list-edge-dns.js
  src/services/real-time-events-service/edge-functions-console/list-edge-functions-console.js
  src/services/real-time-events-service/edge-functions-console/load-edge-functions-console.js
  src/services/real-time-events-service/edge-functions/list-edge-functions.js
  src/services/real-time-events-service/edge-functions/load-edge-functions.js
  src/services/real-time-events-service/get-timezone.js
  src/services/real-time-events-service/http-request/list-http-request.js
  src/services/real-time-events-service/http-request/load-http-request.js
  src/services/real-time-events-service/image-processor/list-image-processor.js
  src/services/real-time-events-service/image-processor/load-image-processor.js
  src/services/real-time-events-service/tiered-cache/list-tiered-cache.js
  src/services/real-time-events-service/tiered-cache/load-tiered-cache.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderDinaminc.vue
  src/templates/list-table-block/index.vue
  src/tests/helpers/account-timezone.test.js
  src/tests/modules/real-time-metrics/constants/reports.test.js
  src/tests/services/digital-certificates-services/v4/list-digital-certificates-service.test.js
  src/tests/utils/constants.test.js
  src/utils/constants.js
  src/views/EdgeApplications/Dialog/Clone.vue
  src/views/EdgeApplicationsErrorResponses/FormFields/FormFieldsErrorResponses.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/WafRules/Drawer/index.vue
Labels: DEPLOY

#2302 [UXE-6422] test: disable temporarily the edge service resource test
  cypress.config.js
  cypress.config.prod.js
  cypress/e2e/edge-services/edit-edge-service-resource.cy.js
Labels: e2e tests

#2303 [UXE-6406] fix: add watch for browser cache settings to reset maximum TTL value
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
Labels: bug

#2300 [UXE-6731] fix: add domain names to more details drawer in waf tuning
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug

#2304 [UXE-6797] fix: timezone applied to Edge Firewall Rules Engine last modified column
  src/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.js
  src/tests/services/edge-firewall-rules-engine-services/v4/list-edge-firewall-rules-engine-service.test.js
Labels: bug

#2310 [UXE-6870] hotfix: increase WAF rules page size to 2000 to fetch all rules
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  src/services/waf-rules-services/list-waf-rules-service.js
  src/tests/services/waf-rules-services/list-waf-rules-service.test.js
Labels: hotfix

#2314 [UXE-6834] chore: remove config max-age in azsid
  azion.config.mjs
Labels: IAC

#2312 Chore: updated project version to 1.33.5
  package.json
Labels: project version

#2317 [UXE-6834] chore: remove space in config max-age
  azion.config.mjs
Labels: IAC

#2305 [UXE-6657] fix: close waf tuning drawer when esc is pressed
  src/templates/empty-drawer/index.vue
Labels: bug

#2309 [UXE-6848] feat: vcs api v4 urls updates
  src/services/version-control-system-integration-services/list-integrations-service.js
  src/services/version-control-system-integration-services/list-platforms-service.js
  src/services/version-control-system-integration-services/list-repositories-service.js
  src/tests/services/version-control-system-integration-services/list-integrations-service.test.js
  src/tests/services/version-control-system-integration-services/list-platforms-service.test.js
  src/tests/services/version-control-system-integration-services/list-repositories-service.test.js
Labels: enhancement

#2306 [UXE-6131] fix: show correct message when returning status other than 200
  src/services/data-stream-services/load-data-stream-service.js
  src/services/domains-services/load-domain-service.js
  src/services/edge-application-origins-services/load-origin-service.js
  src/services/edge-node-service-services/load-service-edge-node-service.js
  src/services/edge-node-services/load-edge-node-service.js
  src/services/edge-service-services/load-edge-service-services.js
  src/services/users-services/load-user-service.js
  src/services/variables-services/load-variable-service.js
  src/tests/services/domains-services/load-domain-service.test.js
  src/tests/services/edge-application-origins-services/load-origin-service.test.js
  src/tests/services/edge-node-service-services/load-service-edge-node-service.test.js
  src/tests/services/edge-node-services/load-edge-node-service.test.js
  src/tests/services/edge-service-services/load-edge-service-services.test.js
  src/tests/services/users-services/load-user-service.test.js
  src/tests/services/variables-services/load-variable-service.test.js
Labels: bug

#2319 [UXE-6733] fix: Real Time Events advanced filter - incorrect results due to space in query
  src/views/RealTimeEvents/Blocks/azion-query-language.js
  src/views/RealTimeEvents/Blocks/azion-query-language.vue
Labels: bug

#2313 [UXE-6816] fix: Real Time Events custom date not working properly
  src/views/RealTimeEvents/Blocks/content-filter-block.vue
Labels: bug

#2321 [UXE-6734] feat: add support between operation in filter advanced real time events
  src/views/RealTimeEvents/Blocks/azion-query-language.js
Labels: console-measurements

#2322 Chore: updated project version to 1.34.0
  package.json
Labels: project version

#2325 [UXE-6904] fix: change edge application rules behaviors to parse number ids to string
  src/services/edge-application-rules-engine-services/v4/helper-behavior.js
Labels: bug

#2318 [UXE-5991] feat: add delete account option in account settings page
  cypress/e2mock/delete-account.cy.js
  cypress/support/selectors/view-selectors/account-settings.js
  src/services/account-services/delete-account-service.js
  src/services/account-services/index.js
  src/services/account-services/make-account-delete-base-url.js
  src/templates/create-form-block/form-horizontal.vue
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
Labels: enhancement

#2329 [NO-ISSUE] chore: bump project version to 1.35.0
  package.json
Labels: project version

#2328 Deploy 2025-03-28
  package.json
  src/services/edge-application-rules-engine-services/v4/helper-behavior.js
Labels: DEPLOY

#2332 [UXE-6259] fix: added the active value to the data stream put request
  src/services/data-stream-services/edit-data-stream-service.js
  src/tests/services/data-stream-services/edit-data-stream-service.test.js
Labels: bug

#2333 [UXE-6097] feat: enable switch to activate and deactivate user
  src/services/users-services/create-users-service.js
  src/services/users-services/edit-another-user-service.js
  src/views/Users/CreateView.vue
  src/views/Users/FormsFields/FormFieldsUsers.vue
Labels: enhancement

#2327 [UXE-6853] fix: billing screen adjustments
  cypress/support/commands.js
  src/helpers/convert-date.js
  src/layout/components/menu-profile/index.vue
  src/layout/components/navbar/switch-account.vue
  src/services/billing-services/list-payment-history-service.js
  src/services/billing-services/list-service-and-products-changes-accounting-service.js
  src/services/billing-services/list-service-and-products-changes.js
  src/services/billing-services/load-invoice-data-service.js
  src/tests/helpers/convert-date.test.js
  src/views/Billing/InvoiceDetailsView.vue
Labels: bug
