Repository aziontech/azion-console-kit, pull requests merged in 2025-08, with the labels that each got.

#2601 [UXE-7804] fix: add validation schema for WAF rule conditions with required fields
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: bug

#2604 SYNC 2025-07-31
  src/services/v2/adapters/waf-adapter.js
  src/views/WafRules/TabsView.vue
Labels: sync-main-to-dev-after-deploy

#2609 [UXE-7804] fix: updated WAF rules in allowed to validation schema for conditions without value
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: hotfix

#2614 [NO-ISSUE] fix: adjusted WAF rule for match Value null
  src/services/v2/adapters/waf-adapter.js
Labels: bug

#2434 [UXE-7100] feat: adds pagination support to activity history
  src/router/routes/activity-history-routes/index.js
  src/services/activity-history-services/get-activity-history-total-records.js
  src/services/activity-history-services/index.js
  src/services/activity-history-services/list-activity-history-events-service.js
  src/templates/activity-history-block/index.vue
  src/tests/services/activity-history-service/list-activity-history-service.test.js
  src/views/ActivityHistory/ListView.vue
Labels: enhancement

#2584 [UXE-7777] fix: ui should not reflect unsaved waf module state
  src/views/EdgeFirewall/TabsView.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: bug

#2582 [UXE-7430] feat: activity history page not displaying records in console
  src/layout/components/menu-profile/index.vue
Labels: enhancement

#2620 [UXE-7092] feat: upgrade azion-theme version
  package.json
  yarn.lock
Labels: enhancement

#2618 [UXE-7817] fix: resolve issue with disappearing custom headers in Console
  src/services/v2/adapters/data-stream-adapter.js
  src/templates/edit-form-block/index.vue
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/views/DataStream/CreateView.vue
  src/views/DataStream/EditView.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/FormFields/blocks/OutputSection.vue
  src/views/DataStream/FormFields/blocks/TransformSection.vue
  src/views/DataStream/FormFields/composables/validation.js
Labels: bug

#2624 [UXE-7351] feat: implement bucket settings management
  src/composables/useEdgeStorage.js
  src/router/routes/edge-storage/index.js
  src/views/EdgeStorage/CustomView.vue
  src/views/EdgeStorage/Dialog/CredentialCreatedDialog.vue
  src/views/EdgeStorage/Drawer/index.vue
  src/views/EdgeStorage/FormFields/FormFieldsCredential.vue
  src/views/EdgeStorage/FormFields/FormFieldsEdgeStorage.vue
  src/views/EdgeStorage/ListView.vue
  src/views/EdgeStorage/View.vue
Labels: enhancement

#2630 [NO-ISSUE] feat: update azion-theme version
  package.json
  yarn.lock
Labels: enhancement

#2632 [NO-ISSUE] fix: delete dialog bypass
  src/templates/list-table-block/index.vue
Labels: bug

#2634 [UXE-7834] fix: prevent error when editing Edge Connector with null or undefined
  src/services/v2/adapters/edge-connectors-adapter.js
Labels: bug

#2633 [UXE-7803] fix: Edge App - some error message were truncated
  src/templates/toast-block/index.vue
Labels: bug

#2636 [UXE-7357] feat: integrating bucket settings with API
  src/composables/useEdgeStorage.js
  src/services/v2/edge-storage-service.js
  src/views/EdgeStorage/FormFields/FormFieldsEdgeStorage.vue
  src/views/EdgeStorage/View.vue
Labels: enhancement

#2640 [UXE-7873] fix: correct cache settings override display when editing
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue
Labels: bug

#2641 [UXE-7356] fix: Create bucket
  src/composables/useEdgeStorage.js
  src/helpers/azion-documentation-catalog.js
  src/services/v2/edge-storage-service.js
  src/views/EdgeStorage/FormFields/FormFieldsEdgeStorage.vue
  src/views/EdgeStorage/ListView.vue
  src/views/EdgeStorage/View.vue
Labels: enhancement

#2638 [UXE-7865] refactor: removing credentials mock
  src/views/EdgeStorage/Dialog/CredentialCreatedDialog.vue
  src/views/EdgeStorage/Drawer/index.vue
  src/views/EdgeStorage/FormFields/FormFieldsCredential.vue
  src/views/EdgeStorage/FormFields/FormFieldsEdgeStorage.vue
  src/views/EdgeStorage/View.vue
Labels: enhancement

#2639 [UXE-7359] feat: implement file upload by drag and drop
  src/composables/useEdgeStorage.js
  src/services/v2/edge-storage-service.js
  src/views/EdgeStorage/ListView.vue
  src/views/EdgeStorage/components/DragAndDrop.vue
  src/views/EdgeStorage/components/UploadCard.vue
Labels: enhancement

#2643 [UXE-7357] fix: fix responsiveness and add skeleton
  src/views/EdgeStorage/ListView.vue
Labels: enhancement

#2646 [UXE-7360] feat: add folder upload
  src/composables/useEdgeStorage.js
  src/services/v2/edge-storage-service.js
  src/views/EdgeStorage/ListView.vue
  src/views/EdgeStorage/components/DragAndDrop.vue
Labels: enhancement

#2647 [UXE-7364] feat: add edge storage bucket creation through drawer in edge connectors
  src/composables/useEdgeStorage.js
  src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
  src/views/EdgeStorage/Drawer/index.vue
  src/views/EdgeStorage/View.vue
Labels: enhancement

#2642 [UXE-7833] fix: display associated digital certificate when present
  src/services/v2/adapters/digital-certificates-adapter.js
  src/services/v2/digital-certificates-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/views/Workload/FormFields/blocks/protocolSettingsBlock.vue
Labels: bug, do-not-merge

#2650 [UXE-7100] feat: Improvements in Activity History search (pagination + search on backend)
  src/router/routes/activity-history-routes/index.js
  src/services/activity-history-services/index.js
  src/services/activity-history-services/list-events-service.js
  src/services/activity-history-services/make-events-list-base-url.js
  src/services/v2/activity-history-service.js
  src/services/v2/adapters/activity-history-adapter.js
  src/services/v2/index.js
  src/templates/activity-history-block/index.vue
  src/tests/services/activity-history-service/list-activity-history-service.test.js
  src/views/ActivityHistory/ListView.vue
Labels: enhancement

#2655 [UXE-7867] feat: update window title based on navigation
  src/App.vue
  src/router/routes/activity-history-routes/index.js
  src/router/routes/billing-routes/index.js
  src/router/routes/custom-pages-routes/index.js
  src/router/routes/data-stream-routes/index.js
  src/router/routes/digital-certificates-routes/index.js
  src/router/routes/domains/index.js
  src/router/routes/edge-application-routes/index.js
  src/router/routes/edge-connectors-routes/index.js
  src/router/routes/edge-dns-routes/index.js
  src/router/routes/edge-firewall-routes/index.js
  src/router/routes/edge-functions-routes/index.js
  src/router/routes/edge-node-routes/index.js
  src/router/routes/edge-pulse-routes/index.js
  src/router/routes/edge-services-routes/index.js
  src/router/routes/error-routes/index.js
  src/router/routes/github-routes/index.js
  src/router/routes/groups-management-routes/index.js
  src/router/routes/identity-providers-routes/index.js
  src/router/routes/import-github-routes/index.js
  src/router/routes/marketplace-routes/index.js
  src/router/routes/mfa-management-routes/index.js
  src/router/routes/network-lists-routes/index.js
  src/router/routes/password-routes/index.js
  src/router/routes/personal-tokens-routes/index.js
  src/router/routes/real-time-events-routes/index.js
  src/router/routes/real-time-metrics-routes/index.js
  src/router/routes/real-time-purge/index.js
  src/router/routes/reseller-management-routes/index.js
  src/router/routes/team-permission/index.js
  src/router/routes/users-routes/index.js
  src/router/routes/variables-routes/index.js
  src/router/routes/waf-rules-routes/index.js
  src/router/routes/workload-routes/index.js
  src/router/routes/your-settings-routes/index.js
Labels: enhancement

#2656 [UXE-7886] feat: list Edge Connectors and Custom Pages in resource creation screen
  src/templates/create-modal-block/index.vue
Labels: enhancement

#2657 [UXE-7361] navegacao por pastas e diretorios
  src/composables/useEdgeStorage.js
  src/helpers/format-bytes.js
  src/services/v2/adapters/edge-storage-adapter.js
  src/services/v2/edge-storage-service.js
  src/templates/list-table-block/folder-list.vue
  src/views/CompareWithAzion/utils/result-data-parse.js
  src/views/EdgeStorage/ListView.vue
Labels: enhancement

#2660 [UXE-7833] refactor: change the message about pending and failed certificates
  src/views/Workload/FormFields/blocks/protocolSettingsBlock.vue
Labels: code-refactor

#2661 [UXE-7932] refactor: rename setting to behavior
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue
Labels: code-refactor

#2667 [UXE-7363] feat: add files search
  src/templates/list-table-block/folder-list.vue
  src/views/EdgeStorage/ListView.vue
Labels: enhancement

#2672 [UXE-7952] fix: improve OAuth security guard to allow legitimate authentication flows
  src/helpers/account-handler.js
  src/helpers/oauth-security.js
  src/templates/sign-in-block/index.vue
  src/templates/social-idps-block/index.vue
Labels: bug

#2673 DEPLOY 2025-08-21
  azion.config.mjs
  azion/stage/azion.json
  src/helpers/oauth-security.js
  src/main.js
  src/templates/sign-in-block/index.vue
  src/templates/social-idps-block/index.vue
Labels: DEPLOY

#2684 [NO-ISSUE] chore: update azion.json with new origins and routing rules
  azion/production/azion.json
Labels: IAC

#2674 [UXE-7888] refactor: remove unused network list base URL helper function
  src/services/network-lists-services/make-network-list-base-url.js
Labels: code-refactor

#2683 [UXE-7723] feat: add warn and navigation to Application Accelerator module from Rules Engine
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement

#2692 [NO-ISSUE] chore: update CLI version and azion.json with new origins and rules
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
  azion/production/azion.json
  azion/stage/azion.json
Labels: IAC

#2698 [UXE-8943] feat: edge sql insert data drawer
  src/services/v2/adapters/edge-sql-adapter.js
  src/services/v2/edge-sql-service.js
  src/views/EdgeSQL/DatabaseView.vue
  src/views/EdgeSQL/components/RowFormDrawer.vue
Labels: enhancement

#2703 [UXE-8949] fix: console workload trusted ca certificates not displaying
  src/services/v2/adapters/digital-certificates-adapter.js
Labels: code-refactor

#2701 DEPLOY 2025-08-28
  azion/production/azion.json
  src/services/v2/adapters/digital-certificates-adapter.js
  src/views/Domains/FormFields/FormFieldsCreateDomains.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
Labels: DEPLOY

#2681 [UXE-7937] refactor: remove _edge in edge firewall
  src/services/v2/adapters/edge-firewall-adapter.js
  src/services/v2/adapters/edge-firewall-function-adapter.js
  src/services/v2/edge-firewall-function-service.js
  src/views/EdgeFirewallFunctions/ListView.vue
Labels: do-not-merge, code-refactor

#2679 [UXE-7942] feat: remove edge_ prefix from endpoints
  src/services/v2/edge-dns-records-service.js
  src/services/v2/edge-dns-service.js
Labels: enhancement

#2706 [UXE-8956] fix: resolve error when creating Cache Settings
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
Labels: bug

#2711 fix: rename edge_application and edge_firewall fields to application and firewall
  src/services/v2/adapters/workload-adapter.js
  src/services/v2/adapters/workload-deployments-adapter.js
  src/services/v2/workload-service.js
  src/services/workload-deployment-service/edit-workload-deployment-service.js
  src/services/workload-deployment-service/list-workload-deployment-service.js
  src/services/workloads-services/create-workloads-service.js
  src/tests/services/workload-deployment-services/edit-workload-deployment-service.test.js
  src/tests/services/workload-deployment-services/list-workload-deployment-service.test.js
  src/tests/services/workloads-services/create-workloads-service.test.js
  src/views/Workload/Config/validation.js
  src/views/Workload/CreateView.vue
  src/views/Workload/Drawer/index.vue
  src/views/Workload/FormFields/FormFieldsCreateDomains.vue
  src/views/Workload/FormFields/blocks/deploymentSettingsBlock.vue
Labels: bug
