Repository aziontech/azion-console-kit, pull requests merged in 2025-07, with the labels that each got.

#2502 [UXE-7485] refactor: update custom page service and ui
  src/services/v2/adapters/custom-page-adapter.js
  src/services/v2/custom-page-service.js
  src/services/v2/utils/buildQueryParams.js
  src/templates/form-fields-inputs/fieldTextArea.vue
  src/views/CustomPages/Blocks/responseDetailsBlock.vue
  src/views/CustomPages/Blocks/statusCodeBlock.vue
  src/views/CustomPages/Blocks/statusConfigurationBlock.vue
  src/views/CustomPages/ConfigForm/listStatusCode.js
  src/views/CustomPages/ConfigForm/validationSchema.js
  src/views/CustomPages/FormFields/CustomPages.vue
  src/views/CustomPages/View.vue
Labels: code-refactor

#2505 [UXE-7593] refactor: rename json_args to args in edge app functions instance
  src/services/edge-functions-services/v4/create-edge-functions-service.js
  src/services/v2/adapters/edge-application-functions-adapter.js
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
Labels: api-v4-migration

#2506 [UXE-7596] fix: show all edge functions instance on the edge app
  src/services/v2/edge-application-functions-service.js
Labels: bug

#2509 [NO-ISSUE] feat: add status column on the Edge App list page
  src/services/v2/adapters/edge-app-adapter.js
  src/views/EdgeApplications/ListView.vue
Labels: enhancement

#2498 [UXE-7521] feat: edge connectors UI Review and API improvements
  src/services/v2/adapters/digital-certificates-adapter.js
  src/services/v2/adapters/edge-connectors-adapter.js
  src/services/v2/adapters/edge-storage-adapter.js
  src/services/v2/digital-certificates-crl-service.js
  src/services/v2/digital-certificates-service.js
  src/services/v2/edge-storage-service.js
  src/services/v2/index.js
  src/templates/form-fields-inputs/fieldTextIcon.vue
  src/views/DigitalCertificates/Drawer/index.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/EditView.vue
  src/views/EdgeConnectors/FormFields/FormFieldsEdgeConnectors.vue
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectorType.vue
  src/views/EdgeConnectors/FormFields/blocks/General.vue
  src/views/EdgeConnectors/FormFields/blocks/LoadBalancerConfiguration.vue
  src/views/EdgeConnectors/FormFields/blocks/Modules.vue
  src/views/EdgeConnectors/FormFields/blocks/MutualAuthenticationSettings.vue
  src/views/EdgeConnectors/FormFields/blocks/OriginIpAcl.vue
  src/views/EdgeConnectors/FormFields/blocks/Status.vue
  src/views/EdgeConnectors/FormFields/blocks/hmac.vue
  src/views/EdgeConnectors/composables/validation.js
Labels: console-measurements

#2513 [UXE-7594] feat: rules engine ui review and api improvements
  src/helpers/helper-behavior.js
  src/services/v2/adapters/edge-app-rules-engine-adapter.js
  src/services/v2/edge-app-rules-engine-service.js
  src/templates/list-table-block/v2/index.vue
  src/views/EdgeApplicationsRulesEngine/Dialog/components/ReorderedRules.vue
  src/views/EdgeApplicationsRulesEngine/Dialog/components/RuleChangeDetail.vue
  src/views/EdgeApplicationsRulesEngine/Dialog/order-dialog.vue
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: console-measurements

#2515 [UXE-7521] fix: update Edge Connectors address management and data adapters to handle load balancer configuration
  src/services/v2/adapters/edge-connectors-adapter.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
  src/views/EdgeConnectors/composables/validation.js
Labels: bug

#2517 [NO-ISSUE] fix: Edge Connectors - improve error handling and adjusts returns in adapters
  src/helpers/helper-behavior.js
  src/services/v2/adapters/edge-connectors-adapter.js
  src/services/v2/adapters/edge-storage-adapter.js
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeConnectors/composables/validation.js
Labels: bug

#2518 [NO-ISSUE] feat: Dealing with the error when trying to create a let encrypt
  src/services/v2/adapters/digital-certificates-crl-adapter.js
  src/services/v2/adapters/edge-app-adapter.js
  src/services/v2/adapters/edge-firewall-adapter.js
  src/services/v2/adapters/workload-adapter.js
  src/services/v2/base/httpService.js
  src/services/v2/digital-certificates-service.js
  src/services/v2/edge-app-service.js
  src/services/v2/edge-firewall-service.js
  src/services/v2/utils/errorHandler.js
  src/services/v2/utils/hasAnyFieldChanged.js
  src/services/v2/workload-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderWithFilter.vue
  src/views/Workload/FormFields/blocks/deploymentSettingsBlock.vue
  src/views/Workload/FormFields/blocks/domainsBlock.vue
  src/views/Workload/FormFields/blocks/mutualAuthenticationSettingsBlock.vue
  src/views/Workload/ListView.vue
Labels: enhancement

#2519 [UXE-7550] refactor: update data stream adapter to handle sampling and workload filtering with new transform structure
  src/services/v2/adapters/data-stream-adapter.js
  src/services/v2/data-stream-service.js
  src/views/DataStream/FormFields/blocks/RenderTemplateSection.vue
  src/views/DataStream/FormFields/blocks/TransformSection.vue
Labels: api-v4-migration

#2512 [UXE-7575] fix: creating edge dns records with multiple value
  src/services/v2/adapters/edge-dns-records-adapter.js
  src/services/v2/edge-dns-records-service.js
Labels: bug

#2522 [UXE-7550] feat: add last editor and last modified columns to Data Stream list view
  src/services/v2/adapters/data-stream-adapter.js
  src/templates/edit-form-block/index.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/ListView.vue
Labels: api-v4-migration

#2525 [UXE-7550] feat: data stream ui fixes and review
  src/services/v2/adapters/data-stream-adapter.js
  src/services/v2/data-stream-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoader.vue
  src/templates/form-fields-inputs/fieldPickList.vue
  src/views/DataStream/Drawer/index.vue
  src/views/DataStream/FormFields/FormFieldsDataStream.vue
  src/views/DataStream/FormFields/blocks/RenderTemplateSection.vue
  src/views/DataStream/FormFields/composables/validation.js
Labels: api-v4-migration

#2507 [UXE-7572] refactor: cache settings payload structure based in api
  src/templates/form-fields-inputs/fieldMultiselectLazyLoader.vue
  src/utils/constants.js
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/FormFieldsEdgeApplicationCacheSettings.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/ApplicationAccelerator.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/TieredCache.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsDeviceGroups/Drawer/index.vue
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
Labels: api-v4-migration

#2526 [No-ISSUE] refactor: code refactor workload
  src/services/v2/adapters/digital-certificates-adapter.js
  src/services/v2/adapters/workload-adapter.js
  src/services/v2/digital-certificates-service.js
  src/services/v2/utils/errorHandler.js
  src/services/v2/workload-deployments-service.js
  src/services/v2/workload-service.js
  src/templates/form-fields-inputs/fieldDropdownLazyLoaderWithFilter.vue
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/Drawer/index.vue
  src/views/DigitalCertificates/FormFields/FormFieldsCreateDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/blocks/ImportRequestCertificate.vue
  src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
  src/views/DigitalCertificates/FormFields/composables/validation.js
  src/views/Workload/CreateView.vue
  src/views/Workload/EditView.vue
  src/views/Workload/FormFields/blocks/domainsBlock.vue
  src/views/Workload/FormFields/blocks/protocolSettingsBlock.vue
Labels: code-refactor

#2527 [NO-ISSUE] fix: optimize rules engine position swapping and remove cancel button
  src/services/v2/edge-app-rules-engine-service.js
  src/templates/list-table-block/v2/index.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: bug, code-refactor

#2531 [NO-ISSUE] fix: small UI adjustments waf and custom page
  src/services/marketplace-services/load-solution-service.js
  src/views/ImportGitHub/FormFields/FormFieldsImportGithub.vue
  src/views/ImportGitHub/ImportGithubView.vue
  src/views/WafRules/FormFields/FormFieldsAllowed.vue
Labels: code-refactor

#2532 [NO-ISSUE] fix: disable connector type field in edit mode and improve address block UI
  src/services/v2/adapters/edge-connectors-adapter.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectorType.vue
  src/views/EdgeConnectors/FormFields/blocks/hmac.vue
  src/views/EdgeConnectors/composables/validation.js
Labels: bug

#2530 [UXE-7489] feat: copy to clipboard button
  src/templates/copy-block/copy-block.vue
  src/templates/list-table-block/columns/text-with-clipboard-column.vue
  src/views/Domains/EditView.vue
  src/views/Domains/FormFields/FormFieldsEditDomains.vue
  src/views/EdgeDNS/FormFields/FormFieldsEditEdgeDns.vue
  src/views/Workload/FormFields/FormFieldsEditDomains.vue
  src/views/Workload/FormFields/blocks/domainsBlock.vue
Labels: enhancement

#2536 [NO-ISSUE] feat: adjustment on the digital certificate page
  src/services/v2/adapters/digital-certificates-adapter.js
  src/templates/list-table-block/columns/column-builder.js
  src/templates/list-table-block/columns/expand-text-column.vue
  src/views/DigitalCertificates/EditView.vue
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
  src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
  src/views/DigitalCertificates/FormFields/composables/validation.js
  src/views/DigitalCertificates/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/PersonalTokens/ListView.vue
Labels: enhancement

#2543 [NO-ISSUE] fix: adjusting template duplication in data stream
  src/services/v2/adapters/data-stream-adapter.js
Labels: bug

#2541 [NO-ISSUE] fix: adjust edge connectors and improvements description inputs
  package.json
  src/helpers/azion-documentation-catalog.js
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
  src/views/EdgeDNS/FormFields/FormFieldsEdgeDns.vue
  yarn.lock
Labels: bug, code-refactor, console-measurements

#2542 [NO-ISSUE] feat: remove dropdown on criteria and add trash button
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
Labels: enhancement

#2544 [NO-ISSUE] refactor: show edge dns name on the edit page
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/ListView.vue
Labels: enhancement

#2546 [NO-ISSUE] refactor: adjustments to the payment and customPage ui's
  src/services/v2/adapters/custom-page-adapter.js
  src/services/v2/payment-service.js
  src/views/Billing/BillingLayout.vue
  src/views/Billing/BillsView.vue
  src/views/Billing/Drawer/DrawerPaymentMethod.vue
  src/views/Billing/PaymentListView.vue
  src/views/Billing/TabsView.vue
  src/views/Billing/components/notification-payment.vue
  src/views/CustomPages/Blocks/pagesCodeBlock.vue
  src/views/CustomPages/Blocks/responseDetailsBlock.vue
  src/views/CustomPages/Blocks/statusConfigurationBlock.vue
  src/views/CustomPages/ConfigForm/listStatusCode.js
  src/views/CustomPages/ConfigForm/validationSchema.js
  src/views/CustomPages/Drawer/drawerSelectPageCode.vue
  src/views/CustomPages/ListView.vue
Labels: code-refactor

#2548 [NO-ISSUE] feat: edge app cache setting war room
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/ApplicationAccelerator.vue
Labels: code-refactor

#2550 [NO-ISSUE] refactor: minor adjustments after pm review
  src/templates/form-fields-inputs/fieldTextIcon.vue
  src/views/DataStream/FormFields/blocks/OutputSection.vue
  src/views/DataStream/FormFields/blocks/TransformSection.vue
  src/views/DataStream/FormFields/composables/validation.js
  src/views/DataStream/ListView.vue
  src/views/DigitalCertificates/ListView.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/ApplicationAccelerator.vue
  src/views/EdgeConnectors/ListView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/FormFields/FormFieldsRecords.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/Workload/ListView.vue
Labels: code-refactor

#2552 [NO-ISSUE] feat: add modules on the create page edge application
  src/helpers/azion-contact-sales-window-opener.js
  src/helpers/index.js
  src/services/v2/adapters/edge-app-adapter.js
  src/services/v2/edge-app-service.js
  src/views/EdgeApplications/CreateView.vue
  src/views/EdgeApplications/Drawer/index.vue
  src/views/EdgeApplications/FormFields/FormFieldsCreateEdgeApplications.vue
  src/views/EdgeApplications/FormFields/FormFieldsEditEdgeApplications.vue
  src/views/EdgeApplications/FormFields/block/debugEdgeApp.vue
  src/views/EdgeApplications/FormFields/block/generalEdgeApp.vue
  src/views/EdgeApplications/FormFields/block/moduleEdgeApp.vue
  src/views/EdgeApplications/FormFields/block/statusEdgeApp.vue
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
Labels: enhancement

#2553 [NO-ISSUE] fix: setting http and https address values on edge connectors
  src/services/v2/adapters/edge-connectors-adapter.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
  src/views/EdgeConnectors/FormFields/blocks/LoadBalancerConfiguration.vue
  src/views/EdgeConnectors/composables/validation.js
Labels: bug

#2554 [UXE-7702] feat: Prevent saving Rule without a name
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
Labels: bug

#2556 [UXE-7724] fix: correct certificate status display when actual status is "failed"
  src/helpers/format-strings.js
  src/helpers/index.js
  src/services/v2/adapters/digital-certificates-adapter.js
  src/services/v2/utils/adapter/parse-status-utils.js
Labels: bug

#2559 [UXE-7721] fix: adjusted collumn in waf allow rules
  src/views/EdgeApplicationsDeviceGroups/ListView.vue
  src/views/WafRules/ListWafRulesAllowed.vue
Labels: code-refactor

#2557 [UXE-7720] fix: let's encrypt on domain page
  src/services/v2/adapters/digital-certificates-adapter.js
Labels: bug

#2558 [UXE-7722] fix: Let's Encrypt breaking when CNAME/alternative fields are not provided
  src/views/CustomPages/Blocks/pagesCodeBlock.vue
  src/views/CustomPages/Blocks/statusConfigurationBlock.vue
  src/views/CustomPages/Config/listStatusCode.js
  src/views/CustomPages/Config/validationSchema.js
  src/views/CustomPages/Drawer/drawerSelectPageCode.vue
  src/views/CustomPages/Drawer/index.vue
  src/views/CustomPages/View.vue
  src/views/EdgeConnectors/Config/validation.js
  src/views/EdgeConnectors/CreateView.vue
  src/views/EdgeConnectors/EditView.vue
  src/views/Workload/Config/validation.js
  src/views/Workload/CreateView.vue
  src/views/Workload/EditView.vue
Labels: bug, code-refactor

#2563 [UXE-7734] feat: update siem link
  src/services/sidebar-menus-services/menus.js
Labels: enhancement

#2560 feat: add error handling for billing credit and improve payment method
  src/helpers/account-data.js
  src/services/billing-services/load-your-service-plan-service.js
  src/services/v2/billing-gql-service.js
  src/templates/add-payment-method-block/index.vue
  src/templates/list-table-block/index.vue
  src/templates/toast-block/index.vue
  src/tests/services/billing-services/load-your-service-plan-service.test.js
  src/views/Billing/BillsView.vue
  src/views/Billing/PaymentListView.vue
  src/views/Billing/components/notification-payment.vue
Labels: code-refactor

#2570 [UXE-7740] feat: allow CSR creation in Digital Certificates section of Console
  src/views/DigitalCertificates/FormFields/blocks/General.vue
  src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
Labels: bug

#2572 [UXE-7741] fix: ensure Trusted CA field validation only applies when toggle is active
  src/services/domains-services/create-domain-service.js
  src/services/domains-services/edit-domain-service.js
Labels: bug

#2574 [UXE-7743] refactor: improve address form initialization and validation using resetForm
  src/templates/add-payment-method-block/add-address.vue
  src/templates/add-payment-method-block/index.vue
Labels: code-refactor

#2561 [UXE-6903] refactor: create composable for open delete dialog with entity name
  src/composables/useDeleteDialog.js
  src/templates/list-table-block/dialog/delete-dialog.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/v2/index.vue
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/templates/list-table-block/with-selection-behavior.vue
  src/views/AccountSettings/FormFields/FormFieldsAccountSettings.vue
  src/views/DataStream/FormFields/FormFieldsTemplate.vue
  src/views/IdentityProviders/ListView.vue
Labels: enhancement

#2577 [UXE-7214] fix: correct max-age behavior when saving Cache Settings with Honor
  src/services/v2/adapters/edge-app-cache-settings-adapter.js
Labels: bug

#2578 [UXE-7742] refactor: update Edge Functions field names according to new API
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: code-refactor

#2579 [UXE-7759] feat: add ID column to all list views in the console
  src/views/CustomPages/ListView.vue
  src/views/DataStream/ListView.vue
  src/views/DigitalCertificates/ListView.vue
  src/views/EdgeApplications/ListView.vue
  src/views/EdgeApplicationsCacheSettings/ListView.vue
  src/views/EdgeApplicationsFunctions/ListView.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
  src/views/EdgeConnectors/ListView.vue
  src/views/EdgeDNS/EditView.vue
  src/views/EdgeDNS/ListView.vue
  src/views/EdgeFirewall/ListView.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/EdgeFunctions/ListView.vue
  src/views/EdgeServices/ListView.vue
  src/views/NetworkLists/ListView.vue
  src/views/WafRules/ListView.vue
  src/views/Workload/ListView.vue
Labels: enhancement

#2589 [UXE-7785] hotfix: increase page size to 200 when fetching edge application functions
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
Labels: hotfix

#2593 [UXE-7788] fix: network lists country type not saving
  src/views/NetworkLists/EditView.vue
Labels: hotfix

#2587 chore: bump project version to 1.40.0
  package.json
Labels: project version

#2580 [UXE-7726] fix: Digital Certificates - correct placeholder text for private key field
  src/views/DigitalCertificates/FormFields/FormFieldsEditDigitalCertificates.vue
Labels: bug

#2575 [UXE-7725] fix: Fixing the digital certificates table when the process of creating a new certificate is closed
  src/templates/list-table-block/with-fetch-ordering-and-pagination.vue
  src/views/DigitalCertificates/FormFields/composables/certificate.js
  src/views/DigitalCertificates/ListView.vue
Labels: bug
