Repository aziontech/azion-console-kit, pull requests merged in 2025-06, with the labels that each got.

#2454 [UXE-7337] refactor: rules engine services integration
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-cache-policy.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-edge-connectors.cy.js
  cypress/e2e/edge-application/rules-engine/create-rule-engine-set-function.cy.js
  src/helpers/helper-behavior.js
  src/helpers/helper-criteria.js
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-rules-engine-services/create-rules-engine-service.js
  src/services/edge-application-rules-engine-services/delete-rules-engine-service.js
  src/services/edge-application-rules-engine-services/edit-rules-engine-service.js
  src/services/edge-application-rules-engine-services/helper-behavior.js
  src/services/edge-application-rules-engine-services/index.js
  src/services/edge-application-rules-engine-services/list-rules-engine-service.js
  src/services/edge-application-rules-engine-services/load-rules-engine-service.js
  src/services/edge-application-rules-engine-services/v4/create-rules-engine-service.js
  src/services/edge-application-rules-engine-services/v4/delete-rule-service.js
  src/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.js
  src/services/edge-application-rules-engine-services/v4/index.js
  src/services/edge-application-rules-engine-services/v4/list-rules-engine-all-service.js
  src/services/edge-application-rules-engine-services/v4/load-rules-engine-service.js
  src/services/edge-application-rules-engine-services/v4/reorder-rules-engine-service.js
  src/services/v2/adapters/edge-app-rules-engine-adapter.js
  src/services/v2/edge-app-rules-engine-service.js
  src/services/v2/index.js
  src/tests/services/edge-application-rules-engine-services/create-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/delete-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/edit-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/helper-behavior.test.js
  src/tests/services/edge-application-rules-engine-services/list-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/load-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/v4/create-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/v4/delete-rule-service.test.js
  src/tests/services/edge-application-rules-engine-services/v4/edit-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/v4/helper-behavior.test.js
  src/tests/services/edge-application-rules-engine-services/v4/list-rules-engine-service.test.js
  src/tests/services/edge-application-rules-engine-services/v4/load-rules-engine-service.test.js
  src/views/EdgeApplicationsRulesEngine/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/ListView.vue
Labels: enhancement, code-refactor

#2457 [UXE-7415] hotfix: fix display user email when name is not available
  src/views/MFAManagement/ListView.vue
Labels: hotfix

#2461 refactor: Remove unused files related to Edge Firewall
  src/router/routes/edge-firewall-routes/index.js
  src/services/edge-firewall-functions-services/create-function-service.js
  src/services/edge-firewall-functions-services/delete-function-service.js
  src/services/edge-firewall-functions-services/edit-function-service.js
  src/services/edge-firewall-functions-services/index.js
  src/services/edge-firewall-functions-services/list-edge-functions-service.js
  src/services/edge-firewall-functions-services/list-functions-service.js
  src/services/edge-firewall-functions-services/load-function-service.js
  src/services/edge-firewall-functions-services/make-edge-firewall-base-url.js
  src/services/edge-firewall-functions-services/make-edge-functions-base-url.js
  src/services/edge-firewall-rules-engine-services/create-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/delete-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/edit-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/index.js
  src/services/edge-firewall-rules-engine-services/list-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/load-edge-firewall-rules-engine-service.js
  src/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-base-url.js
  src/services/edge-firewall-rules-engine-services/make-edge-firewall-rules-engine-reorder-base-url.js
  src/services/edge-firewall-rules-engine-services/reorder-edge-firewall-rules-engine-service.js
  src/services/v2/adapters/waf-adapter.js
  src/services/v2/waf-service.js
  src/views/EdgeFirewallRulesEngine/FormFields/FormFieldsEdgeFirewallRulesEngine.vue
  src/views/EdgeFirewallRulesEngine/ListView.vue
  src/views/WafRules/ListView.vue
Labels: code-refactor

#2458 [UXE-7334] perf: performance improvements in edge function
  src/services/v2/adapters/edge-function-adapter.js
  src/services/v2/edge-application-functions-service.js
  src/services/v2/edge-function-service.js
  src/views/EdgeApplicationsFunctions/ListView.vue
Labels: performance improvements

#2466 [UXE-7279] feat: error handle MFA
  src/router/routes/mfa-management-routes/index.js
  src/services/v2/adapters/mfa-adapter.js
  src/services/v2/index.js
  src/services/v2/mfa-service.js
  src/views/MFAManagement/ListView.vue
Labels: enhancement

#2467 [UXE-7331] fix: adjust view edge dns required in ui validation
  src/services/v2/adapters/edge-dns-adapter.js
  src/services/v2/edge-dns-service.js
  src/templates/form-fields-inputs/fieldTextIcon.vue
  src/views/EdgeDNS/FormFields/FormFieldsEditEdgeDns.vue
Labels: bug, code-refactor

#2468 [UXE-7339] feat: error handling edge api function
  src/router/routes/edge-firewall-routes/index.js
  src/router/routes/edge-functions-routes/index.js
  src/services/edge-functions-services/create-edge-functions-service.js
  src/services/edge-functions-services/delete-edge-functions-service.js
  src/services/edge-functions-services/edit-edge-functions-service.js
  src/services/edge-functions-services/index.js
  src/services/edge-functions-services/list-edge-functions-service.js
  src/services/edge-functions-services/load-edge-functions-service.js
  src/services/edge-functions-services/make-edge-functions-base-url.js
  src/services/edge-functions-services/v4/create-edge-functions-service.js
  src/services/edge-functions-services/v4/delete-edge-function-service.js
  src/services/edge-functions-services/v4/edit-edge-functions-service.js
  src/services/edge-functions-services/v4/index.js
  src/services/edge-functions-services/v4/list-edge-functions-dropdown-service.js
  src/services/edge-functions-services/v4/list-edge-functions-service.js
  src/services/edge-functions-services/v4/load-edge-function-service.js
  src/services/edge-functions-services/v4/make-edge-functions-base-url.js
  src/services/mfa-services/v4/delete-mfa-service.js
  src/services/mfa-services/v4/index.js
  src/services/mfa-services/v4/list-mfa-users-service.js
  src/services/mfa-services/v4/load-user-service.js
  src/services/mfa-services/v4/make-mfa-management-base-url.js
  src/services/v2/adapters/edge-function-adapter.js
  src/services/v2/edge-function-service.js
  src/tests/services/edge-functions-services/create-edge-functions-service.test.js
  src/tests/services/edge-functions-services/delete-edge-functions-service.test.js
  src/tests/services/edge-functions-services/edit-edge-functions-service.test.js
  src/tests/services/edge-functions-services/list-edge-functions-service.test.js
  src/tests/services/edge-functions-services/load-edge-functions-service.test.js
  src/tests/services/edge-functions-services/make-edge-functions-base-url.test.js
  src/tests/services/edge-functions-services/v4/create-edge-functions-service.test.js
  src/tests/services/edge-functions-services/v4/delete-edge-function-service.test.js
  src/tests/services/edge-functions-services/v4/edit-edge-functions-service.test.js
  src/tests/services/edge-functions-services/v4/list-edge-functions-dropdown-service.test.js
  src/tests/services/edge-functions-services/v4/list-edge-functions-service.test.js
  src/tests/services/edge-functions-services/v4/load-edge-function-service.test.js
  src/tests/services/edge-functions-services/v4/make-edge-functions-base-url.test.js
  src/tests/services/mfa-services/v4/delete-mfa-service.test.js
  src/tests/services/mfa-services/v4/list-mfa-users-service.test.js
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFunctions/CreateView.vue
  src/views/EdgeFunctions/Drawer/index.vue
  src/views/EdgeFunctions/EditView.vue
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
  src/views/EdgeFunctions/ListView.vue
  vitest.config.js
Labels: enhancement

#2471 [UXE-7458] feat: implements new component dropdown multi select lazy loader
  src/templates/form-fields-inputs/fieldDropdownMultiSelectLazyLoader.vue
Labels: console-measurements

#2479 [UXE-7503] feat: adjustments api v4 Edge FW function instances
  src/services/v2/adapters/edge-firewall-adapter.js
  src/services/v2/adapters/edge-firewall-function-adapter.js
  src/views/EdgeFirewall/EditView.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/EdgeFirewallRulesEngine/Drawer/index.vue
Labels: enhancement

#2483 [UXE-7504] feat: update vendor and icon display fallbacks in edge functions
  src/services/v2/adapters/edge-function-adapter.js
  src/views/EdgeFunctions/ListView.vue
Labels: enhancement

#2484 [UXE-7506] feat: purge ui general adjustments
  src/services/real-time-purge/list-real-time-purge-service.js
  src/tests/services/real-time-purge/list-real-time-purge.test.js
  src/views/RealTimePurge/Dialog/index.vue
  src/views/RealTimePurge/FormFields/FormFieldsCreateRealTimePurge.vue
  src/views/RealTimePurge/ListView.vue
Labels: enhancement

#2480 [UXE-7503] refactor: adjustments api v4 function instances
  cypress/e2e/edge-firewall/create-edge-firewall-function.cy.js
  src/views/EdgeFirewall/CreateView.vue
  src/views/EdgeFirewall/FormFields/FormFieldsEdgeFirewall.vue
  src/views/EdgeFirewallFunctions/ListView.vue
Labels: code-refactor

#2481 [UXE-7481] feat: enhance digital certificate forms with dynamic titles and placeholders based on certificate type
  src/services/v2/adapters/digital-certificates-csr-adapter.js
  src/views/DigitalCertificates/CreateView.vue
  src/views/DigitalCertificates/FormFields/blocks/ImportServerCertificate.vue
  src/views/DigitalCertificates/FormFields/blocks/RequestCertificate.vue
  src/views/DigitalCertificates/FormFields/composables/certificate.js
  src/views/DigitalCertificates/FormFields/composables/validation.js
  src/views/DigitalCertificates/ListView.vue
Labels: console-measurements
