Repository aziontech/azion-console-kit, pull requests merged in 2025-09, with the labels that each got.

#2708 DEPLOY 2025-09-01
  src/helpers/helper-behavior.js
  src/services/v2/adapters/edge-app-adapter.js
  src/services/v2/adapters/edge-application-functions-adapter.js
  src/services/v2/adapters/edge-connectors-adapter.js
  src/services/v2/adapters/edge-firewall-adapter.js
  src/services/v2/adapters/edge-firewall-function-adapter.js
  src/services/v2/adapters/workload-adapter.js
  src/services/v2/adapters/workload-deployments-adapter.js
  src/services/v2/edge-application-functions-service.js
  src/services/v2/edge-connectors-service.js
  src/services/v2/edge-dns-records-service.js
  src/services/v2/edge-dns-service.js
  src/services/v2/edge-firewall-function-service.js
  src/services/v2/workload-service.js
  src/services/workload-deployment-service/edit-workload-deployment-service.js
  src/services/workload-deployment-service/list-workload-deployment-service.js
  src/services/workloads-services/create-workloads-service.js
  src/tests/services/workload-deployment-services/edit-workload-deployment-service.test.js
  src/tests/services/workload-deployment-services/list-workload-deployment-service.test.js
  src/tests/services/workloads-services/create-workloads-service.test.js
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsRulesEngine/FormFields/FormFieldsEdgeApplicationsRulesEngine.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectionOptions.vue
  src/views/EdgeConnectors/FormFields/blocks/ConnectorType.vue
  src/views/EdgeFirewallFunctions/ListView.vue
  src/views/Workload/Config/validation.js
  src/views/Workload/CreateView.vue
  src/views/Workload/Drawer/index.vue
  src/views/Workload/FormFields/FormFieldsCreateDomains.vue
  src/views/Workload/FormFields/blocks/deploymentSettingsBlock.vue
Labels: DEPLOY

#2713 [NO-ISSUE] fix: update baseURL for edge connectors service
  src/services/v2/edge-connectors-service.js
Labels: bug, hotfix

#2714 DEPLOY 2025-09-01
  src/services/v2/edge-connectors-service.js
Labels: DEPLOY

#2718 [NO-ISSUE] chore: upgrade azion cli version
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-stage.yml
Labels: dependencies

#2710 [UXE-7498] feat: conditionally show Origins and Error Responses tabs
  cypress/e2mock/edge-application/tabs-visibility.cy.js
  cypress/fixtures/account/info/workload_flags.json
  cypress/fixtures/edge-application/edge-application-item-v3.json
  cypress/fixtures/edge-application/edge-application-item-v4.json
  cypress/support/selectors/product-selectors/edge-application.js
  src/views/EdgeApplications/TabsView.vue
Labels: enhancement, e2mock

#2722 [NO-ISSUE] fix: reordering edge app tabs when edge functions are disabled
  src/views/EdgeApplications/TabsView.vue
Labels: bug

#2715 [UXE-8974] fix: correct disabling of configuration fields and validation
  src/services/v2/adapters/edge-connectors-adapter.js
  src/views/EdgeConnectors/Config/validation.js
  src/views/EdgeConnectors/FormFields/blocks/Address.vue
  src/views/EdgeConnectors/FormFields/blocks/LoadBalancerConfiguration.vue
Labels: bug

#2688 [UXE-7761] refactor: update status code headers and sort order in custom pages UI
  src/views/CustomPages/Blocks/pagesCodeBlock.vue
  src/views/CustomPages/Config/listStatusCode.js
Labels: enhancement

#2726 [UXE-8984] fix: resolve 400 error when updating Trusted CA certificate
  src/services/v2/adapters/digital-certificates-adapter.js
Labels: bug

#2719 [UXE-8975] fix: migrate error response to v2 service
  src/router/routes/edge-application-routes/index.js
  src/services/edge-application-error-responses-services/edit-error-responses-service.js
  src/services/edge-application-error-responses-services/index.js
  src/services/edge-application-error-responses-services/list-error-responses-service.js
  src/services/edge-application-error-responses-services/make-edge-application-error-responses-base-url.js
  src/services/v2/adapters/edge-app-error-response-adapter.js
  src/services/v2/edge-app-error-response-service.js
  src/services/v2/index.js
  src/tests/services/edge-application-error-responses/edit-error-responses-services.test.js
  src/tests/services/edge-application-error-responses/list-error-responses-service.test.js
  src/views/EdgeApplications/TabsView.vue
  src/views/EdgeApplicationsErrorResponses/EditView.vue
Labels: bug

#2741 feat: pin vulnerable npm packages to safe versions
  package.json
  yarn.lock
Labels: enhancement

#2736 [UXE-8967] feat: new version of the login screen with performance improvements
  index.html
  src/App.vue
  src/helpers/account-data.js
  src/layout/app-footer.vue
  src/layout/components/menu-production/index.vue
  src/layout/components/navbar/button-helper.vue
  src/layout/components/navbar/create.vue
  src/layout/index.vue
  src/main.js
  src/plugins/sentry/SentryPlugin.js
  src/plugins/sentry/index.js
  src/plugins/sentry/sentry-feedback.css
  src/router/hooks/afterEachRoute.js
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/SSOManagementGuard.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/router/hooks/guards/cliGuard.js
  src/router/hooks/guards/domainsLimitGuard.js
  src/router/hooks/guards/flagGuard.js
  src/router/hooks/guards/index.js
  src/router/hooks/guards/redirectGuard.js
  src/router/hooks/guards/themeGuard.js
  src/router/routes/data-stream-routes/index.js
  src/router/routes/identity-providers-routes/index.js
  src/router/routes/login-routes/index.js
  src/router/routes/signup-routes/index.js
  src/services/social-idps-services/index.js
  src/services/social-idps-services/list-social-idps-service.js
  src/services/social-idps-services/make-list-social-idps-base-url.js
  src/services/v2/adapters/iam-adapter.js
  src/services/v2/iam-service.js
  src/services/v2/index.js
  src/templates/list-table-block/index.vue
  src/templates/sign-in-block/index.vue
  src/templates/signup-block/form-signup-block.vue
  src/templates/signup-block/social-signup-block.vue
  src/templates/social-idps-block/index.vue
  src/tests/services/social-idps-services/list-social-idps-service.test.js
  src/views/Home/HomeView.vue
  src/views/Login/LoginView.vue
  src/views/Signup/SignupView.vue
  vite.config.js
Labels: enhancement

#2745 DEPLOY 2025-09-10 - 3
  index.html
  src/App.vue
  src/helpers/account-data.js
  src/layout/app-footer.vue
  src/layout/components/menu-production/index.vue
  src/layout/components/navbar/button-helper.vue
  src/layout/components/navbar/create.vue
  src/layout/index.vue
  src/main.js
  src/plugins/sentry/SentryPlugin.js
  src/plugins/sentry/index.js
  src/plugins/sentry/sentry-feedback.css
  src/router/hooks/afterEachRoute.js
  src/router/hooks/beforeEachRoute.js
  src/router/hooks/guards/SSOManagementGuard.js
  src/router/hooks/guards/accountGuard.js
  src/router/hooks/guards/billingGuard.js
  src/router/hooks/guards/cliGuard.js
  src/router/hooks/guards/domainsLimitGuard.js
  src/router/hooks/guards/flagGuard.js
  src/router/hooks/guards/index.js
  src/router/hooks/guards/redirectGuard.js
  src/router/hooks/guards/themeGuard.js
  src/router/routes/data-stream-routes/index.js
  src/router/routes/identity-providers-routes/index.js
  src/router/routes/login-routes/index.js
  src/router/routes/signup-routes/index.js
  src/services/social-idps-services/index.js
  src/services/social-idps-services/list-social-idps-service.js
  src/services/social-idps-services/make-list-social-idps-base-url.js
  src/services/v2/adapters/iam-adapter.js
  src/services/v2/iam-service.js
  src/services/v2/index.js
  src/templates/list-table-block/index.vue
  src/templates/sign-in-block/index.vue
  src/templates/signup-block/form-signup-block.vue
  src/templates/signup-block/social-signup-block.vue
  src/templates/social-idps-block/index.vue
  src/tests/services/social-idps-services/list-social-idps-service.test.js
  src/views/Home/HomeView.vue
  src/views/Login/LoginView.vue
  src/views/Signup/SignupView.vue
  vite.config.js
Labels: DEPLOY

#2757 [UXE-5287] fix: add cnames to WAF Tunning
  src/services/waf-rules-services/list-waf-rules-domain-service.js
  src/views/WafRules/Drawer/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: bug, do-not-merge

#2774 [UXE-9048] feat: enable save/cancel for WAF Tuning details using client flag
  src/stores/account.js
  src/views/WafRules/Drawer/index.vue
Labels: enhancement

#2761 [UXE-9035] fix: resolve unexpected error when selecting newly created function from drawer
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFunctions/Drawer/index.vue
Labels: bug

#2755 [UXE-7982] feat: Sql Database
  cypress.env.example.json
  cypress/e2e/edge-sql/create-edge-sql-database.cy.js
  cypress/e2e/edge-sql/edge-sql-database-interface.cy.js
  cypress/e2mock/edge-sql.cy.js
  cypress/fixtures/edge-sql/database-tables.json
  cypress/fixtures/edge-sql/databases-list.json
  cypress/fixtures/edge-sql/query-error-responses.json
  cypress/fixtures/edge-sql/query-results.json
  cypress/support/commands.js
  cypress/support/selectors.js
  cypress/support/selectors/product-selectors/edge-sql.js
  src/helpers/azion-documentation-catalog.js
  src/router/index.js
  src/router/routes/edge-sql-routes/index.js
  src/services/sidebar-menus-services/menus.js
  src/services/v2/adapters/edge-sql-adapter.js
  src/services/v2/edge-sql-service.js
  src/services/v2/index.js
  src/services/v2/utils/adapter/handleSqlCommand.js
  src/templates/create-form-block/index.vue
  src/templates/empty-results-block/index.vue
  src/templates/list-table-block/index.vue
  src/templates/list-table-block/with-row-edit.vue
  src/views/EdgeSQL/CreateView.vue
  src/views/EdgeSQL/DatabaseView.vue
  src/views/EdgeSQL/FormFields/FormFieldsCreateDatabase.vue
  src/views/EdgeSQL/FormFields/blocks/ListTablesBlock.vue
  src/views/EdgeSQL/FormFields/blocks/QueryEditorBlock.vue
  src/views/EdgeSQL/FormFields/blocks/ResultsBlock.vue
  src/views/EdgeSQL/FormFields/blocks/SqlDefinition.vue
  src/views/EdgeSQL/FormFields/blocks/TableInfo.vue
  src/views/EdgeSQL/ListView.vue
  src/views/EdgeSQL/components/QueryHistory.vue
  src/views/EdgeSQL/composable/useEdgeSQL.js
  src/views/EdgeSQL/constants/index.js
  src/views/EdgeSQL/constants/queries.js
  src/views/EdgeSQL/utils/index.js
  src/views/EdgeSQL/utils/table-actions.js
  yarn.lock
Labels: enhancement

#2769 [UXE-7975] feat: Cache Settings - applying a handle to Honor Cache behavior
  src/views/EdgeApplicationsCacheSettings/Drawer/index.vue
  src/views/EdgeApplicationsCacheSettings/FormFields/blocks/EdgeCache.vue
Labels: bug

#2778 [UXE-9029] fix: integration validation Form Builder blocking send request data
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeApplicationsFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/FormFields/FormFieldsEdgeApplicationsFunctions.vue
  src/views/EdgeFunctions/CreateView.vue
  src/views/EdgeFunctions/EditView.vue
  src/views/EdgeFunctions/FormFields/FormFieldsCreateEdgeFunctions.vue
  src/views/EdgeFunctions/FormFields/FormFieldsEditEdgeFunctions.vue
Labels: enhancement, hotfix

#2781 [UXE-7843] feat: share block on Edit Function Instance
  src/layout/components/navbar/share-url.vue
  src/templates/edit-drawer-block/index.vue
  src/views/EdgeApplicationsFunctions/Drawer/index.vue
  src/views/EdgeFirewallFunctions/Drawer/index.vue
Labels: enhancement

#2747 [UXE-9013] feat: add bucket table
  src/composables/useEdgeStorage.js
  src/router/routes/edge-storage/index.js
  src/services/sidebar-menus-services/menus.js
  src/services/v2/adapters/edge-storage-adapter.js
  src/templates/list-table-block/folder-list.vue
  src/views/EdgeStorage/Drawer/index.vue
  src/views/EdgeStorage/ListView.vue
  src/views/EdgeStorage/View.vue
  src/views/EdgeStorage/components/BucketListTable.vue
  src/views/EdgeStorage/components/DragAndDrop.vue
Labels: enhancement, do-not-merge

#2758 [UXE-9024] feat: Edge Storage - add bucket size metrics
  src/services/v2/adapters/edge-storage-adapter.js
  src/services/v2/edge-storage-service.js
  src/views/EdgeStorage/ListView.vue
  src/views/EdgeStorage/components/BucketListTable.vue
Labels: enhancement, do-not-merge

#2777 [UXE-7361] feat: Edge Storage folder navigation
  package.json
  src/composables/useEdgeStorage.js
  src/main.js
  src/router/routes/edge-storage/index.js
  src/services/sidebar-menus-services/menus.js
  src/services/v2/adapters/edge-storage-adapter.js
  src/services/v2/edge-storage-service.js
  src/templates/list-table-block/folder-list.vue
  src/utils/icons.js
  src/views/EdgeStorage/ListView.vue
  yarn.lock
Labels: enhancement, do-not-merge

#2783 [UXE-9046] allowed rule only by regex
  src/helpers/convert-waf-rules-tuning 2.js
  src/services/v2/adapters/waf-adapter.js
  src/services/v2/waf-service.js
  src/templates/form-fields-inputs/fieldGroupRadio.vue
  src/views/WafRules/Dialog/index.vue
  src/views/WafRules/Drawer/allowedRules.vue
  src/views/WafRules/Drawer/index.vue
  src/views/WafRules/ListWafRulesTuning.vue
Labels: console-measurements

#2800 fix: adjust import for workload deployment and add parameter workload id
  src/services/v2/workload/workload-service.js
Labels: bug

#2796 [UXE-9078] feat: restrict object storage access to Azion email users
  src/composables/user-flag.js
  src/helpers/account-data.js
  src/router/hooks/guards/flagGuard.js
  src/router/routes/edge-storage/index.js
  src/services/sidebar-menus-services/menus.js
  src/tests/services/sidebar-menus-services/list-sidebar-menus-service.test.js
Labels: enhancement

#2803 [UXE-9072] feat: update rules engine for ignore edge_storage routes
  azion.config.mjs
Labels: enhancement

#2808 feat: enhance WAF rules drawer with regex validation and examples
  src/templates/form-fields-inputs/fieldText.vue
  src/views/WafRules/Config/regexValidator.js
  src/views/WafRules/Drawer/allowedRules.vue
  src/views/WafRules/Drawer/components/regexExamples.vue
  src/views/WafRules/Drawer/components/topPaths.vue
  src/views/WafRules/Drawer/index.vue
Labels: console-measurements

#2811 [NO-ISSUE] hotfix: fix wildcard domain parsing and action rendering across tables and billing
  src/services/v2/utils/adapter/domainAdapter.js
  src/templates/list-table-block/index.vue
  src/views/Billing/BillsView.vue
  src/views/Workload/Config/validation.js
Labels: hotfix

#2810 [UXE-9094] fix: asterisks as subdomain in workloads
  src/services/v2/utils/adapter/domainAdapter.js
Labels: bug

#2818 [NO-ISSUE] feat: centralize cache configurations and update refetch intervals
  src/helpers/account-data.js
  src/services/v2/account/contract-service.js
  src/services/v2/base/query/baseService.js
  src/services/v2/base/query/config.js
  src/services/v2/base/query/queryClient.js
Labels: hotfix

#2827 [NO-ISSUE] fix: add error handling to encoding and decoding functions in cacheStore
  src/services/v2/base/query/cacheStore.js
Labels: hotfix
